ArrayList< A >
NAME
ArrayList< A > - An implementation of a list backed by a resizable array.
SYNOPSIS
#include <ArrayList.hpp>
Inherits IList< A >.
Inherited by ArraySet< A >, SortedArrayList< A >, and Stack< A > [private].
Public Member Functions
void append (A &&elem) override
Appends the given element to the list.
void append (A const &elem) override
Appends the given element to the list.
void appendAll (ArrayList< A > const &l)
Append all elements of the given list to this one.
ArrayList ()
ArrayList (ArrayList< A > const &other)
ArrayList (unsigned reserved)
Preallocate memory for the given amount of elements.
unsigned capacity () const
return the current maximum capacity of the array
void clear () override
Clears the list.
bool contains (A const &elem) const override
Returns true if the given element is contained in the list.
std::unique_ptr< ArrayList< A > > difference (ArrayList< A > const &list) const
Returns the set difference of this list and the provided one.
std::unique_ptr< ArrayList< A > > distinct () const
Construct a new list using the elements of this one but ensuring that the elements of the new list are distinct.
void expand ()
Double the capacity of the array.
void fill ()
Fill the array with elements created with the default constructor.
void fill (A const &elem)
Fill the entire array with the given element.
std::unique_ptr< ArrayList< A > > filter (std::function< bool(const A &)> predicate) const
Return a new ArrayList containing all elements in the current list that match the provided predicate.
int find (std::function< bool(const A &)> predicate) const
template<typename B , typename = std::enable_if_t<std::is_base_of<IList<B>, A>::value>> std::unique_ptr< ArrayList< B > > flatten ()
Convert a list of lists into a single list containing all elements of the previously contained lists.
A fold (A start, std::function< A(const A &, const A &)> biconsumer)
Return the result of applying the provided function to the result of the previous application or the provided starting value and the next element in the list until all the elements of the list have been consumed.
void foreach (std::function< void(const A &)> consumer) const
Applies the provided function to each element of the list in order.
A & get (unsigned index) const override
Returns the value at the index.
void insert (A &&elem, unsigned at) override
Inserts the given element in the list at the specified position.
void insert (A const &elem, unsigned at) override
Inserts the given element in the list at the specified position.
std::unique_ptr< ArrayList< A > > intersection (ArrayList< A > const &list) const
Returns the set intersection of this list and the provided one.
unsigned length () const final
return the amount of elements currently in the array
template<typename B > std::unique_ptr< ArrayList< B > > map (std::function< B(const A &)> mapper) const
Return a new ArrayList containing the result of applying the provided mapping function to each element of the list in order.
ArrayList< A > & operator= (ArrayList< A > const &other)
bool operator== (ArrayList< A > const &other)
std::unique_ptr< Nullable< A > > pop () override
Removes the last element of the list, if any, and returns it.
void prepend (A &&elem) override
Prepends the given element to the list.
void prepend (A const &elem) override
Prepends the given element to the list.
void prependAll (ArrayList< A > const &l)
Prepend all elements of the given list to this one.
int remove (const A &elem) override
Remove the first occurence of the given element in the list.
std::unique_ptr< Nullable< A > > removeAt (unsigned ind) override
Removes the value associated with the given index, if any, and returns it.
std::unique_ptr< Nullable< A > > removeIf (std::function< bool(const A &)> predicate)
Remove the first element of the list that matches the given predicate, and return it.
std::unique_ptr< Nullable< A > > shift () override
Removes the first element of the list, if any, and returns it.
template<int sliceSize> std::unique_ptr< ArrayList< typename Tuple< A >::template ofSize< sliceSize >::type > > slice ()
Slices the array in parts of the provided size.
std::unique_ptr< ArrayList< A > > sort (std::function< bool(const A &, const A &)> comparator) const
Returns a new ArrayList containing the elements of this list sorted with the QuickSort algorithm by the provided comparison function.
template<typename B > std::unique_ptr< ArrayList< Tuple< A, B > > > zip (ArrayList< B > const &list) const
Return a list of pairs where each pair is composed of the elements of the two lists with the same index.
~ArrayList ()
Static Public Member Functions
static unsigned getDefaultReservedSpace ()
Protected Attributes
unsigned elemCount
A ** elems = nullptr
unsigned reserved
Private Member Functions
void copy (ArrayList< A > const &other)
Copies another list into this one.
void create (unsigned reserve)
Initializes the list with the given size.
void free ()
Frees the resizable array.
Static Private Member Functions
template<typename B > static unsigned partition (std::unique_ptr< ArrayList< B >> const &array, unsigned from, unsigned to, std::function< bool(const B &, const B &)> comparator)
The partition function of the quicksort algorithm.
template<typename B > static void quickSort (std::unique_ptr< ArrayList< B >> const &array, unsigned from, unsigned to, std::function< bool(const B &, const B &)> comparator)
An implementation of the quicksort algorithm that allows for the use of an arbitrary comparison function.
Static Private Attributes
static const unsigned DEFAULT_RESERVED_SPACE = 4
Detailed Description
template<class A>
class ArrayList< A >"
An implementation of a list backed by a resizable array.
Due to some quirks of the implementation, type A must implement operator==.
Definition at line 22 of file ArrayList.hpp.
Constructor & Destructor Documentation
template<class A > ArrayList< A >::ArrayList () [inline]
Definition at line 117 of file ArrayList.hpp.
{ create(getDefaultReservedSpace()); }
template<class A > ArrayList< A >::ArrayList (unsigned reserved) [inline], [explicit]
Preallocate memory for the given amount of elements.
Definition at line 141 of file ArrayList.hpp.
{ create(reserved); }
template<class A > ArrayList< A >::ArrayList (ArrayList< A > const & other) [inline]
Definition at line 143 of file ArrayList.hpp.
                                       {
    if (&other != this)
      copy(other);
  }
template<class A > ArrayList< A >::~ArrayList () [inline]
Definition at line 154 of file ArrayList.hpp.
{ free(); }
Member Function Documentation
template<class A > void ArrayList< A >::append (A && elem) [inline], [override], [virtual]
Appends the given element to the list.
Parameters
elem the element
Implements IList< A >.
Definition at line 234 of file ArrayList.hpp.
{ insert(std::move(elem), length()); }
template<class A > void ArrayList< A >::append (A const & elem) [inline], [override], [virtual]
Appends the given element to the list.
Parameters
elem the element
Implements IList< A >.
Definition at line 232 of file ArrayList.hpp.
{ insert(elem, length()); }
Referenced by User::addFriend(), ArrayList< char * >::appendAll(), ArrayList< char * >::fill(), Travel::VisitBuilder::photoAdd(), and Stack< A >::push().
template<class A > void ArrayList< A >::appendAll (ArrayList< A > const & l) [inline]
Append all elements of the given list to this one.
Parameters
l the list to append
Definition at line 134 of file ArrayList.hpp.
                                        {
    for (int i = 0; i < l.length(); i++) {
      append(l.get(i));
    }
  }
Referenced by ArrayList< char * >::copy().
template<class A > unsigned ArrayList< A >::capacity () const [inline]
return the current maximum capacity of the array
Definition at line 299 of file ArrayList.hpp.
{ return reserved; }
Referenced by Stack< A >::asList(), ArrayList< char * >::copy(), ArrayList< char * >::expand(), ArrayList< char * >::fill(), ArrayList< char * >::insert(), ArrayList< char * >::map(), ArrayList< char * >::sort(), and ArrayList< char * >::zip().
template<class A > void ArrayList< A >::clear () [inline], [override], [virtual]
Clears the list.
Implements IList< A >.
Definition at line 301 of file ArrayList.hpp.
                        {
    free();
    create(getDefaultReservedSpace());
  }
Referenced by Travel::VisitBuilder::clear().
template<class A > bool ArrayList< A >::contains (A const & elem) const [inline], [override], [virtual]
Returns true if the given element is contained in the list.
Parameters
elem the element to search for
Returns
if the element is contained
Implements IList< A >.
Definition at line 240 of file ArrayList.hpp.
                                              {
    for (int i = 0; i < length(); i++) {
      if (get(i) == elem)
        return true;
    }
    return false;
  }
Referenced by ArrayList< char * >::difference(), ArrayList< char * >::intersection(), and ArrayList< char * >::operator==().
template<class A > void ArrayList< A >::copy (ArrayList< A > const & other) [inline], [private]
Copies another list into this one.
Parameters
other the other list.
Definition at line 55 of file ArrayList.hpp.
                                       {
    // LOG(INFO, "Copying ArrayList");
    free();
    elems = new A *[other.capacity()];
    reserved = other.capacity();
    elemCount = 0;
    appendAll(other);
  }
Referenced by ArrayList< char * >::ArrayList(), and ArrayList< char * >::operator=().
template<class A > void ArrayList< A >::create (unsigned reserve) [inline], [private]
Initializes the list with the given size.
Parameters
reserve the starting size to allocate for the resizable array
Definition at line 44 of file ArrayList.hpp.
                                {
    // LOG(INFO, "Creating ArrayList");
    elems = new A *[reserve];
    reserved = reserve;
    elemCount = 0;
  }
Referenced by ArrayList< char * >::ArrayList(), and ArrayList< char * >::clear().
template<class A > std::unique_ptr<ArrayList<A> > ArrayList< A >::difference (ArrayList< A > const & list) const [inline]
Returns the set difference of this list and the provided one.
Parameters
list the other list
Returns
the set difference of the two lists
Definition at line 486 of file ArrayList.hpp.
                                                                         {
    std::unique_ptr<ArrayList<A>> res = std::make_unique<ArrayList<A>>();
    if (length() >= list.length()) {
      for (int i = 0; i < length(); i++) {
        if (!list.contains(get(i)))
          res->append(get(i));
      }
      for (int i = 0; i < list.length(); i++) {
        if (!contains(list.get(i)) && !res->contains(list.get(i)))
          res->append(list.get(i));
      }
      return res;
    } else {
      return list.difference(*this);
    }
  }
Referenced by ArrayList< char * >::difference().
template<class A > std::unique_ptr<ArrayList<A> > ArrayList< A >::distinct () const [inline]
Construct a new list using the elements of this one but ensuring that the elements of the new list are distinct. i.e comparing any two elements of the newly constructed list via operator== results in false.
Returns
the list of distinct elements
Definition at line 329 of file ArrayList.hpp.
                                               {
    std::unique_ptr<ArrayList<A>> filtered = std::make_unique<ArrayList<A>>();
    for (int i = 0; i < length(); i++) {
      if (!filtered->contains(get(i))) {
        filtered->append(get(i));
      }
    }
    return filtered;
  }
template<class A > void ArrayList< A >::expand () [inline]
Double the capacity of the array.
Definition at line 207 of file ArrayList.hpp.
                {
    // LOG(VERBOSE, "Expanding array");
    unsigned newCapacity = capacity() * 2;
    reserved = newCapacity;
    A **newRooms = new A *[newCapacity];
    for (int i = 0; i < length(); i++) {
      newRooms[i] = new A(get(i));
    }
    free();
    elems = newRooms;
  }
Referenced by ArrayList< char * >::insert().
template<class A > void ArrayList< A >::fill () [inline]
Fill the array with elements created with the default constructor.
Definition at line 223 of file ArrayList.hpp.
{ fill(A{}); }
Referenced by ArrayList< char * >::fill().
template<class A > void ArrayList< A >::fill (A const & elem) [inline]
Fill the entire array with the given element.
Definition at line 226 of file ArrayList.hpp.
                           {
    for (int i = 0; i < capacity(); i++) {
      append(elem);
    }
  }
template<class A > std::unique_ptr<ArrayList<A> > ArrayList< A >::filter (std::function< bool(const A &)> predicate) const [inline]
Return a new ArrayList containing all elements in the current list that match the provided predicate.
Parameters
predicate the condition that elements need to satisfy
Returns
the filtered list
Definition at line 313 of file ArrayList.hpp.
                                                       {
    std::unique_ptr<ArrayList<A>> filtered = std::make_unique<ArrayList<A>>();
    for (int i = 0; i < length(); i++) {
      if (predicate(get(i))) {
        filtered->append(get(i));
      }
    }
    return filtered;
  }
template<class A > int ArrayList< A >::find (std::function< bool(const A &)> predicate) const [inline]
Definition at line 354 of file ArrayList.hpp.
                                                         {
    for (int i = 0; i < length(); i++) {
      if (predicate(get(i))) {
        return i;
      }
    }
    return -1;
  }
Referenced by User::addFriend(), and User::hasFriend().
template<class A > template<typename B , typename = std::enable_if_t<std::is_base_of<IList<B>, A>::value>> std::unique_ptr<ArrayList<B> > ArrayList< A >::flatten () [inline]
Convert a list of lists into a single list containing all elements of the previously contained lists.
Definition at line 455 of file ArrayList.hpp.
                                        {
    std::unique_ptr<ArrayList<B>> res = std::make_unique<ArrayList<B>>();
    for (int i = 0; i < length(); i++) {
      res->appendAll(get(i));
    }
    return res;
  }
template<class A > A ArrayList< A >::fold (A start, std::function< A(const A &, const A &)> biconsumer) [inline]
Return the result of applying the provided function to the result of the previous application or the provided starting value and the next element in the list until all the elements of the list have been consumed.
Parameters
start the starting value
biconsumer the function to apply
Returns
the result of the application
Definition at line 425 of file ArrayList.hpp.
                                                                   {
    for (int i = 0; i < length(); i++) {
      start = biconsumer(start, get(i));
    }
    return start;
  }
template<class A > void ArrayList< A >::foreach (std::function< void(const A &)> consumer) const [inline]
Applies the provided function to each element of the list in order.
Parameters
consumer the function to apply
Definition at line 367 of file ArrayList.hpp.
                                                             {
    for (int i = 0; i < length(); i++) {
      if (elems[i])
        consumer(get(i));
    }
  }
Referenced by User::listFriends(), operator<<(), and Travel::VisitBuilder::photoShow().
template<class A > void ArrayList< A >::free () [inline], [private]
Frees the resizable array.
Definition at line 29 of file ArrayList.hpp.
              {
    // LOG(INFO, "Freeing ArrayList.");
    if (!elems)
      return;
    for (unsigned i = 0; i < elemCount; i++) {
      if (elems[i])
        delete elems[i];
    }
    delete[] elems;
  }
Referenced by ArrayList< char * >::clear(), ArrayList< char * >::copy(), ArrayList< char * >::expand(), and ArrayList< char * >::~ArrayList().
template<class A > A& ArrayList< A >::get (unsigned index) const [inline], [override], [virtual]
Returns the value at the index.
Parameters
index the index
Returns
the value
Implements IList< A >.
Definition at line 290 of file ArrayList.hpp.
                                        {
    if (index >= length())
      return *elems[length() - 1];
    return *elems[index];
  }
Referenced by ArrayList< char * >::appendAll(), ArrayList< char * >::contains(), ArrayList< char * >::difference(), ArrayList< char * >::distinct(), ArrayList< char * >::expand(), ArrayList< char * >::filter(), ArrayList< char * >::find(), ArrayList< char * >::flatten(), ArrayList< char * >::fold(), ArrayList< char * >::foreach(), ArraySet< A >::insert(), ArrayList< char * >::intersection(), ArrayList< char * >::map(), ArrayList< char * >::operator==(), ArrayList< char * >::prependAll(), Stack< A >::pushAll(), ArrayList< char * >::remove(), ArrayList< char * >::removeIf(), ArrayList< char * >::zip(), and User::~User().
template<class A > static unsigned ArrayList< A >::getDefaultReservedSpace () [inline], [static]
Definition at line 534 of file ArrayList.hpp.
{ return DEFAULT_RESERVED_SPACE; };
Referenced by ArrayList< char * >::ArrayList(), and ArrayList< char * >::clear().
template<class A > void ArrayList< A >::insert (A && elem, unsigned at) [inline], [override], [virtual]
Inserts the given element in the list at the specified position.
Parameters
elem the element
at the position
Implements IList< A >.
Definition at line 180 of file ArrayList.hpp.
                                              {
    if (elemCount + 1 > capacity()) {
      expand(); // Expand the list if inserting one more element would
                // exceed the dynamic array's current capacity
    }
    if (at >= length()) { // Assume that indexes greater or equal to the
      // list's length mean an insertion at the end of
      // the list.
      elems[elemCount] = new A(std::move(elem));
      elemCount++;
      return;
    }
    for (int i = length(); i > at; i--) {
      elems[i] = elems[i - 1]; // Shift all elements from index at to
                               // length() left by one to make space for
                               // the new element
    }
    *elems[at] = std::move(elem);
    elemCount++;
  }
template<class A > void ArrayList< A >::insert (A const & elem, unsigned at) [inline], [override], [virtual]
Inserts the given element in the list at the specified position.
Parameters
elem the element
at the position
Implements IList< A >.
Reimplemented in ArraySet< A >.
Definition at line 156 of file ArrayList.hpp.
                                                   {
    if (elemCount + 1 > capacity()) {
      expand(); // Expand the list if inserting one more element would
                // exceed the dynamic array's current capacity
    }
    if (at >= length()) { // Assume that indexes greater or equal to the
      // list's length mean an insertion at the end of
      // the list.
      elems[elemCount] = new A(elem);
      elemCount++;
      return;
    }
    for (int i = length(); i > at; i--) {
      elems[i] = elems[i - 1]; // Shift all elements from index at to
                               // length() left by one to make space for
                               // the new element
    }
    *elems[at] = elem;
    elemCount++;
  }
Referenced by ArrayList< char * >::append(), ArraySet< A >::insert(), and ArrayList< char * >::prepend().
template<class A > std::unique_ptr<ArrayList<A> > ArrayList< A >::intersection (ArrayList< A > const & list) const [inline]
Returns the set intersection of this list and the provided one.
Parameters
list the other list
Returns
the set intersection of the two lists
Definition at line 468 of file ArrayList.hpp.
                                                                           {
    std::unique_ptr<ArrayList<A>> res = std::make_unique<ArrayList<A>>();
    if (length() >= list.length()) {
      for (int i = 0; i < length(); i++) {
        if (list.contains(get(i)))
          res->append(get(i));
      }
      return res;
    } else {
      return list.intersection(*this);
    }
  }
Referenced by ArrayList< char * >::intersection().
template<class A > unsigned ArrayList< A >::length () const [inline], [final], [virtual]
return the amount of elements currently in the array
Implements IList< A >.
Definition at line 297 of file ArrayList.hpp.
{ return elemCount; }
Referenced by ArrayList< char * >::append(), ArrayList< char * >::appendAll(), Stack< A >::asList(), ArrayList< char * >::contains(), ArrayList< char * >::difference(), ArrayList< char * >::distinct(), ArrayList< char * >::expand(), ArrayList< char * >::filter(), ArrayList< char * >::find(), ArrayList< char * >::flatten(), ArrayList< char * >::fold(), ArrayList< char * >::foreach(), ArrayList< char * >::get(), ArraySet< A >::insert(), ArrayList< char * >::insert(), ArrayList< char * >::intersection(), ArrayList< char * >::map(), ArrayList< char * >::operator==(), Stack< A >::peek(), ArrayList< char * >::pop(), ArrayList< char * >::prependAll(), Stack< A >::pushAll(), ArrayList< char * >::remove(), ArrayList< char * >::removeAt(), ArrayList< char * >::removeIf(), ArrayList< char * >::slice(), ArrayList< char * >::sort(), ArrayList< char * >::zip(), and User::~User().
template<class A > template<typename B > std::unique_ptr<ArrayList<B> > ArrayList< A >::map (std::function< B(const A &)> mapper) const [inline]
Return a new ArrayList containing the result of applying the provided mapping function to each element of the list in order.
Template Parameters
B the type of elements in the new list
Parameters
mapper the mapping function
Returns
the new ArrayList
Definition at line 408 of file ArrayList.hpp.
                                                                          {
    std::unique_ptr<ArrayList<B>> mapped =
        std::make_unique<ArrayList<B>>(capacity());
    for (int i = 0; i < length(); i++) {
      mapped->append(mapper(get(i)));
    }
    return mapped;
  }
template<class A > ArrayList<A>& ArrayList< A >::operator= (ArrayList< A > const & other) [inline]
Definition at line 148 of file ArrayList.hpp.
                                                     {
    if (&other != this)
      copy(other);
    return *this;
  }
template<class A > bool ArrayList< A >::operator== (ArrayList< A > const & other) [inline]
Definition at line 524 of file ArrayList.hpp.
                                             {
    if (length() != other.length())
      return false;
    for (int i = 0; i < length(); i++) {
      if (!other.contains(get(i)) || !contains(other.get(i)))
        return false;
    }
    return true;
  }
template<class A > template<typename B > static unsigned ArrayList< A >::partition (std::unique_ptr< ArrayList< B >> const & array, unsigned from, unsigned to, std::function< bool(const B &, const B &)> comparator) [inline], [static], [private]
The partition function of the quicksort algorithm.
Template Parameters
B the type of the elements in the list
Parameters
array the list to sort
from the start of the range to partition in
to the end of the range to partition in
comparator the function with which to compare elements
Returns
the pivot
Definition at line 75 of file ArrayList.hpp.
                                                          {
    B pivot = array->get(to);
    unsigned i = from;
    for (unsigned j = from; j <= to; j++) {
      if (comparator(array->get(j), pivot)) {
        swap(array->elems[j], array->elems[i]);
        i++;
      }
    }
    swap(array->elems[i], array->elems[to]);
    return i;
  }
template<class A > std::unique_ptr<Nullable<A> > ArrayList< A >::pop () [inline], [override], [virtual]
Removes the last element of the list, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the list is empty or an instance of NotNull wrapped around the value.
Returns
the value, if any
Implements IList< A >.
Definition at line 286 of file ArrayList.hpp.
{ return removeAt(length() - 1); }
template<class A > void ArrayList< A >::prepend (A && elem) [inline], [override], [virtual]
Prepends the given element to the list.
Parameters
elem the element
Implements IList< A >.
Definition at line 238 of file ArrayList.hpp.
{ insert(std::move(elem), 0); }
template<class A > void ArrayList< A >::prepend (A const & elem) [inline], [override], [virtual]
Prepends the given element to the list.
Parameters
elem the element
Implements IList< A >.
Definition at line 236 of file ArrayList.hpp.
{ insert(elem, 0); }
Referenced by ArrayList< char * >::prependAll().
template<class A > void ArrayList< A >::prependAll (ArrayList< A > const & l) [inline]
Prepend all elements of the given list to this one. Very slow for large lists.
Parameters
l the list to prepend
Definition at line 124 of file ArrayList.hpp.
                                         {
    for (int i = 0; i < l.length(); i++) {
      prepend(l.get(i));
    }
  }
template<class A > template<typename B > static void ArrayList< A >::quickSort (std::unique_ptr< ArrayList< B >> const & array, unsigned from, unsigned to, std::function< bool(const B &, const B &)> comparator) [inline], [static], [private]
An implementation of the quicksort algorithm that allows for the use of an arbitrary comparison function.
Template Parameters
B the type of the elements in the list
Parameters
array the list to sort
from the start of the range to sort in
to the end of the range to sort in
comparator the function with which to compare elements
Definition at line 100 of file ArrayList.hpp.
                                                                            {
    if (from <= to) {
      unsigned part = partition<B>(array, from, to, comparator);
      if (part != 0)
        quickSort<B>(array, from, part - 1, comparator);
      quickSort<B>(array, part + 1, to, comparator);
    }
  }
template<class A > int ArrayList< A >::remove (const A & elem) [inline], [override], [virtual]
Remove the first occurence of the given element in the list. All following elements are brought back by one index in order to fill the hole left by the removal
Parameters
elem the element to remove
Returns
the index of the removed element
Implements IList< A >.
Definition at line 248 of file ArrayList.hpp.
                                     {
    int foundAt = -1;
    unsigned index = 0;
    for (unsigned i = 0; i < length(); i++) {
      if (get(i) == elem) {
        delete elems[i];
        foundAt = i;
        continue;
      }
      if (index != i) {
        elems[index] = elems[i];
      }
      index++;
    }
    if (foundAt != -1)
      elemCount--;
    return foundAt;
  }
Referenced by Travel::VisitBuilder::photoDelete().
template<class A > std::unique_ptr<Nullable<A> > ArrayList< A >::removeAt (unsigned ind) [inline], [override], [virtual]
Removes the value associated with the given index, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the index doesn't exist or an instance of NotNull wrapped around the value.
All following elements are moved back by one index to fill the hole left by the removal
Parameters
index the index, whose value to remove
Returns
the value, if any
Implements IList< A >.
Definition at line 268 of file ArrayList.hpp.
                                                             {
    if (length() == 0)
      return std::make_unique<Null<A>>(); // No element to remove
    // so just return null
    A ret =
        *elems[ind >= length() ? length() - 1
                               : ind]; // Save the element that will be removed
    delete elems[ind >= length() ? length() - 1 : ind];
    if (ind < length() - 1) {
      for (unsigned i = ind; i < length() - 1; i++) {
        elems[i] = elems[i + 1];
      }
    }
    elemCount--;
    return std::make_unique<NotNull<A>>(ret);
  }
Referenced by ArrayList< char * >::pop(), ArrayList< char * >::removeIf(), and ArrayList< char * >::shift().
template<class A > std::unique_ptr<Nullable<A> > ArrayList< A >::removeIf (std::function< bool(const A &)> predicate) [inline]
Remove the first element of the list that matches the given predicate, and return it. If no such element exists return Null instead.
Parameters
predicate the condition for removal
Returns
the removed element or null
Definition at line 345 of file ArrayList.hpp.
                                                                                {
    for (int i = 0; i < length(); i++) {
      if (predicate(get(i))) {
        return removeAt(i);
      }
    }
    return std::make_unique<Null<A>>();
  }
Referenced by User::removeFriend().
template<class A > std::unique_ptr<Nullable<A> > ArrayList< A >::shift () [inline], [override], [virtual]
Removes the first element of the list, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the list is empty or an instance of NotNull wrapped around the value.
All following elements are moved back by one index to fill the hole left by the removal
Returns
the value, if any
Implements IList< A >.
Definition at line 288 of file ArrayList.hpp.
{ return removeAt(0); }
template<class A > template<int sliceSize> std::unique_ptr<ArrayList<typename Tuple<A>::template ofSize<sliceSize>::type> > ArrayList< A >::slice () [inline]
Slices the array in parts of the provided size. Those slices are stored in a tuple and an array list of all the resulting tuples is returned.
Definition at line 382 of file ArrayList.hpp.
          {
    if (length() % sliceSize != 0)
      throw InvalidArgumentException("List size must be evenly divisible"
                                     " by slice size");
    int slices = length() / sliceSize;
    auto list = std::make_unique<
        ArrayList<typename Tuple<A>::template ofSize<sliceSize>::type>>(slices);
    for (int i = 1; i < slices; i++) {
      typename Tuple<A>::template ofSize<sliceSize>::type tuple(elems +
                                                                sliceSize * i);
      list->append(tuple);
    }
    return list;
  }
template<class A > std::unique_ptr<ArrayList<A> > ArrayList< A >::sort (std::function< bool(const A &, const A &)> comparator) const [inline]
Returns a new ArrayList containing the elements of this list sorted with the QuickSort algorithm by the provided comparison function.
Parameters
comparator the comparison function
Returns
the sorted list
Definition at line 440 of file ArrayList.hpp.
                                                                 {
    std::unique_ptr<ArrayList<A>> sorted =
        std::make_unique<ArrayList<A>>(capacity());
    if (length() == 0)
      return sorted;
    sorted->appendAll(*this);
    quickSort<A>(sorted, 0, sorted->length() - 1, comparator);
    return sorted;
  }
template<class A > template<typename B > std::unique_ptr<ArrayList<Tuple<A, B> > > ArrayList< A >::zip (ArrayList< B > const & list) const [inline]
Return a list of pairs where each pair is composed of the elements of the two lists with the same index. The lists must have the same amount of elements
Definition at line 509 of file ArrayList.hpp.
                                                                            {
    using Pair = Tuple<A, B>;
    if (list.length() != length())
      throw NoValueException("Calling zip on ArrayLists with different"
                             "amount of elements)");
    auto res = std::make_unique<ArrayList<Pair>>(capacity());
    for (unsigned i = 0; i < length(); i++) {
      A a = this->get(i);
      B b = list.get(i);
      res->append(Pair(a, b));
    }
    return res;
  }
Member Data Documentation
template<class A > const unsigned ArrayList< A >::DEFAULT_RESERVED_SPACE = 4 [static], [private]
Definition at line 24 of file ArrayList.hpp.
Referenced by ArrayList< char * >::getDefaultReservedSpace().
template<class A > unsigned ArrayList< A >::elemCount [protected]
Definition at line 114 of file ArrayList.hpp.
Referenced by ArrayList< char * >::copy(), ArrayList< char * >::create(), ArrayList< char * >::free(), ArrayList< char * >::insert(), ArrayList< char * >::length(), ArrayList< char * >::remove(), and ArrayList< char * >::removeAt().
template<class A > A** ArrayList< A >::elems = nullptr [protected]
Definition at line 112 of file ArrayList.hpp.
Referenced by ArrayList< char * >::copy(), ArrayList< char * >::create(), ArrayList< char * >::expand(), ArrayList< char * >::foreach(), ArrayList< char * >::free(), ArrayList< char * >::get(), ArrayList< char * >::insert(), ArrayList< char * >::remove(), ArrayList< char * >::removeAt(), and ArrayList< char * >::slice().
template<class A > unsigned ArrayList< A >::reserved [protected]
Definition at line 113 of file ArrayList.hpp.
Referenced by ArrayList< char * >::ArrayList(), ArrayList< char * >::capacity(), ArrayList< char * >::copy(), ArrayList< char * >::create(), and ArrayList< char * >::expand().
Author
Generated automatically by Doxygen for Traveller's App from the source code.