ArraySet< A >
NAME
ArraySet< A > - Literally an ArrayList but when adding items it checks if the element is already in the list.
SYNOPSIS
#include <ArraySet.hpp>
Inherits ArrayList< A >.
Public Member Functions
ArraySet ()
ArraySet (ArraySet< A > const &set)
ArraySet (int capacity)
void insert (A const &elem, unsigned at) override
Inserts the given element in the list at the specified position.
Additional Inherited Members
Detailed Description
template<class A>
class ArraySet< A >"
Literally an ArrayList but when adding items it checks if the element is already in the list.
Definition at line 14 of file ArraySet.hpp.
Constructor & Destructor Documentation
template<class A > ArraySet< A >::ArraySet (ArraySet< A > const & set) [inline]
Definition at line 16 of file ArraySet.hpp.
: ArrayList<A>(set) {}
template<class A > ArraySet< A >::ArraySet (int capacity) [inline]
Definition at line 18 of file ArraySet.hpp.
: ArrayList<A>(capacity) {}
template<class A > ArraySet< A >::ArraySet () [inline]
Definition at line 20 of file ArraySet.hpp.
: ArrayList<A>() {}
Member Function Documentation
template<class A > void ArraySet< A >::insert (A const & elem, unsigned at) [inline], [override], [virtual]
Inserts the given element in the list at the specified position.
Parameters
elem the element
at the position
Reimplemented from ArrayList< A >.
Definition at line 22 of file ArraySet.hpp.
                                                   {
    if (at < 0)
      return;
    for (unsigned i = 0; i < this->length(); i++) {
      if (this->get(i) == elem) {
        return;
      }
    }
    ArrayList<A>::insert(elem, at);
  }
References ArrayList< A >::get(), ArrayList< A >::insert(), and ArrayList< A >::length().
Author
Generated automatically by Doxygen for Traveller's App from the source code.