.TH "TravellersApp/src/collection/BinaryNode.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/collection/BinaryNode.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'ArrayList\&.hpp'\fP
.br
\fC#include 'Stack\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBinaryNode< B, A >\fP"
.br
.RI "A node for use in a binary tree\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
