CSV< Types >
NAME
CSV< Types > - An ill-conceived attempt to create a csv file.
SYNOPSIS
#include <CSV.hpp>
Public Member Functions
void addEntry (Types &... data)
Add an entry. This will make sure at compile-time that the amount of elements provided matches the amount of columns in the file.
CSV ()=delete
It is necessary to provide the names of the header manually. This may change in the future.
CSV (CSVHeader const &header)
Construct a new csv file with the provided column header.
template<typename... Ts> CSV (Ts... ts)
Allow the passing of a column-amount of const char* instead of a tuple for the construction of the header.
auto getByColumnHeader (const char *s)
Return the column with the given header I am not entirely sure this works. It did when I was testing while writing it but...
template<int ind> auto getColumn () -> std::unique_ptr< ArrayList< typename Entry::template typeOf< ind >::type >>
Returns the specified column.
auto getKeys () -> std::unique_ptr< ArrayList< typename Entry::template typeOf< 0 >::type >>
Returns the first column of the file.
Tuple< Types... > & getRow (unsigned ind)
Returns a reference to the row at the given index.
CSVHeader header ()
Return the header of this file.
void load (const char *filepath)
Load the entries from the CSV file located at the given path The number of columns in the file must match the number of columns of this class.
void save (const char *filepath)
Save the contents of the file into the file pointed to by the provided path.
unsigned size ()
Returns the amount of entries in the file.
~CSV ()
Private Types
using CSVHeader = typename Tuple< const char * >::ofSize< columns >::type
The type of the header - A Tuple with as many const char* provided as type arguments as there are columns.
using Entry = Tuple< Types... >
Private Attributes
CSVHeader _header
ArrayList< Entry > entries
Static Private Attributes
static constexpr int columns = sizeof...(Types)
The number of columns.
Detailed Description
template<typename... Types>
class CSV< Types >"
An ill-conceived attempt to create a csv file.
It's closer to a SSV (Space Separated Values) to a CSV since no commas are actually used in the files. The element in the first column is considered a key and must be unique. It can store an arbitrary number of arbitrary types... theoretically It doesn't actually work with anything that isn't a char* or a class that supports implicit conversion from char* (Such as SimpleString). It does an adequate job for the types it does work for. And it does make sure at compile-time that the exact amount of entries required are used.
Bug
It ignores the actual header names inside the file. It just cares about their count.
Definition at line 25 of file CSV.hpp.
Member Typedef Documentation
template<typename... Types> using CSV< Types >::CSVHeader = typename Tuple<const char *>::ofSize<columns>::type [private]
The type of the header - A Tuple with as many const char* provided as type arguments as there are columns.
Definition at line 32 of file CSV.hpp.
template<typename... Types> using CSV< Types >::Entry = Tuple<Types...> [private]
Definition at line 34 of file CSV.hpp.
Constructor & Destructor Documentation
template<typename... Types> CSV< Types >::CSV () [delete]
It is necessary to provide the names of the header manually. This may change in the future.
template<typename... Types> CSV< Types >::CSV (CSVHeader const & header) [inline]
Construct a new csv file with the provided column header.
Definition at line 43 of file CSV.hpp.
: _header(header){};
template<typename... Types> template<typename... Ts> CSV< Types >::CSV (Ts... ts) [inline]
Allow the passing of a column-amount of const char* instead of a tuple for the construction of the header.
Definition at line 47 of file CSV.hpp.
: _header(CSVHeader(ts...)) {}
template<typename... Types> CSV< Types >::~CSV () [inline]
Definition at line 165 of file CSV.hpp.
         {
    for (int i = 0; i < entries.length(); i++) {
      entries.get(i).free();
    }
  }
Member Function Documentation
template<typename... Types> void CSV< Types >::addEntry (Types &... data) [inline]
Add an entry. This will make sure at compile-time that the amount of elements provided matches the amount of columns in the file.
Definition at line 142 of file CSV.hpp.
{ entries.append({data...}); }
Referenced by User::~User().
template<typename... Types> auto CSV< Types >::getByColumnHeader (const char * s) [inline]
Return the column with the given header I am not entirely sure this works. It did when I was testing while writing it but...
Definition at line 174 of file CSV.hpp.
                                        {
    int ind = header().template indexOf<const char *>(s);
    if (entries.length() == 0) {
      throw NoValueException("CSV contains no entries");
    }
    auto t = *entries.get(0).template at<decltype(s)>(ind);
    return entries.template map<decltype(t)>(
        [ind](const Entry &e) { return *e.template at<decltype(s)>(ind); });
  }
template<typename... Types> template<int ind> auto CSV< Types >::getColumn () -> std::unique_ptr<ArrayList<typename Entry::template typeOf<ind>::type>> [inline]
Returns the specified column.
Template Parameters
ind the column to return.
Definition at line 159 of file CSV.hpp.
                                                                          {
    return entries.template map<typename Entry::template typeOf<ind>::type>(
        [](Entry const &t) { return *t.template get<ind>(); });
  }
template<typename... Types> auto CSV< Types >::getKeys () -> std::unique_ptr<ArrayList<typename Entry::template typeOf<0>::type>> [inline]
Returns the first column of the file.
Definition at line 151 of file CSV.hpp.
                                                                        {
    return getColumn<0>();
  }
Referenced by CSV< const char *, const char *, const char * >::load(), Travel::TravelState::login(), Travel::TravelState::TravelState(), and User::User().
template<typename... Types> Tuple<Types...>& CSV< Types >::getRow (unsigned ind) [inline]
Returns a reference to the row at the given index.
Definition at line 145 of file CSV.hpp.
{ return entries.get(ind); }
Referenced by Travel::TravelState::login().
template<typename... Types> CSVHeader CSV< Types >::header () [inline]
Return the header of this file.
Definition at line 138 of file CSV.hpp.
{ return _header; }
Referenced by CSV< const char *, const char *, const char * >::getByColumnHeader(), and CSV< const char *, const char *, const char * >::save().
template<typename... Types> void CSV< Types >::load (const char * filepath) [inline]
Load the entries from the CSV file located at the given path The number of columns in the file must match the number of columns of this class.
Bug
Ignores the header.
This doesn't really work as advertised. It doesn't check if each row contains the exact amount of columns as this class. Rather it checks that the total number of separate entries (including the header) is evenly divisible by the amount of columns. EXAMPLE: Assuming that this class expects a file like this
header1 * header2 * header3 * entry1 * entry2 * entry3 *
A file formatted like so:
header1 * header2 * header3 * header4 * entry11 * entry12 * entry13 * entry14 * entry21 * entry22 * entry23 * entry24 *
Will be considered valid, and will be loaded like so
header1 * header2 * header3 * header4 * entry11 * entry12 * entry13 * entry14 * entry21 * entry22 * entry23 * entry24 *
Definition at line 76 of file CSV.hpp.
                                  {
      std::ifstream file(filepath);
    if (file.is_open()) {
      Travel::CommandList cl;
      Travel::Scanner scanner(ScannerContext::ALL, &file, &cl);
      auto tokens =
          scanner.scan()
              ->filter([](Token const &t) { return t.t != TokenType::EOF_T; })
              ->template map<typename Entry::template typeOf<0>::type>(
                  [](Token const &t) {
                    char *s = t.lexeme;
                    char *d = new char[strlen(s) + 1];
                    strcpy(d, s);
                    return d;
                  });
      if (tokens->length() < columns) {
        std::cerr << filepath << " is empty" << std::endl;
        file.close();
        return;
      }
      for (int i = 0; i < columns; i++) {
        delete[] tokens->get(i);
      }
      std::unique_ptr<ArrayList<Tuple<Types...>>> readEntries =
          tokens->template slice<columns>();
      for (int i = 0; i < readEntries->length(); i++) {
        auto k = getKeys();
        if (k->find([&readEntries, i](const char *const(&entry)) {
              return strcmp(readEntries->get(i).head(), entry) == 0;
            }) >= 0) {
          std::cerr << "Key " << readEntries->get(i).head()
                    << " already exists. Skipping" << std::endl;
          readEntries->get(i).free();
          continue;
        }
        entries.append(readEntries->get(i));
      }
    } else {
      std::cerr << "Cannot open " << filepath << " for read." << std::endl;
    }
    file.close();
  }
Referenced by Travel::TravelState::TravelState(), and User::User().
template<typename... Types> void CSV< Types >::save (const char * filepath) [inline]
Save the contents of the file into the file pointed to by the provided path. The file is formatted properly so that it can later be read by this class' load function
Definition at line 124 of file CSV.hpp.
                                  {
      std::ofstream file(filepath);
    if (file.is_open()) {
      file << header() << std::endl;
      for (int i = 0; i < size(); i++) {
        file << entries.get(i) << std::endl;
      }
    } else {
      std::cerr << "Cannot open " << filepath << " for write." << std::endl;
    }
    file.close();
  }
Referenced by Travel::TravelState::~TravelState(), and User::~User().
template<typename... Types> unsigned CSV< Types >::size () [inline]
Returns the amount of entries in the file.
Definition at line 148 of file CSV.hpp.
{ return entries.length(); }
Referenced by CSV< const char *, const char *, const char * >::save(), and Travel::TravelState::TravelState().
Member Data Documentation
template<typename... Types> CSVHeader CSV< Types >::_header [private]
Definition at line 33 of file CSV.hpp.
Referenced by CSV< const char *, const char *, const char * >::header().
template<typename... Types> constexpr int CSV< Types >::columns = sizeof...(Types) [static], [constexpr], [private]
The number of columns.
Definition at line 28 of file CSV.hpp.
Referenced by CSV< const char *, const char *, const char * >::load().
template<typename... Types> ArrayList<Entry> CSV< Types >::entries [private]
Definition at line 35 of file CSV.hpp.
Referenced by CSV< const char *, const char *, const char * >::addEntry(), CSV< const char *, const char *, const char * >::getByColumnHeader(), CSV< const char *, const char *, const char * >::getColumn(), CSV< const char *, const char *, const char * >::getRow(), CSV< const char *, const char *, const char * >::load(), CSV< const char *, const char *, const char * >::save(), CSV< const char *, const char *, const char * >::size(), and CSV< const char *, const char *, const char * >::~CSV().
Author
Generated automatically by Doxygen for Traveller's App from the source code.