.TH "TravellersApp/src/parser/CSV.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/parser/CSV.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./SimpleString\&.hpp'\fP
.br
\fC#include '\&.\&./collection/ArrayList\&.hpp'\fP
.br
\fC#include '\&.\&./collection/Tuple\&.hpp'\fP
.br
\fC#include '\&.\&./ttype\&.hpp'\fP
.br
\fC#include 'Scanner\&.hpp'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCSV< Types >\fP"
.br
.RI "An ill-conceived attempt to create a csv file\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
