.TH "TravellersApp/src/Date.cpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/Date.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Date\&.hpp'\fP
.br
\fC#include 'InvalidArgumentException\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <ctime>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTravel\fP"
.br
.RI "Collects all code that is not necessarily easily reusable\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBTravel::isDash\fP (std::istream &in)"
.br
.ti -1c
.RI "std::ostream & \fBTravel::operator<<\fP (std::ostream &out, const Date &date)"
.br
.ti -1c
.RI "std::istream & \fBTravel::operator>>\fP (std::istream &in, Date &date)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
