.TH "forType< Type >::repeat< 0, Tail... >" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
forType< Type >::repeat< 0, Tail... > \- Root of the recursion for \fBrepeat\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ttype\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "template<template< typename\&.\&.\&. A > class applicant> using \fBapply\fP = applicant< Tail\&.\&.\&. >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Type>
.br
template<typename\&.\&.\&. Tail>
.br
struct forType< Type >::repeat< 0, Tail\&.\&.\&. >"
Root of the recursion for \fBrepeat\fP\&. 
.PP
Definition at line 25 of file ttype\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename Type > template<typename\&.\&.\&. Tail> template<template< typename\&.\&.\&. A > class applicant> using \fBforType\fP< Type >::\fBrepeat\fP< 0, Tail\&.\&.\&. >::\fBapply\fP =  applicant<Tail\&.\&.\&.>"

.PP
Definition at line 27 of file ttype\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
