HashMap< Key, Value >
NAME
HashMap< Key, Value > - A generic implementation of a HashMap.
SYNOPSIS
#include <HashMap.hpp>
Public Member Functions
unsigned capacity () const
The capacity of the HashMap.
void clear ()
Clears the contents of the hash map.
bool contains (Key const &k)
Returns true if the key is contained in the HashMap.
std::unique_ptr< Nullable< Value > > get (Key const &k)
Returns the Value associated with the given Key if any.
HashMap ()
Initialize the HashMap to DEFAULT_SIZE.
HashMap (HashMap< Key, Value > const &other)
std::unique_ptr< ArrayList< Key > > keys () const
Returns all contained keys in a list.
unsigned length () const
The amount of elements in this HashMap.
HashMap< Key, Value > & operator= (HashMap< Key, Value > const &other)
void put (Key &&k, Value &&v)
Move the given key-value pair in the HashMap.
void put (Key &&k, Value const &v)
Put the given key-value pair in the HashMap.
void put (Key const &k, Value &&v)
Put the given key-value pair in the HashMap.
void put (Key const &k, Value const &v)
Put the given key-value pair in the HashMap.
void putAll (HashMap< Key, Value > const &other)
Puts all elements contained in a Hash Map in this one.
void remove (Key const &k)
Removes the given key from the hash map by setting it's corresponding entry's as uninitialized.
std::unique_ptr< ArrayList< Tuple< Key, Value > > > toList ()
Return a list of the key-value pairs stored in this HashMap.
const SpecEntry * underlying () const
Returns a constant pointer to the underlying entry list for the purposes of iteration.
std::unique_ptr< ArrayList< Value > > values () const
Returns all contained values in a list.
~HashMap ()
Private Types
typedef Entry< Key, Value > * SpecEntry
Shorthand for the Specialized Entry.
Private Member Functions
void copy (HashMap< Key, Value > const &other)
Convenience method for copying another HashMap.
void expand ()
Expand the hash map by doubling the current capacity.
unsigned findEntry (Key const &k) const
Finds hash associated with the given key.
void free ()
Free all dynamically allocated memory associated with the Hash Map.
template<typename T , typename std::enable_if_t<!std::is_pointer< T >::value > * = nullptr> uint32_t hash (const T *key) const
An implementation of the 32-bit FNV-1a hash.
template<typename T , typename std::enable_if_t< std::is_pointer< T >::value > * = nullptr> uint32_t hash (const T *key) const
An implementation of the 32-bit FNV-1a hash.
void init (unsigned size)
Initializes the hash map with a provided size.
double loadFactor () const
Returns the load factor of the HashMap.
void putAll (const SpecEntry *other, unsigned size)
Puts all key-value pairs in the given list in this Hash Map.
Private Attributes
SpecEntry * array
unsigned elemCount
unsigned reserved
Static Private Attributes
static const unsigned DEFAULT_SIZE = 16
The default size of the HashMap.
static constexpr double EXPAND_FACTOR = 0.8
The load factor threshold for expanding the underlying array.
Detailed Description
template<class Key, class Value>
class HashMap< Key, Value >"
A generic implementation of a HashMap.
This particular implementation uses the 32-bit FNV-1a hash.
Due to the way it is implemented there are several requirements for the Key type.
Firstly the Key type needs to overload the == and != operators.
Secondly the Key type cannot be a pointer of any kind.
Thirdly, if the Key is a class then it must not contain any pointers as fields. The third requirement can be circumvented by overloading the operator& of the class so that it returns the stored pointer instead. Doing this is NOT recommended and will probably break interoperability with STL methods.
Template Parameters
Key the key
Value the value
Definition at line 54 of file HashMap.hpp.
Member Typedef Documentation
template<class Key , class Value > typedef Entry<Key, Value>* HashMap< Key, Value >::SpecEntry [private]
Shorthand for the Specialized Entry.
Definition at line 57 of file HashMap.hpp.
Constructor & Destructor Documentation
template<class Key , class Value > HashMap< Key, Value >::HashMap () [inline]
Initialize the HashMap to DEFAULT_SIZE.
Definition at line 239 of file HashMap.hpp.
{ init(DEFAULT_SIZE); }
template<class Key , class Value > HashMap< Key, Value >::~HashMap () [inline]
Definition at line 241 of file HashMap.hpp.
             {
    // LOG(INFO, "Destructor called.");
    free();
  }
template<class Key , class Value > HashMap< Key, Value >::HashMap (HashMap< Key, Value > const & other) [inline]
Definition at line 246 of file HashMap.hpp.
                                            {
    if (this != &other)
      copy(other);
  }
Member Function Documentation
template<class Key , class Value > unsigned HashMap< Key, Value >::capacity () const [inline]
The capacity of the HashMap.
Returns
the capacity
Definition at line 296 of file HashMap.hpp.
{ return reserved; }
Referenced by HashMap< SimpleString, const char * >::copy(), HashMap< SimpleString, const char * >::expand(), HashMap< SimpleString, const char * >::findEntry(), HashMap< SimpleString, const char * >::free(), HashMap< SimpleString, const char * >::keys(), HashMap< SimpleString, const char * >::loadFactor(), HashMap< SimpleString, const char * >::putAll(), HashMap< SimpleString, const char * >::toList(), and HashMap< SimpleString, const char * >::values().
template<class Key , class Value > void HashMap< Key, Value >::clear () [inline]
Clears the contents of the hash map.
Definition at line 446 of file HashMap.hpp.
               {
    free();
    init(DEFAULT_SIZE);
  }
template<class Key , class Value > bool HashMap< Key, Value >::contains (Key const & k) [inline]
Returns true if the key is contained in the HashMap.
Parameters
k the key
Returns
is the key in the HashMap
Definition at line 287 of file HashMap.hpp.
                              {
    unsigned hsh = findEntry(k);
    return array[hsh] ? true : false;
  }
template<class Key , class Value > void HashMap< Key, Value >::copy (HashMap< Key, Value > const & other) [inline], [private]
Convenience method for copying another HashMap.
Parameters
other the HashMap to copy
Definition at line 122 of file HashMap.hpp.
                                              {
    // LOG(INFO, "Copy HashMap");
    array = new SpecEntry[other.capacity()];
    reserved = other.capacity();
    elemCount = 0;
    putAll(other);
  }
Referenced by HashMap< SimpleString, const char * >::HashMap(), and HashMap< SimpleString, const char * >::operator=().
template<class Key , class Value > void HashMap< Key, Value >::expand () [inline], [private]
Expand the hash map by doubling the current capacity. This operation requires that all elements are rehashed since the hash relies on the capacity, as such it can be a bit slow for a large number of elements
Definition at line 175 of file HashMap.hpp.
                {
    // LOG(INFO, "Expand HashMap");
    SpecEntry *const newarray = new SpecEntry[capacity() * 2];
    unsigned oldCapacity = capacity();
    for (int i = 0; i < capacity() * 2; i++) {
      newarray[i] = nullptr;
    }
    const SpecEntry *const oldarray = array;
    array = newarray;
    reserved = capacity() * 2;
    elemCount = 0;
    putAll(oldarray, oldCapacity);
    for (unsigned i = 0; i < oldCapacity; i++) {
      if (oldarray[i])
        delete oldarray[i];
    }
    delete[] oldarray;
  }
Referenced by HashMap< SimpleString, const char * >::put().
template<class Key , class Value > unsigned HashMap< Key, Value >::findEntry (Key const & k) const [inline], [private]
Finds hash associated with the given key. This is also the function that deals with hash collisions. The way hash collision resolution is accomplished is simply by hashing the key and incrementing it by one until a free hash is reached or the hash where that key is stored is found.
Parameters
k the key, whose hash to find
Returns
the position of the key in the underlying array
Definition at line 141 of file HashMap.hpp.
                                         {
    uint32_t hsh = hash(&k) % capacity();
    while (array[hsh] && array[hsh]->key != k) {
      hsh++;
      if (hsh >= capacity()) {
        hsh = 0;
      }
    }
    return hsh;
  }
Referenced by HashMap< SimpleString, const char * >::contains(), HashMap< SimpleString, const char * >::get(), HashMap< SimpleString, const char * >::put(), and HashMap< SimpleString, const char * >::remove().
template<class Key , class Value > void HashMap< Key, Value >::free () [inline], [private]
Free all dynamically allocated memory associated with the Hash Map.
Definition at line 216 of file HashMap.hpp.
              {
    // LOG(INFO, "Free HashMap");
    for (unsigned i = 0; i < capacity(); i++) {
      if (array[i])
        delete array[i];
    }
    delete[] array;
    reserved = 0;
    elemCount = 0;
  }
Referenced by HashMap< SimpleString, const char * >::clear(), HashMap< SimpleString, const char * >::operator=(), and HashMap< SimpleString, const char * >::~HashMap().
template<class Key , class Value > std::unique_ptr<Nullable<Value> > HashMap< Key, Value >::get (Key const & k) [inline]
Returns the Value associated with the given Key if any. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the key doesn't exist or an instance of NotNull wrapped around the Value.
Parameters
k the key, whose value to get
Returns
the value, if any
Definition at line 273 of file HashMap.hpp.
                                                   {
    unsigned hsh = findEntry(k);
    if (!array[hsh]) {
      return std::make_unique<Null<Value>>();
    } else
      return std::make_unique<NotNull<Value>>(array[hsh]->value);
  }
Referenced by Travel::TravelState::login().
template<class Key , class Value > template<typename T , typename std::enable_if_t<!std::is_pointer< T >::value > * = nullptr> uint32_t HashMap< Key, Value >::hash (const T * key) const [inline], [private]
An implementation of the 32-bit FNV-1a hash. This implementation is only available if T is not a pointer type
Template Parameters
T the type of the object to be hashed
Parameters
key the object to be hashed
Returns
the hash
Definition at line 75 of file HashMap.hpp.
                                    {
    unsigned char *bytes = (unsigned char *)key;
    uint32_t hash = 2166136261u;
    uint32_t elems = sizeof(*key);
    for (int i = 0; i < elems; i++) {
      hash ^= bytes[i];
      hash *= 16777619;
    }
    return hash;
  };
Referenced by HashMap< SimpleString, const char * >::findEntry(), and HashMap< SimpleString, const char * >::hash().
template<class Key , class Value > template<typename T , typename std::enable_if_t< std::is_pointer< T >::value > * = nullptr> uint32_t HashMap< Key, Value >::hash (const T * key) const [inline], [private]
An implementation of the 32-bit FNV-1a hash. This implementation is only available if T is a pointer type
Template Parameters
T the type of the object to be hashed
Parameters
key the object to be hashed
Returns
the hash
Definition at line 97 of file HashMap.hpp.
                                    {
    unsigned char *bytes = (unsigned char *)*key;
    uint32_t hash = 2166136261u;
    uint32_t elems = strlen(*key); // This assumes T is char*.
    for (int i = 0; i < elems; i++) {
      hash ^= bytes[i];
      hash *= 16777619;
    }
    return hash;
  };
template<class Key , class Value > void HashMap< Key, Value >::init (unsigned size) [inline], [private]
Initializes the hash map with a provided size. Assumes that the previous array, if such, has already been freed, otherwise it leaks memory.
Parameters
size the size to initialize the hash map with
Definition at line 159 of file HashMap.hpp.
                           {
    // LOG(INFO, "Initialize HashMap");
    array = new SpecEntry[size];
    reserved = size;
    elemCount = 0;
    for (int i = 0; i < size; i++) {
      array[i] = nullptr;
    }
  }
Referenced by HashMap< SimpleString, const char * >::clear(), and HashMap< SimpleString, const char * >::HashMap().
template<class Key , class Value > std::unique_ptr<ArrayList<Key> > HashMap< Key, Value >::keys () const [inline]
Returns all contained keys in a list. The order in which the keys appear in the list is arbitrary.
Returns
a pointer to the list of keys
Definition at line 431 of file HashMap.hpp.
                                             {
    std::unique_ptr<ArrayList<Key>> list =
        std::make_unique<ArrayList<Key>>(length());
    for (int i = 0; i < capacity(); i++) {
      if (array[i]) {
        list->append(array[i]->key);
      }
    }
    return list;
  }
Referenced by User::~User().
template<class Key , class Value > unsigned HashMap< Key, Value >::length () const [inline]
The amount of elements in this HashMap.
Returns
the length
Definition at line 263 of file HashMap.hpp.
{ return elemCount; }
Referenced by HashMap< SimpleString, const char * >::keys(), HashMap< SimpleString, const char * >::loadFactor(), HashMap< SimpleString, const char * >::toList(), and HashMap< SimpleString, const char * >::values().
template<class Key , class Value > double HashMap< Key, Value >::loadFactor () const [inline], [private]
Returns the load factor of the HashMap. The load factor is the ratio of the total allocated capacity that is filled.
Returns
the load factor
Definition at line 116 of file HashMap.hpp.
{ return length() / (double)capacity(); }
Referenced by HashMap< SimpleString, const char * >::put().
template<class Key , class Value > HashMap<Key, Value>& HashMap< Key, Value >::operator= (HashMap< Key, Value > const & other) [inline]
Definition at line 251 of file HashMap.hpp.
                                                                   {
    if (this != &other) {
      free();
      copy(other);
    }
    return *this;
  }
template<class Key , class Value > void HashMap< Key, Value >::put (Key && k, Value && v) [inline]
Move the given key-value pair in the HashMap. If the key is already in the HashMap, its value will be updated.
Parameters
k the key
v the value
Definition at line 323 of file HashMap.hpp.
                               {
    if (loadFactor() >= EXPAND_FACTOR) {
      expand();
    }
    unsigned hsh = findEntry(k);
    if (!array[hsh]) {
      array[hsh] = new Entry<Key, Value>{std::move(k), std::move(v)};
      elemCount++;
      return;
    }
    array[hsh]->value = std::move(v);
  }
template<class Key , class Value > void HashMap< Key, Value >::put (Key && k, Value const & v) [inline]
Put the given key-value pair in the HashMap. If the key is already in the HashMap, its value will be updated.
Parameters
k the key
v the value
Definition at line 342 of file HashMap.hpp.
                                    {
    if (loadFactor() >= EXPAND_FACTOR) {
      expand();
    }
    unsigned hsh = findEntry(k);
    if (!array[hsh]) {
      array[hsh] = new Entry<Key, Value>{std::move(k), v};
      elemCount++;
      return;
    }
    array[hsh]->value = v;
  }
template<class Key , class Value > void HashMap< Key, Value >::put (Key const & k, Value && v) [inline]
Put the given key-value pair in the HashMap. If the key is already in the HashMap, its value will be updated.
Parameters
k the key
v the value
Definition at line 361 of file HashMap.hpp.
                                    {
    if (loadFactor() >= EXPAND_FACTOR) {
      expand();
    }
    unsigned hsh = findEntry(k);
    if (!array[hsh]) {
      array[hsh] = new Entry<Key, Value>{k, std::move(v)};
      elemCount++;
      return;
    }
    array[hsh]->value = std::move(v);
  }
template<class Key , class Value > void HashMap< Key, Value >::put (Key const & k, Value const & v) [inline]
Put the given key-value pair in the HashMap. If the key is already in the HashMap, its value will be updated.
Parameters
k the key
v the value
Definition at line 304 of file HashMap.hpp.
                                         {
    if (loadFactor() >= EXPAND_FACTOR) {
      expand();
    }
    unsigned hsh = findEntry(k);
    if (!array[hsh]) {
      array[hsh] = new Entry<Key, Value>{k, v};
      elemCount++;
      return;
    }
    array[hsh]->value = v;
  }
Referenced by User::addVisit(), HashMap< SimpleString, const char * >::putAll(), Travel::TravelState::TravelState(), and User::User().
template<class Key , class Value > void HashMap< Key, Value >::putAll (const SpecEntry * other, unsigned size) [inline], [private]
Puts all key-value pairs in the given list in this Hash Map.
Parameters
other an array of Entries
the size of the array
Definition at line 205 of file HashMap.hpp.
                                                     {
    for (unsigned i = 0; i < size; i++) {
      if (!other[i])
        continue; // Skip if the entry is not initialized
      put(other[i]->key, other[i]->value);
    }
  }
Referenced by HashMap< SimpleString, const char * >::copy(), HashMap< SimpleString, const char * >::expand(), and HashMap< SimpleString, const char * >::putAll().
template<class Key , class Value > void HashMap< Key, Value >::putAll (HashMap< Key, Value > const & other) [inline]
Puts all elements contained in a Hash Map in this one.
Parameters
other the HashMap whose element to add to this one
Definition at line 232 of file HashMap.hpp.
                                                {
    putAll(other.array, other.capacity());
  }
template<class Key , class Value > void HashMap< Key, Value >::remove (Key const & k) [inline]
Removes the given key from the hash map by setting it's corresponding entry's as uninitialized. This will probably free any memory associated with the Key, Value pair
Parameters
k the key to remove
Definition at line 381 of file HashMap.hpp.
                            {
    unsigned hsh = findEntry(k);
    if (!array[hsh])
      return;
    delete array[hsh];
    array[hsh] = nullptr;
    elemCount--;
  }
template<class Key , class Value > std::unique_ptr<ArrayList<Tuple<Key, Value> > > HashMap< Key, Value >::toList () [inline]
Return a list of the key-value pairs stored in this HashMap.
Definition at line 398 of file HashMap.hpp.
                                                       {
    auto list = std::make_unique<ArrayList<Tuple<Key, Value>>>(length());
    for (int i = 0; i < capacity(); i++) {
      if (array[i]) {
        list->append(
            std::move(Tuple<Key, Value>(array[i]->key, array[i]->value)));
      }
    }
    return list;
  }
template<class Key , class Value > const SpecEntry* HashMap< Key, Value >::underlying () const [inline]
Returns a constant pointer to the underlying entry list for the purposes of iteration.
Returns
the entries
Definition at line 395 of file HashMap.hpp.
{ return array; }
template<class Key , class Value > std::unique_ptr<ArrayList<Value> > HashMap< Key, Value >::values () const [inline]
Returns all contained values in a list. The order in which the values appear in the list is arbitrary.
Returns
a pointer to the list of values
Definition at line 414 of file HashMap.hpp.
                                                 {
    std::unique_ptr<ArrayList<Value>> list =
        std::make_unique<ArrayList<Value>>(length());
    for (int i = 0; i < capacity(); i++) {
      if (array[i]) {
        list->append(array[i]->value);
      }
    }
    return list;
  }
Referenced by Travel::TravelState::~TravelState(), and User::~User().
Member Data Documentation
template<class Key , class Value > SpecEntry* HashMap< Key, Value >::array [private]
Definition at line 62 of file HashMap.hpp.
Referenced by HashMap< SimpleString, const char * >::contains(), HashMap< SimpleString, const char * >::copy(), HashMap< SimpleString, const char * >::expand(), HashMap< SimpleString, const char * >::findEntry(), HashMap< SimpleString, const char * >::free(), HashMap< SimpleString, const char * >::get(), HashMap< SimpleString, const char * >::init(), HashMap< SimpleString, const char * >::keys(), HashMap< SimpleString, const char * >::put(), HashMap< SimpleString, const char * >::putAll(), HashMap< SimpleString, const char * >::remove(), HashMap< SimpleString, const char * >::toList(), HashMap< SimpleString, const char * >::underlying(), and HashMap< SimpleString, const char * >::values().
template<class Key , class Value > const unsigned HashMap< Key, Value >::DEFAULT_SIZE = 16 [static], [private]
The default size of the HashMap.
Definition at line 59 of file HashMap.hpp.
Referenced by HashMap< SimpleString, const char * >::clear(), and HashMap< SimpleString, const char * >::HashMap().
template<class Key , class Value > unsigned HashMap< Key, Value >::elemCount [private]
Definition at line 64 of file HashMap.hpp.
Referenced by HashMap< SimpleString, const char * >::copy(), HashMap< SimpleString, const char * >::expand(), HashMap< SimpleString, const char * >::free(), HashMap< SimpleString, const char * >::init(), HashMap< SimpleString, const char * >::length(), HashMap< SimpleString, const char * >::put(), and HashMap< SimpleString, const char * >::remove().
template<class Key , class Value > constexpr double HashMap< Key, Value >::EXPAND_FACTOR = 0.8 [static], [constexpr], [private]
The load factor threshold for expanding the underlying array.
Definition at line 61 of file HashMap.hpp.
Referenced by HashMap< SimpleString, const char * >::put().
template<class Key , class Value > unsigned HashMap< Key, Value >::reserved [private]
Definition at line 63 of file HashMap.hpp.
Referenced by HashMap< SimpleString, const char * >::capacity(), HashMap< SimpleString, const char * >::copy(), HashMap< SimpleString, const char * >::expand(), HashMap< SimpleString, const char * >::free(), and HashMap< SimpleString, const char * >::init().
Author
Generated automatically by Doxygen for Traveller's App from the source code.