.TH "TravellersApp/src/parser/HTLInterpreter.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/parser/HTLInterpreter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./InvalidArgumentException\&.hpp'\fP
.br
\fC#include '\&.\&./ReachedEndOfStreamException\&.hpp'\fP
.br
\fC#include '\&.\&./TravelState\&.hpp'\fP
.br
\fC#include '\&.\&./WrongTokenTypeException\&.hpp'\fP
.br
\fC#include 'CommandList\&.hpp'\fP
.br
\fC#include 'Interpreter\&.hpp'\fP
.br
\fC#include 'Token\&.hpp'\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTravel::HTLInterpreter\fP"
.br
.RI "An interpreter for general commands\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTravel\fP"
.br
.RI "Collects all code that is not necessarily easily reusable\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
