IList< A >
NAME
IList< A > - An interface for a generic list.
SYNOPSIS
#include <IList.hpp>
Inherited by ArrayList< A >, and LinkedList< A >.
Public Member Functions
virtual void append (A &&elem)=0
Appends the given element to the list.
virtual void append (A const &elem)=0
Appends the given element to the list.
virtual void clear ()=0
Clears the list.
virtual bool contains (A const &elem) const =0
Returns true if the given element is contained in the list.
virtual A & get (unsigned index) const =0
Returns the value at the index.
virtual void insert (A &&elem, unsigned at)=0
Inserts the given element in the list at the specified position.
virtual void insert (A const &elem, unsigned at)=0
Inserts the given element in the list at the specified position.
bool isEmpty () const
Checks if the list is empty.
virtual unsigned length () const =0
Returns the amount of elements contained in the list.
std::unique_ptr< Nullable< A > > operator[] (unsigned index) const
Returns the value associated with the given index if any.
virtual std::unique_ptr< Nullable< A > > pop ()=0
Removes the last element of the list, if any, and returns it.
virtual void prepend (A &&elem)=0
Prepends the given element to the list.
virtual void prepend (A const &elem)=0
Prepends the given element to the list.
virtual int remove (const A &elem)=0
Remove the first occurence of the given element in the list.
virtual std::unique_ptr< Nullable< A > > removeAt (unsigned ind)=0
Removes the value associated with the given index, if any, and returns it.
virtual std::unique_ptr< Nullable< A > > shift ()=0
Removes the first element of the list, if any, and returns it.
virtual ~IList ()=default
Detailed Description
template<class A>
class IList< A >"
An interface for a generic list.
Template Parameters
A the type of the elements in the list
Definition at line 15 of file IList.hpp.
Constructor & Destructor Documentation
template<class A > virtual IList< A >::~IList () [virtual], [default]
Member Function Documentation
template<class A > virtual void IList< A >::append (A && elem) [pure virtual]
Appends the given element to the list.
Parameters
elem the element
Implemented in ArrayList< Tuple >, ArrayList< Token >, ArrayList< SimpleString >, ArrayList< char * >, and ArrayList< A >.
template<class A > virtual void IList< A >::append (A const & elem) [pure virtual]
Appends the given element to the list.
Parameters
elem the element
Implemented in ArrayList< Tuple >, ArrayList< Token >, ArrayList< SimpleString >, ArrayList< char * >, ArrayList< A >, and LinkedList< A >.
template<class A > virtual void IList< A >::clear () [pure virtual]
Clears the list.
Implemented in ArrayList< A >, ArrayList< SimpleString >, ArrayList< Token >, ArrayList< Tuple >, ArrayList< char * >, and LinkedList< A >.
template<class A > virtual bool IList< A >::contains (A const & elem) const [pure virtual]
Returns true if the given element is contained in the list.
Parameters
elem the element to search for
Returns
if the element is contained
Implemented in ArrayList< Tuple >, ArrayList< Token >, ArrayList< SimpleString >, ArrayList< char * >, ArrayList< A >, and LinkedList< A >.
template<class A > virtual A& IList< A >::get (unsigned index) const [pure virtual]
Returns the value at the index.
Parameters
index the index
Returns
the value
Implemented in ArrayList< A >, ArrayList< SimpleString >, ArrayList< Token >, ArrayList< Tuple >, ArrayList< char * >, and LinkedList< A >.
Referenced by IList< char * >::operator[]().
template<class A > virtual void IList< A >::insert (A && elem, unsigned at) [pure virtual]
Inserts the given element in the list at the specified position.
Parameters
elem the element
at the position
Implemented in ArrayList< Tuple >, ArrayList< Token >, ArrayList< SimpleString >, ArrayList< char * >, and ArrayList< A >.
template<class A > virtual void IList< A >::insert (A const & elem, unsigned at) [pure virtual]
Inserts the given element in the list at the specified position.
Parameters
elem the element
at the position
Implemented in ArrayList< Tuple >, ArrayList< Token >, ArrayList< SimpleString >, ArrayList< char * >, ArrayList< A >, LinkedList< A >, and ArraySet< A >.
template<class A > bool IList< A >::isEmpty () const [inline]
Checks if the list is empty.
Definition at line 141 of file IList.hpp.
{ return length() == 0; }
template<class A > virtual unsigned IList< A >::length () const [pure virtual]
Returns the amount of elements contained in the list.
Implemented in LinkedList< A >, ArrayList< A >, ArrayList< SimpleString >, ArrayList< Token >, ArrayList< Tuple >, and ArrayList< char * >.
Referenced by IList< char * >::isEmpty(), and IList< char * >::operator[]().
template<class A > std::unique_ptr<Nullable<A> > IList< A >::operator[] (unsigned index) const [inline]
Returns the value associated with the given index if any. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the index doesn't exist or an instance of NotNull wrapped around the value.
Meant as some sort of cautious get in case for some reason the length of the list is unknown.
Parameters
index the index, whose value to get
Returns
the value, if any
Definition at line 70 of file IList.hpp.
                                                              {
    if (index < length())
      return std::make_unique<NotNull<A>>(get(index));
    return std::make_unique<Null<A>>();
  }
template<class A > virtual std::unique_ptr<Nullable<A> > IList< A >::pop () [pure virtual]
Removes the last element of the list, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the list is empty or an instance of NotNull wrapped around the value.
Returns
the value, if any
Implemented in ArrayList< A >, ArrayList< SimpleString >, ArrayList< Token >, ArrayList< Tuple >, ArrayList< char * >, and LinkedList< A >.
template<class A > virtual void IList< A >::prepend (A && elem) [pure virtual]
Prepends the given element to the list.
Parameters
elem the element
Implemented in ArrayList< Tuple >, ArrayList< Token >, ArrayList< SimpleString >, ArrayList< char * >, and ArrayList< A >.
template<class A > virtual void IList< A >::prepend (A const & elem) [pure virtual]
Prepends the given element to the list.
Parameters
elem the element
Implemented in ArrayList< Tuple >, ArrayList< Token >, ArrayList< SimpleString >, ArrayList< char * >, ArrayList< A >, and LinkedList< A >.
template<class A > virtual int IList< A >::remove (const A & elem) [pure virtual]
Remove the first occurence of the given element in the list. All following elements are brought back by one index in order to fill the hole left by the removal
Parameters
elem the element to remove
Returns
the index of the removed element
Implemented in ArrayList< Tuple >, ArrayList< Token >, ArrayList< SimpleString >, ArrayList< char * >, ArrayList< A >, and LinkedList< A >.
template<class A > virtual std::unique_ptr<Nullable<A> > IList< A >::removeAt (unsigned ind) [pure virtual]
Removes the value associated with the given index, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the index doesn't exist or an instance of NotNull wrapped around the value.
All following elements are moved back by one index to fill the hole left by the removal
Parameters
index the index, whose value to remove
Returns
the value, if any
Implemented in ArrayList< A >, ArrayList< SimpleString >, ArrayList< Token >, ArrayList< Tuple >, ArrayList< char * >, and LinkedList< A >.
template<class A > virtual std::unique_ptr<Nullable<A> > IList< A >::shift () [pure virtual]
Removes the first element of the list, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the list is empty or an instance of NotNull wrapped around the value.
All following elements are moved back by one index to fill the hole left by the removal
Returns
the value, if any
Implemented in ArrayList< A >, ArrayList< SimpleString >, ArrayList< Token >, ArrayList< Tuple >, ArrayList< char * >, and LinkedList< A >.
Author
Generated automatically by Doxygen for Traveller's App from the source code.