.TH "TravellersApp/src/collection/IList.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/collection/IList.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Nullable\&.hpp'\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIList< A >\fP"
.br
.RI "An interface for a generic list\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
