.TH "TravellersApp/src/parser/Interpreter.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/parser/Interpreter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./InvalidArgumentException\&.hpp'\fP
.br
\fC#include '\&.\&./ReachedEndOfStreamException\&.hpp'\fP
.br
\fC#include '\&.\&./WrongTokenTypeException\&.hpp'\fP
.br
\fC#include 'CommandList\&.hpp'\fP
.br
\fC#include 'Token\&.hpp'\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInterpreter< Controller >\fP"
.br
.RI "A interface for command-line interpreters\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
