Interpreter< Controller >
NAME
Interpreter< Controller > - A interface for command-line interpreters.
SYNOPSIS
#include <Interpreter.hpp>
Public Member Functions
Interpreter (std::shared_ptr< ArrayList< Token >> _tokens)
virtual bool parse (Controller &state)=0
Parse the provided tokens into the given controller.
Public Attributes
bool errorflag = false
Protected Member Functions
Token consume (TokenType type, const char *msg)
If the next token is of the provided TokenType return the next token else throw an error with the provided message.
void error (int line, const char *msg) const
Throw an error at the given line with the given message.
bool isAtEnd () const
Has the interpreter consumed all the tokens it was given.
bool matches (TokenType type) const
Is the next token of the provided TokenType.
Token next ()
Pop the next token.
Token peek () const
Peek at the next token.
Token prev () const
Return the previous token.
Protected Attributes
unsigned index = 0
std::shared_ptr< ArrayList< Token > > tokens
Detailed Description
template<typename Controller>
class Interpreter< Controller >"
A interface for command-line interpreters.
Definition at line 14 of file Interpreter.hpp.
Constructor & Destructor Documentation
template<typename Controller > Interpreter< Controller >::Interpreter (std::shared_ptr< ArrayList< Token >> _tokens) [inline], [explicit]
Definition at line 83 of file Interpreter.hpp.
      : tokens(_tokens) {}
Member Function Documentation
template<typename Controller > Token Interpreter< Controller >::consume (TokenType type, const char * msg) [inline], [protected]
If the next token is of the provided TokenType return the next token else throw an error with the provided message.
Exceptions
WrongTokenTypeException
Definition at line 62 of file Interpreter.hpp.
                                                 {
    if (!matches(type)) {
      error(peek().line, msg);
    } else {
      return next();
    }
    // Never used. Just here to suppress a compiler warning
    return {TokenType::EOF_T, "", 0};
  }
template<typename Controller > void Interpreter< Controller >::error (int line, const char * msg) const [inline], [protected]
Throw an error at the given line with the given message.
Exceptions
WrongTokenTypeException
Definition at line 44 of file Interpreter.hpp.
                                              {
    char sline[32];
    sprintf(sline, "%d", line);
    char *nmsg = new char[6 + strlen(sline) + 3 + strlen(msg) + 1];
    strcpy(nmsg, "Line: ");
    strcpy(nmsg + 6, sline);
    strcpy(nmsg + 6 + strlen(sline), " - ");
    strcpy(nmsg + 6 + strlen(sline) + 3, msg);
    // std::cerr<<nmsg<<std::endl;
    WrongTokenTypeException e(nmsg);
    delete[] nmsg;
    throw e;
  }
Referenced by Interpreter< VisitBuilder >::consume().
template<typename Controller > bool Interpreter< Controller >::isAtEnd () const [inline], [protected]
Has the interpreter consumed all the tokens it was given.
Definition at line 22 of file Interpreter.hpp.
{ return index >= tokens->length(); }
Referenced by Interpreter< VisitBuilder >::next(), and Interpreter< VisitBuilder >::peek().
template<typename Controller > bool Interpreter< Controller >::matches (TokenType type) const [inline], [protected]
Is the next token of the provided TokenType.
Definition at line 73 of file Interpreter.hpp.
{ return peek().t == type; }
Referenced by Interpreter< VisitBuilder >::consume().
template<typename Controller > Token Interpreter< Controller >::next () [inline], [protected]
Pop the next token.
Definition at line 25 of file Interpreter.hpp.
               {
    if (isAtEnd())
      throw ReachedEndOfStreamException{};
    else {
      index++;
      return tokens->get(index - 1);
    }
  }
Referenced by Interpreter< VisitBuilder >::consume().
template<typename Controller > virtual bool Interpreter< Controller >::parse (Controller & state) [pure virtual]
Parse the provided tokens into the given controller.
template<typename Controller > Token Interpreter< Controller >::peek () const [inline], [protected]
Peek at the next token.
Definition at line 34 of file Interpreter.hpp.
                     {
    if (isAtEnd())
      throw ReachedEndOfStreamException{};
    else {
      return tokens->get(index);
    }
  }
Referenced by Interpreter< VisitBuilder >::consume(), and Interpreter< VisitBuilder >::matches().
template<typename Controller > Token Interpreter< Controller >::prev () const [inline], [protected]
Return the previous token.
Definition at line 76 of file Interpreter.hpp.
{ return tokens->get(index - 1); }
Member Data Documentation
template<typename Controller > bool Interpreter< Controller >::errorflag = false
Definition at line 79 of file Interpreter.hpp.
template<typename Controller > unsigned Interpreter< Controller >::index = 0 [protected]
Definition at line 18 of file Interpreter.hpp.
Referenced by Interpreter< VisitBuilder >::isAtEnd(), Interpreter< VisitBuilder >::next(), Interpreter< VisitBuilder >::peek(), and Interpreter< VisitBuilder >::prev().
template<typename Controller > std::shared_ptr<ArrayList<Token> > Interpreter< Controller >::tokens [protected]
Definition at line 17 of file Interpreter.hpp.
Referenced by Interpreter< VisitBuilder >::isAtEnd(), Interpreter< VisitBuilder >::next(), Interpreter< VisitBuilder >::peek(), and Interpreter< VisitBuilder >::prev().
Author
Generated automatically by Doxygen for Traveller's App from the source code.