InvalidArgumentException
NAME
InvalidArgumentException - An exception thrown when an invalid argument is passed to a function.
SYNOPSIS
#include <InvalidArgumentException.hpp>
Inherits std::exception.
Public Member Functions
InvalidArgumentException ()
InvalidArgumentException (const char *_msg)
virtual const char * what () const throw ()
~InvalidArgumentException ()
Private Attributes
char * msg
Static Private Attributes
static const char * DEFAULT_MESSAGE
Detailed Description
An exception thrown when an invalid argument is passed to a function.
Definition at line 9 of file InvalidArgumentException.hpp.
Constructor & Destructor Documentation
InvalidArgumentException::InvalidArgumentException (const char * _msg) [inline]
Definition at line 16 of file InvalidArgumentException.hpp.
                                             {
    msg = new char[strlen(_msg) + 1];
    strcpy(msg, _msg);
  }
References msg.
InvalidArgumentException::~InvalidArgumentException () [inline]
Definition at line 23 of file InvalidArgumentException.hpp.
{ delete[] msg; }
References msg.
InvalidArgumentException::InvalidArgumentException () [inline]
Definition at line 25 of file InvalidArgumentException.hpp.
: InvalidArgumentException(DEFAULT_MESSAGE) {}
Member Function Documentation
virtual const char* InvalidArgumentException::what () const [inline], [virtual]
Definition at line 21 of file InvalidArgumentException.hpp.
{ return msg; }
References msg.
Referenced by Travel::LoginInterpreter::parse(), Travel::VisitInterpreter::parse(), and Travel::HTLInterpreter::parse().
Member Data Documentation
const char * InvalidArgumentException::DEFAULT_MESSAGE [static], [private]
Initial value:
=
    "Provided argument was invalid"
Definition at line 11 of file InvalidArgumentException.hpp.
char* InvalidArgumentException::msg [private]
Definition at line 13 of file InvalidArgumentException.hpp.
Referenced by InvalidArgumentException(), what(), and ~InvalidArgumentException().
Author
Generated automatically by Doxygen for Traveller's App from the source code.