LinkedList< A >
NAME
LinkedList< A > - An implementation of a singly-linked list.
SYNOPSIS
#include <LinkedList.hpp>
Inherits IList< A >.
Public Member Functions
void append (A const &elem) override
Appends the given element to the list.
void appendAll (LinkedList< A > const &l)
Append all elements of the given list to this one.
void clear () override
Clears the list.
bool contains (A const &elem) const override
Returns true if the given element is contained in the list.
A get (unsigned index) const override
Returns the value at the index.
std::unique_ptr< Nullable< A > > head () const
Return the first element of the list.
void insert (A const &elem, unsigned at) override
Inserts the given element in the list at the specified position.
std::unique_ptr< Nullable< A > > last () const
Return the last element of the list.
unsigned int length () const override
Returns the amount of elements contained in the list.
LinkedList ()
std::unique_ptr< Nullable< A > > pop () override
Removes the last element of the list, if any, and returns it.
void prepend (A const &elem) override
Prepends the given element to the list.
void prependAll (LinkedList< A > const &l)
Prepend all elements of the given list to this one.
unsigned remove (const A &elem) override
Remove the first occurence of the given element in the list.
std::unique_ptr< Nullable< A > > removeAt (unsigned at) override
Removes the value associated with the given index, if any, and returns it.
std::unique_ptr< Nullable< A > > shift () override
Removes the first element of the list, if any, and returns it.
~LinkedList ()
Protected Attributes
Node< A > * _head
Node< A > * _last
int elemCount {}
Private Member Functions
void free ()
Free all nodes created by this list.
Detailed Description
template<class A>
class LinkedList< A >"
An implementation of a singly-linked list.
Definition at line 21 of file LinkedList.hpp.
Constructor & Destructor Documentation
template<class A > LinkedList< A >::LinkedList () [inline]
Definition at line 43 of file LinkedList.hpp.
               {
    _head = nullptr;
    _last = nullptr;
  }
References LinkedList< A >::_head, and LinkedList< A >::_last.
template<class A > LinkedList< A >::~LinkedList () [inline]
Definition at line 52 of file LinkedList.hpp.
{ free(); }
References LinkedList< A >::free().
Member Function Documentation
template<class A > void LinkedList< A >::append (A const & elem) [inline], [override], [virtual]
Appends the given element to the list.
Parameters
elem the element
Implements IList< A >.
Definition at line 48 of file LinkedList.hpp.
{ insert(elem, length()); }
References LinkedList< A >::insert(), and LinkedList< A >::length().
Referenced by LinkedList< A >::appendAll().
template<class A > void LinkedList< A >::appendAll (LinkedList< A > const & l) [inline]
Append all elements of the given list to this one.
Parameters
l the list to append
Definition at line 85 of file LinkedList.hpp.
                                         {
    for (int i = 0; i < l.length(); i++) {
      append(l.get(i));
    }
  }
References LinkedList< A >::append(), LinkedList< A >::get(), and LinkedList< A >::length().
template<class A > void LinkedList< A >::clear () [inline], [override], [virtual]
Clears the list.
Implements IList< A >.
Definition at line 172 of file LinkedList.hpp.
{ free(); }
References LinkedList< A >::free().
template<class A > bool LinkedList< A >::contains (A const & elem) const [inline], [override], [virtual]
Returns true if the given element is contained in the list.
Parameters
elem the element to search for
Returns
if the element is contained
Implements IList< A >.
Definition at line 133 of file LinkedList.hpp.
                                              {
    Node<A> *cur = _head;
    while (cur != nullptr) {
      if (cur->elem == elem)
        return true;
      cur = cur->next;
    }
    return false;
  }
References LinkedList< A >::_head, Node< A >::elem, and Node< A >::next.
template<class A > void LinkedList< A >::free () [inline], [private]
Free all nodes created by this list.
Definition at line 24 of file LinkedList.hpp.
              {
    Node<A> *cur = _head;
    while (cur != nullptr) {
      Node<A> *next = cur->next;
      delete cur;
      cur = next;
    }
    _head = nullptr;
    _last = nullptr;
    elemCount = 0;
  }
References LinkedList< A >::_head, LinkedList< A >::_last, LinkedList< A >::elemCount, and Node< A >::next.
Referenced by LinkedList< A >::clear(), and LinkedList< A >::~LinkedList().
template<class A > A LinkedList< A >::get (unsigned index) const [inline], [override], [virtual]
Returns the value at the index.
Parameters
index the index
Returns
the value
Implements IList< A >.
Definition at line 143 of file LinkedList.hpp.
                                       {
    if (index < 0)
      return get(0);
    if (index > length() - 1 && length() - 1 > 0)
      return get(length() - 1);
    if (index == 0)
      return _head->elem;
    if (index == length() - 1)
      return _last->elem;
    Node<A> *cur = _head;
    A value{};
    int counter = 0;
    while (cur != nullptr) {
      if (counter == index) {
        value = cur->elem;
        break;
      }
      cur = cur->next;
      counter++;
    }
    return value;
  }
References LinkedList< A >::_head, LinkedList< A >::_last, Node< A >::elem, LinkedList< A >::length(), and Node< A >::next.
Referenced by LinkedList< A >::appendAll(), and LinkedList< A >::prependAll().
template<class A > std::unique_ptr<Nullable<A> > LinkedList< A >::head () const [inline]
Return the first element of the list.
Definition at line 214 of file LinkedList.hpp.
                                          {
    if (_head == nullptr)
      return std::make_unique<Null<A>>();
    return std::make_unique<NotNull<A>>(_head->elem);
  }
References LinkedList< A >::_head.
template<class A > void LinkedList< A >::insert (A const & elem, unsigned at) [inline], [override], [virtual]
Inserts the given element in the list at the specified position.
Parameters
elem the element
at the position
Implements IList< A >.
Definition at line 54 of file LinkedList.hpp.
                                                   {
    if (at < 0)
      return;
    if (_head == nullptr) {
      Node<A> *s = new Node<A>{elem, nullptr};
      _head = _last = s;
    } else if (at == 0) {
      Node<A> *s = new Node<A>{elem, _head};
      _head = s;
    } else if (at >= length()) {
      Node<A> *s = new Node<A>{elem, nullptr};
      _last->next = s;
      _last = s;
    } else {
      Node<A> *cur = _head;
      for (int i = 0; i < at - 1; i++) {
        cur = cur->next;
      }
      Node<A> *s = new Node<A>{elem, cur->next};
      cur->next = s;
    }
    elemCount++;
  }
References LinkedList< A >::_head, LinkedList< A >::_last, LinkedList< A >::elemCount, LinkedList< A >::length(), and Node< A >::next.
Referenced by LinkedList< A >::append(), and LinkedList< A >::prepend().
template<class A > std::unique_ptr<Nullable<A> > LinkedList< A >::last () const [inline]
Return the last element of the list.
Definition at line 221 of file LinkedList.hpp.
                                          {
    if (_last == nullptr)
      return std::make_unique<Null<A>>();
    return std::make_unique<NotNull<A>>(_last->elem);
  }
References LinkedList< A >::_last.
template<class A > unsigned int LinkedList< A >::length () const [inline], [override], [virtual]
Returns the amount of elements contained in the list.
Implements IList< A >.
Definition at line 170 of file LinkedList.hpp.
{ return elemCount; }
References LinkedList< A >::elemCount.
Referenced by LinkedList< A >::append(), LinkedList< A >::appendAll(), LinkedList< A >::get(), LinkedList< A >::insert(), LinkedList< A >::pop(), LinkedList< A >::prependAll(), and LinkedList< A >::removeAt().
template<class A > std::unique_ptr<Nullable<A> > LinkedList< A >::pop () [inline], [override], [virtual]
Removes the last element of the list, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the list is empty or an instance of NotNull wrapped around the value.
Returns
the value, if any
Implements IList< A >.
Definition at line 209 of file LinkedList.hpp.
{ return removeAt(length() - 1); }
References LinkedList< A >::length(), and LinkedList< A >::removeAt().
template<class A > void LinkedList< A >::prepend (A const & elem) [inline], [override], [virtual]
Prepends the given element to the list.
Parameters
elem the element
Implements IList< A >.
Definition at line 50 of file LinkedList.hpp.
{ insert(elem, 0); }
References LinkedList< A >::insert().
Referenced by LinkedList< A >::prependAll().
template<class A > void LinkedList< A >::prependAll (LinkedList< A > const & l) [inline]
Prepend all elements of the given list to this one. Very slow for large lists.
Parameters
l the list to prepend
Definition at line 96 of file LinkedList.hpp.
                                          {
    for (int i = 0; i < l.length(); i++) {
      prepend(l.get(i));
    }
  }
References LinkedList< A >::get(), LinkedList< A >::length(), and LinkedList< A >::prepend().
template<class A > unsigned LinkedList< A >::remove (const A & elem) [inline], [override], [virtual]
Remove the first occurence of the given element in the list. All following elements are brought back by one index in order to fill the hole left by the removal
Parameters
elem the element to remove
Returns
the index of the removed element
Implements IList< A >.
Definition at line 114 of file LinkedList.hpp.
                                          {
    if (_head == nullptr)
      return 0;
    unsigned foundAt = 0;
    Node<A> *cur = _head;
    while (cur != nullptr) {
      if (cur->next->elem == elem) {
        Node<A> *temp = cur->next;
        cur->next = temp->next;
        delete temp;
        foundAt++;
        elemCount--;
        break;
      }
      cur = cur->next;
    }
    return foundAt;
  }
References LinkedList< A >::_head, Node< A >::elem, LinkedList< A >::elemCount, and Node< A >::next.
template<class A > std::unique_ptr<Nullable<A> > LinkedList< A >::removeAt (unsigned ind) [inline], [override], [virtual]
Removes the value associated with the given index, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the index doesn't exist or an instance of NotNull wrapped around the value.
All following elements are moved back by one index to fill the hole left by the removal
Parameters
index the index, whose value to remove
Returns
the value, if any
Implements IList< A >.
Definition at line 174 of file LinkedList.hpp.
                                                            {
    if (_head == nullptr)
      return std::make_unique<Null<A>>();
    if (at > length() - 1)
      return removeAt(length() - 1);
    A ret;
    if (at == 0) {
      Node<A> *temp = _head;
      _head = _head->next;
      ret = temp->elem;
      delete temp;
    } else {
      int counter = 0;
      Node<A> *cur = _head;
      while (cur != nullptr) {
        if (counter + 1 == at) {
          Node<A> *temp = cur->next;
          cur->next = temp->next;
          if (at == length() - 1) {
            _last = cur;
          }
          ret = temp->elem;
          delete temp;
          break;
        }
        counter++;
        cur = cur->next;
      }
    }
    elemCount--;
    return std::make_unique<NotNull<A>>(ret);
  }
References LinkedList< A >::_head, LinkedList< A >::_last, Node< A >::elem, LinkedList< A >::elemCount, LinkedList< A >::length(), and Node< A >::next.
Referenced by LinkedList< A >::pop(), and LinkedList< A >::shift().
template<class A > std::unique_ptr<Nullable<A> > LinkedList< A >::shift () [inline], [override], [virtual]
Removes the first element of the list, if any, and returns it. This is done by returning a pointer to a Nullable instance. It is an instance of Null if the list is empty or an instance of NotNull wrapped around the value.
All following elements are moved back by one index to fill the hole left by the removal
Returns
the value, if any
Implements IList< A >.
Definition at line 211 of file LinkedList.hpp.
{ return removeAt(0); }
References LinkedList< A >::removeAt().
Member Data Documentation
template<class A > Node<A>* LinkedList< A >::_head [protected]
Definition at line 37 of file LinkedList.hpp.
Referenced by LinkedList< A >::contains(), LinkedList< A >::free(), LinkedList< A >::get(), LinkedList< A >::head(), LinkedList< A >::insert(), LinkedList< A >::LinkedList(), LinkedList< A >::remove(), and LinkedList< A >::removeAt().
template<class A > Node<A>* LinkedList< A >::_last [protected]
Definition at line 38 of file LinkedList.hpp.
Referenced by LinkedList< A >::free(), LinkedList< A >::get(), LinkedList< A >::insert(), LinkedList< A >::last(), LinkedList< A >::LinkedList(), and LinkedList< A >::removeAt().
template<class A > int LinkedList< A >::elemCount {} [protected]
Definition at line 40 of file LinkedList.hpp.
Referenced by LinkedList< A >::free(), LinkedList< A >::insert(), LinkedList< A >::length(), LinkedList< A >::remove(), and LinkedList< A >::removeAt().
Author
Generated automatically by Doxygen for Traveller's App from the source code.