.TH "Node< A >" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node< A > \- A node used in a singly-linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LinkedList\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "A \fBelem\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class A>
.br
struct Node< A >"
A node used in a singly-linked list\&. 
.PP
Definition at line 15 of file LinkedList\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class A > A \fBNode\fP< A >::elem"

.PP
Definition at line 16 of file LinkedList\&.hpp\&.
.PP
Referenced by LinkedList< A >::contains(), LinkedList< A >::get(), LinkedList< A >::remove(), and LinkedList< A >::removeAt()\&.
.SS "template<class A > \fBNode\fP* \fBNode\fP< A >::next"

.PP
Definition at line 17 of file LinkedList\&.hpp\&.
.PP
Referenced by LinkedList< A >::contains(), LinkedList< A >::free(), LinkedList< A >::get(), LinkedList< A >::insert(), LinkedList< A >::remove(), and LinkedList< A >::removeAt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
