NoValueException
NAME
NoValueException - An exception thrown when there was an attempt to access a value when no value exists.
SYNOPSIS
#include <NoValueException.hpp>
Inherits std::exception.
Public Member Functions
NoValueException ()
NoValueException (const char *_msg)
virtual const char * what () const throw ()
~NoValueException ()
Private Attributes
char * msg
Static Private Attributes
static const char * DEFAULT_MESSAGE
Detailed Description
An exception thrown when there was an attempt to access a value when no value exists.
See also
Nullable
Definition at line 12 of file NoValueException.hpp.
Constructor & Destructor Documentation
NoValueException::NoValueException (const char * _msg) [inline]
Definition at line 21 of file NoValueException.hpp.
                                     {
    msg = new char[strlen(_msg) + 1];
    strcpy(msg, _msg);
  }
References msg.
NoValueException::~NoValueException () [inline]
Definition at line 26 of file NoValueException.hpp.
{ delete[] msg; }
References msg.
NoValueException::NoValueException () [inline]
Definition at line 28 of file NoValueException.hpp.
: NoValueException(DEFAULT_MESSAGE) {}
Member Function Documentation
virtual const char* NoValueException::what () const [inline], [virtual]
Definition at line 19 of file NoValueException.hpp.
{ return msg; }
References msg.
Referenced by Travel::LoginInterpreter::parse(), Travel::VisitInterpreter::parse(), and Travel::HTLInterpreter::parse().
Member Data Documentation
const char * NoValueException::DEFAULT_MESSAGE [static], [private]
Initial value:
=
    "Attempted to access null value."
Definition at line 14 of file NoValueException.hpp.
char* NoValueException::msg [private]
Definition at line 16 of file NoValueException.hpp.
Referenced by NoValueException(), what(), and ~NoValueException().
Author
Generated automatically by Doxygen for Traveller's App from the source code.