Nullable< A >
NAME
Nullable< A > - An optional value container inspired by Haskell's Maybe and Scala's Option.
SYNOPSIS
#include <Nullable.hpp>
Inherited by NotNull< A >, and Null< A >.
Public Member Functions
virtual A const get () const =0
Return the value contained if such exists, else throw a NoValueException.
A const getOrElse (A const &def) const
Return the value contained if such exists, else return the provided value.
bool isDefined () const
Is this value NotNull?
virtual bool isEmpty () const =0
Is this value Null?
virtual ~Nullable ()=default
Detailed Description
template<class A>
class Nullable< A >"
An optional value container inspired by Haskell's Maybe and Scala's Option.
It stores either a value of type A (wrapped into a NotNull instance) or an empty (represented by Null) value. It is intended to provide more safety when returning empty values than returning nullptr would. It not mean you shouldn't check if a value is null. Rather the entire purpose of the class is for when you do forget to check the value, you don't end up spending 2 hours finding out which nullptr you tried to dereference.
Definition at line 18 of file Nullable.hpp.
Constructor & Destructor Documentation
template<class A > virtual Nullable< A >::~Nullable () [virtual], [default]
Member Function Documentation
template<class A > virtual A const Nullable< A >::get () const [pure virtual]
Return the value contained if such exists, else throw a NoValueException.
Exceptions
NoValueException
Returns
the stored value
Implemented in Null< A >, and NotNull< A >.
Referenced by Nullable< A >::getOrElse().
template<class A > A const Nullable< A >::getOrElse (A const & def) const [inline]
Return the value contained if such exists, else return the provided value.
Parameters
def the default value to return
Returns
the stored value or the default value.
Definition at line 42 of file Nullable.hpp.
                                        {
    if (isEmpty())
      return def;
    return get();
  }
References Nullable< A >::get(), and Nullable< A >::isEmpty().
template<class A > bool Nullable< A >::isDefined () const [inline]
Is this value NotNull?
Definition at line 28 of file Nullable.hpp.
{ return !isEmpty(); }
References Nullable< A >::isEmpty().
template<class A > virtual bool Nullable< A >::isEmpty () const [pure virtual]
Is this value Null?
Implemented in Null< A >, and NotNull< A >.
Referenced by Nullable< A >::getOrElse(), and Nullable< A >::isDefined().
Author
Generated automatically by Doxygen for Traveller's App from the source code.