.TH "TravellersApp/src/Nullable.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/Nullable.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'NoValueException\&.hpp'\fP
.br
\fC#include 'debug\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNotNull< A >\fP"
.br
.RI "This class represents a wrapper around a concrete value\&. "
.ti -1c
.RI "class \fBNull< A >\fP"
.br
.RI "This class represents nothing (null)\&. "
.ti -1c
.RI "class \fBNullable< A >\fP"
.br
.RI "An optional value container inspired by Haskell's Maybe and Scala's Option\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
