ReachedEndOfStreamException
NAME
ReachedEndOfStreamException - An exception throw when Interpreter reaches the end of stream unexpectedly.
SYNOPSIS
#include <ReachedEndOfStreamException.hpp>
Inherits std::exception.
Public Member Functions
ReachedEndOfStreamException ()
ReachedEndOfStreamException (const char *_msg)
virtual const char * what () const throw ()
~ReachedEndOfStreamException ()
Private Attributes
char * msg
Static Private Attributes
static const char * DEFAULT_MESSAGE
Detailed Description
An exception throw when Interpreter reaches the end of stream unexpectedly.
Definition at line 13 of file ReachedEndOfStreamException.hpp.
Constructor & Destructor Documentation
ReachedEndOfStreamException::ReachedEndOfStreamException (const char * _msg) [inline]
Definition at line 22 of file ReachedEndOfStreamException.hpp.
                                                {
    msg = new char[strlen(_msg) + 1];
    strcpy(msg, _msg);
  }
References msg.
ReachedEndOfStreamException::~ReachedEndOfStreamException () [inline]
Definition at line 27 of file ReachedEndOfStreamException.hpp.
{ delete[] msg; }
References msg.
ReachedEndOfStreamException::ReachedEndOfStreamException () [inline]
Definition at line 29 of file ReachedEndOfStreamException.hpp.
      : ReachedEndOfStreamException(DEFAULT_MESSAGE) {}
Member Function Documentation
virtual const char* ReachedEndOfStreamException::what () const [inline], [virtual]
Definition at line 20 of file ReachedEndOfStreamException.hpp.
{ return msg; }
References msg.
Referenced by Travel::LoginInterpreter::parse(), Travel::VisitInterpreter::parse(), and Travel::HTLInterpreter::parse().
Member Data Documentation
const char * ReachedEndOfStreamException::DEFAULT_MESSAGE [static], [private]
Initial value:
=
    "Unexpectedly reached the of the input stream."
Definition at line 15 of file ReachedEndOfStreamException.hpp.
char* ReachedEndOfStreamException::msg [private]
Definition at line 17 of file ReachedEndOfStreamException.hpp.
Referenced by ReachedEndOfStreamException(), what(), and ~ReachedEndOfStreamException().
Author
Generated automatically by Doxygen for Traveller's App from the source code.