.TH "TravellersApp/src/ReachedEndOfStreamException.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/ReachedEndOfStreamException.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReachedEndOfStreamException\fP"
.br
.RI "An exception throw when \fBInterpreter\fP reaches the end of stream unexpectedly\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
