.TH "TravellersApp/src/SimpleString.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/SimpleString.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleString\fP"
.br
.RI "An exceedingly simple implementation of a string class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
