SimpleString
NAME
SimpleString - An exceedingly simple implementation of a string class.
SYNOPSIS
#include <SimpleString.hpp>
Public Member Functions
const char * get () const
Returns the underlying char*.
size_t length () const
Returns the length of the string (Excluding the \0)
bool operator!= (const char *str) const
Inequality with cstring. Utilizes std::strcmp.
bool operator!= (SimpleString const &str) const
Inequality with SimpleString. Utilizes std::strcmp.
char * operator& ()
HACK: Needed so this class can be used as a HashMap key.
const char * operator& () const
HACK: Needed so this class can be used as a HashMap key.
SimpleString & operator= (const char str[])
Assign from cstring.
SimpleString & operator= (SimpleString &&str)
Move the provided SimpleString to this one.
SimpleString & operator= (SimpleString const &str)
Copy the provided SimpleString to this one.
bool operator== (const char *str) const
Equality with cstring. Utilizes std::strcmp.
bool operator== (SimpleString const &str) const
Equality with SimpleString. Utilizes std::strcmp.
bool operator> (SimpleString const &other) const
Is this string greater than another? Utilizes std::strcmp.
SimpleString ()
Initialize with an empty string.
SimpleString (const char *str)
Copy constructor from cstring.
SimpleString (const char(&&str)[])
Move constructor from cstring.
SimpleString (SimpleString &&str)
Move constructor from SimpleString.
SimpleString (SimpleString const &str)
Copy constructor from SimpleString.
~SimpleString ()
Private Member Functions
void init (const char *str)
Initialize the string from a cstring.
Private Attributes
char * inner = nullptr
size_t len = 0
Friends
std::ostream & operator<< (std::ostream &out, SimpleString str)
Passes the underlying char* to the provided stream.
Detailed Description
An exceedingly simple implementation of a string class.
It's only purpose is to allow strings to be compared via ==. It also contains a (horrifically hacky) workaround that allows strings to be used as keys in a HashMap. Use char* over this wherever possible
Bug
Because of the HashMap workaround trying to retrieve SimpleString from Tuple via the Tuple::get method will fail as it will attempt to reinterpret_cast a char* to SimpleString*.
Definition at line 18 of file SimpleString.hpp.
Constructor & Destructor Documentation
SimpleString::SimpleString () [inline]
Initialize with an empty string.
Definition at line 37 of file SimpleString.hpp.
                 {
    inner = new char[1];
    inner[0] = '\0';
  }
References inner.
SimpleString::~SimpleString () [inline]
Definition at line 42 of file SimpleString.hpp.
                  {
    // LOG(INFO, "Destructor called.");
    delete[] inner;
  }
References inner.
SimpleString::SimpleString (SimpleString && str) [inline]
Move constructor from SimpleString.
Definition at line 48 of file SimpleString.hpp.
                                   {
    // LOG(INFO, "Moving SimpleString");
    len = str.len;
    inner = str.inner;
    str.len = 0;
    str.inner = nullptr;
  }
References inner, and len.
SimpleString::SimpleString (const char(&&) str[]) [inline]
Move constructor from cstring.
Definition at line 73 of file SimpleString.hpp.
                                    {
    // LOG(INFO, "Moving cstring into SimpleString");
    len = strlen(str);
    inner = const_cast<char *>(str);
  }
References inner, and len.
SimpleString::SimpleString (const char * str) [inline]
Copy constructor from cstring.
Definition at line 80 of file SimpleString.hpp.
                                {
    // LOG(INFO, "Copying SimpleString from cstring");
    init(str);
  }
References init().
SimpleString::SimpleString (SimpleString const & str) [inline]
Copy constructor from SimpleString.
Definition at line 86 of file SimpleString.hpp.
                                        {
    // LOG(INFO, "Copying SimpleString");
    init(str.inner);
  }
References init(), and inner.
Member Function Documentation
const char* SimpleString::get () const [inline]
Returns the underlying char*.
Definition at line 155 of file SimpleString.hpp.
{ return inner; }
References inner.
Referenced by operator>().
void SimpleString::init (const char * str) [inline], [private]
Initialize the string from a cstring.
Parameters
str the cstring to copy
Definition at line 28 of file SimpleString.hpp.
                             {
    // LOG(INFO, "Creating SimpleString instance.");
    len = strlen(str);
    inner = new char[len + 1];
    strcpy(inner, str);
  }
References inner, and len.
Referenced by operator=(), and SimpleString().
size_t SimpleString::length () const [inline]
Returns the length of the string (Excluding the \0)
Definition at line 163 of file SimpleString.hpp.
{ return len; }
References len.
Referenced by operator==().
bool SimpleString::operator!= (const char * str) const [inline]
Inequality with cstring. Utilizes std::strcmp.
Definition at line 129 of file SimpleString.hpp.
{ return !(*this == str); }
bool SimpleString::operator!= (SimpleString const & str) const [inline]
Inequality with SimpleString. Utilizes std::strcmp.
Definition at line 126 of file SimpleString.hpp.
{ return !(*this == str); }
char* SimpleString::operator& () [inline]
HACK: Needed so this class can be used as a HashMap key.
Bug
Messes up Tuple::get.
Returns
the underlying char*
Definition at line 140 of file SimpleString.hpp.
                    {
    // LOG(WARN, "Calling override of operator&.");
    return inner;
  }
References inner.
const char* SimpleString::operator& () const [inline]
HACK: Needed so this class can be used as a HashMap key.
Bug
Messes up Tuple::get.
Returns
the underlying char*
Definition at line 149 of file SimpleString.hpp.
                                {
    // LOG(WARN, "Calling override of operator&");
    return inner;
  }
References inner.
SimpleString& SimpleString::operator= (const char str[]) [inline]
Assign from cstring.
Definition at line 103 of file SimpleString.hpp.
                                            {
    // LOG(INFO, "Assigning SimpleString from cstring");
    if (inner)
      delete[] inner;
    init(str);
    return *this;
  }
References init(), and inner.
SimpleString& SimpleString::operator= (SimpleString && str) [inline]
Move the provided SimpleString to this one.
Definition at line 58 of file SimpleString.hpp.
                                              {
    if (&str != inner) {
      // LOG(INFO, "Move(assign) SimpleString");
      if (inner)
        delete[] inner;
      len = str.len;
      inner = str.inner;
      str.len = 0;
      str.inner = nullptr;
    }
    return *this;
  }
References inner, and len.
SimpleString& SimpleString::operator= (SimpleString const & str) [inline]
Copy the provided SimpleString to this one.
Definition at line 92 of file SimpleString.hpp.
                                                   {
    if (&str != inner) {
      // LOG(INFO, "Assigning SimpleString");
      if (inner)
        delete[] inner;
      init(str.inner);
    }
    return *this;
  }
References init(), and inner.
bool SimpleString::operator== (const char * str) const [inline]
Equality with cstring. Utilizes std::strcmp.
Definition at line 119 of file SimpleString.hpp.
                                         {
    if (length() != strlen(str))
      return false;
    return strcmp(inner, str) == 0;
  }
References inner, and length().
bool SimpleString::operator== (SimpleString const & str) const [inline]
Equality with SimpleString. Utilizes std::strcmp.
Definition at line 112 of file SimpleString.hpp.
                                                 {
    if (length() != str.length())
      return false;
    return strcmp(inner, str.inner) == 0;
  }
References inner, and length().
bool SimpleString::operator> (SimpleString const & other) const [inline]
Is this string greater than another? Utilizes std::strcmp.
Definition at line 132 of file SimpleString.hpp.
                                                  {
    return strcmp(inner, other.get()) > 0;
  }
References get(), and inner.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, SimpleString str) [friend]
Passes the underlying char* to the provided stream.
Definition at line 158 of file SimpleString.hpp.
                                                                   {
    return out << str.inner;
  }
Member Data Documentation
char* SimpleString::inner = nullptr [private]
Definition at line 21 of file SimpleString.hpp.
Referenced by get(), init(), operator&(), operator=(), operator==(), operator>(), SimpleString(), and ~SimpleString().
size_t SimpleString::len = 0 [private]
Definition at line 22 of file SimpleString.hpp.
Referenced by init(), length(), operator=(), and SimpleString().
Author
Generated automatically by Doxygen for Traveller's App from the source code.