Stack< A >
NAME
Stack< A > - An implementation of a stack leveraging ArrayList. Basically an ArrayList but most methods are private and some others exist with different names.
SYNOPSIS
#include <Stack.hpp>
Inherits ArrayList< A >.
Public Member Functions
std::unique_ptr< ArrayList< A > > asList ()
Convert to list.
std::unique_ptr< Nullable< A > > peek () const
Peek at the top element of the stack.
void push (A const &elem)
Push an element onto the stack.
void pushAll (Stack< A > const &stack)
Push multiple elements on top of the stack.
Stack ()
Stack (int capacity)
Stack (Stack< A > const &stack)
Additional Inherited Members
Detailed Description
template<class A>
class Stack< A >"
An implementation of a stack leveraging ArrayList. Basically an ArrayList but most methods are private and some others exist with different names.
Definition at line 11 of file Stack.hpp.
Constructor & Destructor Documentation
template<class A > Stack< A >::Stack (Stack< A > const & stack) [inline]
Definition at line 16 of file Stack.hpp.
: ArrayList<A>(stack) {}
template<class A > Stack< A >::Stack (int capacity) [inline]
Definition at line 18 of file Stack.hpp.
: ArrayList<A>(capacity) {}
template<class A > Stack< A >::Stack () [inline]
Definition at line 20 of file Stack.hpp.
: ArrayList<A>() {}
Member Function Documentation
template<class A > std::unique_ptr<ArrayList<A> > Stack< A >::asList () [inline]
Convert to list.
Definition at line 32 of file Stack.hpp.
                                       {
    std::unique_ptr<ArrayList<A>> list =
        std::make_unique<ArrayList<A>>(ArrayList<A>::capacity());
    for (int i = 0; i < length(); i++) {
      list->append(ArrayList<A>::get(i));
    }
    return list;
  }
References ArrayList< A >::capacity(), and ArrayList< A >::length().
template<class A > std::unique_ptr<Nullable<A> > Stack< A >::peek () const [inline]
Peek at the top element of the stack.
Definition at line 42 of file Stack.hpp.
{ return (*this)[length() - 1]; }
References ArrayList< A >::length().
template<class A > void Stack< A >::push (A const & elem) [inline]
Push an element onto the stack.
Definition at line 23 of file Stack.hpp.
{ this->append(elem); }
References ArrayList< A >::append().
Referenced by Stack< A >::pushAll().
template<class A > void Stack< A >::pushAll (Stack< A > const & stack) [inline]
Push multiple elements on top of the stack.
Definition at line 26 of file Stack.hpp.
                                      {
    for (unsigned i = 0; i < stack.length(); i++)
      push(stack.get(i));
  }
References ArrayList< A >::get(), ArrayList< A >::length(), and Stack< A >::push().
Author
Generated automatically by Doxygen for Traveller's App from the source code.