Travel::LoginInterpreter
NAME
Travel::LoginInterpreter - Interprets all commands in the ATOPEN ScannerContext.
SYNOPSIS
#include <LoginInterpreter.hpp>
Inherits Interpreter< TravelState >.
Public Member Functions
Interpreter (std::shared_ptr< ArrayList< Token >> _tokens)
Inherits the constructors of Interpreter.
bool parse (TravelState &state) override
Parses the provided tokens into the given Travel::TravelState.
Private Member Functions
bool login (TravelState &state)
Interprets the login command.
bool reg (TravelState &state)
Interprets the register command.
Additional Inherited Members
Detailed Description
Interprets all commands in the ATOPEN ScannerContext.
Definition at line 23 of file LoginInterpreter.hpp.
Member Function Documentation
Interpreter< Controller >::Interpreter [inline], [explicit]
Inherits the constructors of Interpreter.
Definition at line 83 of file Interpreter.hpp.
      : tokens(_tokens) {}
bool Travel::LoginInterpreter::login (TravelState & state) [private]
Interprets the login command.
Definition at line 5 of file LoginInterpreter.cpp.
                                               {
  auto user = consume(TokenType::STRING, "Expected username");
  if (matches(TokenType::STRING) || matches(TokenType::NUMBER)) {
    auto password = next();
    return state.login(user.lexeme, password.lexeme);
  } else {
    error(peek().line, "Expected password");
    return false;
  }
}
References Interpreter< TravelState >::consume(), Interpreter< TravelState >::error(), Travel::TravelState::login(), Interpreter< TravelState >::matches(), Interpreter< TravelState >::next(), NUMBER, Interpreter< TravelState >::peek(), and STRING.
Referenced by parse().
bool Travel::LoginInterpreter::parse (TravelState & state) [override]
Parses the provided tokens into the given Travel::TravelState.
Definition at line 28 of file LoginInterpreter.cpp.
                                               {
  errorflag = false;
  while (!isAtEnd()) {
    try {
      switch (next().t) {
      case TokenType::LOGIN:
        return !login(state);
        break;
      case TokenType::REGISTER:
        return !reg(state);
        break;
      case TokenType::NUMBER:
        errorflag = true;
        std::cerr << "(Line " << prev().line << ") "
                  << "Unexpected Number -> " << prev().lexeme << std::endl;
        break;
      case TokenType::DATE:
        errorflag = true;
        std::cerr << "(Line " << prev().line << ") "
                  << "Unexpected Date -> " << prev().lexeme << std::endl;
        break;
      case TokenType::ERROR:
        errorflag = true;
        std::cerr << "(Line " << prev().line << ") "
                  << "Parsing error: " << prev().lexeme << std::endl;
        break;
      case TokenType::EOF_T:
        return true;
        break;
      default:
        errorflag = true;
        std::cerr << "(Line " << prev().line << ") "
                  << "Unexpected String -> " << prev().lexeme << std::endl;
        break;
      }
    } catch (NoValueException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
    } catch (InvalidArgumentException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
    } catch (ReachedEndOfStreamException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
      return true;
    } catch (WrongTokenTypeException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
      while (peek().t == TokenType::STRING || peek().t == TokenType::NUMBER ||
             peek().t == TokenType::DATE || peek().t == TokenType::ERROR) {
        Token n = next();
        if (n.t == TokenType::ERROR) {
          std::cerr << "Error: " << n.lexeme << std::endl;
        }
      }
    }
  }
  return true;
}
References DATE, EOF_T, ERROR, Interpreter< TravelState >::errorflag, Interpreter< TravelState >::isAtEnd(), Token::lexeme, Token::line, LOGIN, login(), Interpreter< TravelState >::next(), NUMBER, Interpreter< TravelState >::peek(), Interpreter< TravelState >::prev(), reg(), REGISTER, STRING, Token::t, WrongTokenTypeException::what(), NoValueException::what(), ReachedEndOfStreamException::what(), and InvalidArgumentException::what().
Referenced by main().
bool Travel::LoginInterpreter::reg (TravelState & state) [private]
Interprets the register command.
Definition at line 16 of file LoginInterpreter.cpp.
                                             {
  auto email = consume(TokenType::STRING, "Expected email");
  auto user = consume(TokenType::STRING, "Expected username");
  if (matches(TokenType::STRING) || matches(TokenType::NUMBER)) {
    auto password = next();
    return state.uregister(email.lexeme, user.lexeme, password.lexeme);
  } else {
    error(peek().line, "Expected password");
    return false;
  }
}
References Interpreter< TravelState >::consume(), Interpreter< TravelState >::error(), Interpreter< TravelState >::matches(), Interpreter< TravelState >::next(), NUMBER, Interpreter< TravelState >::peek(), STRING, and Travel::TravelState::uregister().
Referenced by parse().
Author
Generated automatically by Doxygen for Traveller's App from the source code.