Travel::Date
NAME
Travel::Date - Stores a date (in ISO 8601) and has some useful methods for working with dates.
SYNOPSIS
#include <Date.hpp>
Public Member Functions
Date ()
Constructs a date with the current date.
Date (const char str[11])
Constructs a date from a string representing a date in the ISO 8601 format.
Date (int year, int month, int day)
Constructs a date with the provided arguments.
int daysBetween (const Date &date) const
Returns the days between this date and the provided date.
int daysSince1900 () const
Returns the days between this date and 1900-01-01.
int getDay () const
Returns the day represented by this Date.
int getMonth () const
Returns the month represented by this Date.
void getString (char *(&str)) const
Converts this date to the ISO 8601 format.
void getString (char(&str)[11]) const
Converts this date to the ISO 8601 format.
int getYear () const
Returns the year represented by this Date.
bool operator!= (Date const &other) const
int operator- (Date const &other) const
returns the signed difference in days between this date and another
bool operator< (Date const &other) const
bool operator<= (Date const &other) const
bool operator== (Date const &other) const
bool operator> (Date const &other) const
bool operator>= (Date const &other) const
void print () const
Prints the date in the ISO 8601 format ( [year]-[month]-[day] )
void println () const
Prints the date in the ISO 8601 format ( [year]-[month]-[day] ) and a newline.
Static Public Member Functions
static int currentDay ()
Returns the current day.
static int currentMonth ()
Returns the current month.
static int currentYear ()
Returns the current year.
static int daysBetween (const Date &start, const Date &end)
Returns the days between two dates.
static int daysOfMonth (int month, int year)
Returns the amount of days in a month.
static int daysSince1900 (const Date &date)
Returns the days between 1900-01-01 to date.
static Date fromString (const char str[11])
Converts a string representing a date in the ISO 8601 format into a Date instance.
static bool isLeapYear (int year)
Checks if the provided year is a leap year.
static Date today ()
Returns the current date.
Private Member Functions
void setDay (int _day)
void setMonth (int _month)
void setYear (int _year)
void validate ()
Makes sure the date is valid.
Private Attributes
int day
int month
int year
Friends
std::ostream & operator<< (std::ostream &out, const Date &date)
std::istream & operator>> (std::istream &in, Date &date)
Detailed Description
Stores a date (in ISO 8601) and has some useful methods for working with dates.
Definition at line 15 of file Date.hpp.
Constructor & Destructor Documentation
Travel::Date::Date (int year, int month, int day)
Constructs a date with the provided arguments.
Parameters
year the year
month the month
day the day
Definition at line 33 of file Date.cpp.
                                       {
  this->day = day;
  this->month = month;
  this->year = year;
  validate();
}
References day, month, validate(), and year.
Travel::Date::Date ()
Constructs a date with the current date.
Definition at line 123 of file Date.cpp.
           {
  year = currentYear();
  month = currentMonth();
  day = currentDay();
}
References currentDay(), currentMonth(), currentYear(), day, month, and year.
Travel::Date::Date (const char str[11])
Constructs a date from a string representing a date in the ISO 8601 format.
Parameters
str the string to convert from
Definition at line 106 of file Date.cpp.
                             {
  sscanf(str, "%d-%d-%d", &year, &month, &day);
  validate();
  // char s_year[5];
  // strncpy(s_year, str + 0, 4);
  // s_year[4] = '\0';
  // char s_month[3];
  // strncpy(s_month, str + 5, 2);
  // s_month[2] = '\0';
  // char s_day[3];
  // strncpy(s_day, str + 8, 2);
  // s_day[2] = '\0';
  // year = atoi(s_year);
  // month = atoi(s_month);
  // day = atoi(s_day);
}
References day, month, validate(), and year.
Member Function Documentation
int Travel::Date::currentDay () [static]
Returns the current day.
Returns
the current day
Definition at line 92 of file Date.cpp.
                     {
  time_t now = time(nullptr);
  tm *ltm = localtime(&now);
  return ltm->tm_mday;
}
Referenced by Date().
int Travel::Date::currentMonth () [static]
Returns the current month.
Returns
the current month
Definition at line 86 of file Date.cpp.
                       {
  time_t now = time(nullptr);
  tm *ltm = localtime(&now);
  return ltm->tm_mon + 1;
}
Referenced by Date().
int Travel::Date::currentYear () [static]
Returns the current year.
Returns
the current year
Definition at line 80 of file Date.cpp.
                      {
  time_t now = time(nullptr);
  tm *ltm = localtime(&now);
  return ltm->tm_year + 1900;
}
Referenced by Date().
int Travel::Date::daysBetween (const Date & date) const
Returns the days between this date and the provided date.
Parameters
date the other date
Returns
the days between the two dates
Definition at line 149 of file Date.cpp.
                                            {
  return std::abs(daysSince1900(date) - daysSince1900()) + 1;
}
References daysSince1900().
Referenced by daysBetween().
int Travel::Date::daysBetween (const Date & start, const Date & end) [static]
Returns the days between two dates.
Parameters
start the first date
end the second date
Returns
thr days between the two dates
Definition at line 131 of file Date.cpp.
                                                        {
  return start.daysBetween(end);
}
References daysBetween().
int Travel::Date::daysOfMonth (int month, int year) [static]
Returns the amount of days in a month.
Parameters
month the month for which to check
year the year for which to check
Returns
the days in the provided month during the provided year.
Definition at line 42 of file Date.cpp.
                                         {
  int days = 0;
  switch (month) {
  case 2:
    days += Date::isLeapYear(year) ? 29 : 28;
    break;
  case 1:
  case 3:
  case 5:
  case 7:
  case 8:
  case 10:
  case 12:
    days += 1;
  case 4:
  case 6:
  case 9:
  case 11:
    days += 30;
    break;
  default:
    break;
  }
  return days;
}
References isLeapYear(), month, and year.
Referenced by daysSince1900(), and validate().
int Travel::Date::daysSince1900 () const
Returns the days between this date and 1900-01-01.
Returns
the days since 1900
Definition at line 137 of file Date.cpp.
                              {
  int days = 0;
  for (int i = 1900; i < getYear(); i++) {
    days += Date::isLeapYear(i) ? 366 : 365;
  }
  for (int i = 1; i < getMonth(); i++) {
    days += Date::daysOfMonth(i, getYear());
  }
  days += day;
  return days;
}
References day, daysOfMonth(), getMonth(), getYear(), and isLeapYear().
Referenced by daysBetween(), daysSince1900(), operator-(), and operator>().
int Travel::Date::daysSince1900 (const Date & date) [static]
Returns the days between 1900-01-01 to date.
Parameters
date the date to check
Returns
the days since 1900
Definition at line 135 of file Date.cpp.
{ return date.daysSince1900(); }
References daysSince1900().
Date Travel::Date::fromString (const char str[11]) [static]
Converts a string representing a date in the ISO 8601 format into a Date instance.
Parameters
str the string to convert to date
Returns
the converted date
Definition at line 129 of file Date.cpp.
{ return {str}; }
int Travel::Date::getDay () const [inline]
Returns the day represented by this Date.
Returns
the day
Definition at line 129 of file Date.hpp.
{ return day; }
References day.
Referenced by getString(), and operator==().
int Travel::Date::getMonth () const [inline]
Returns the month represented by this Date.
Returns
the month
Definition at line 135 of file Date.hpp.
{ return month; }
References month.
Referenced by daysSince1900(), getString(), and operator==().
void Travel::Date::getString (char *& str) const
Converts this date to the ISO 8601 format.
Parameters
str the string to which to write
Definition at line 102 of file Date.cpp.
                                       {
  sprintf(str, "%04d-%02d-%02d", getYear(), getMonth(), getDay());
}
References getDay(), getMonth(), and getYear().
void Travel::Date::getString (char(&) str[11]) const
Converts this date to the ISO 8601 format.
Parameters
str the string to which to write
Definition at line 98 of file Date.cpp.
                                          {
  sprintf(str, "%04d-%02d-%02d", getYear(), getMonth(), getDay());
}
References getDay(), getMonth(), and getYear().
Referenced by User::addVisit(), Travel::operator<<(), and print().
int Travel::Date::getYear () const [inline]
Returns the year represented by this Date.
Returns
the year
Definition at line 141 of file Date.hpp.
{ return year; }
References year.
Referenced by daysSince1900(), getString(), and operator==().
bool Travel::Date::isLeapYear (int year) [static]
Checks if the provided year is a leap year.
Parameters
year the year which to check.
Returns
is the provided year a leap year.
Definition at line 68 of file Date.cpp.
                              {
  if (year % 4 == 0) {
    if (year % 100 == 0) {
      return year % 400 == 0;
    } else {
      return true;
    }
  } else {
    return false;
  }
}
References year.
Referenced by daysOfMonth(), and daysSince1900().
bool Travel::Date::operator!= (Date const & other) const
Parameters
other the other date
Returns
are the two dates different
Definition at line 205 of file Date.cpp.
{ return !(*this == other); }
int Travel::Date::operator- (Date const & other) const
returns the signed difference in days between this date and another
Parameters
other the other date
Returns
the unsigned difference in days
Definition at line 212 of file Date.cpp.
                                           {
  return daysSince1900() - other.daysSince1900();
}
References daysSince1900().
bool Travel::Date::operator< (Date const & other) const
Parameters
other the other date
Returns
is this date less than the other date
Definition at line 201 of file Date.cpp.
{ return !(*this >= other); }
bool Travel::Date::operator<= (Date const & other) const
Parameters
other the other date
Returns
is this date less than or equal to the other date
Definition at line 203 of file Date.cpp.
{ return !(*this > other); }
bool Travel::Date::operator== (Date const & other) const
Parameters
other the other date
Returns
are the two dates equal
Definition at line 207 of file Date.cpp.
                                             {
  return other.getYear() == getYear() && other.getMonth() == getMonth() &&
         other.getDay() == getDay();
}
References getDay(), getMonth(), and getYear().
bool Travel::Date::operator> (Date const & other) const
Parameters
other the other date
Returns
is this date greater than the other date
Definition at line 193 of file Date.cpp.
                                            {
  return daysSince1900() > other.daysSince1900();
}
References daysSince1900().
bool Travel::Date::operator>= (Date const & other) const
Parameters
other the other date
Returns
is this date greater than or equal to the other date
Definition at line 197 of file Date.cpp.
                                             {
  return *this > other || *this == other;
}
void Travel::Date::print () const
Prints the date in the ISO 8601 format ( [year]-[month]-[day] )
Definition at line 216 of file Date.cpp.
                       {
  char str[11];
  getString(str);
  std::cout << str;
}
References getString().
Referenced by println().
void Travel::Date::println () const
Prints the date in the ISO 8601 format ( [year]-[month]-[day] ) and a newline.
Definition at line 222 of file Date.cpp.
                         {
  print();
  std::cout << std::endl;
}
References print().
void Travel::Date::setDay (int _day) [inline], [private]
Definition at line 25 of file Date.hpp.
{ day = _day; }
References day.
Referenced by Travel::operator>>().
void Travel::Date::setMonth (int _month) [inline], [private]
Definition at line 23 of file Date.hpp.
{ month = _month; }
References month.
Referenced by Travel::operator>>().
void Travel::Date::setYear (int _year) [inline], [private]
Definition at line 21 of file Date.hpp.
{ year = _year; }
References year.
Referenced by Travel::operator>>().
Date Travel::Date::today () [static]
Returns the current date.
Returns
the current date
Definition at line 40 of file Date.cpp.
{ return Date{}; }
void Travel::Date::validate () [private]
Makes sure the date is valid.
Exceptions
InvalidArgumentException if it isn't valid.
Definition at line 16 of file Date.cpp.
                    {
  if (month > 12) {
    throw InvalidArgumentException("Month cannot be greater than 12.");
  } else if (month < 1) {
    throw InvalidArgumentException("Month cannot be less than 1.");
  }
  int dm = daysOfMonth(month, year);
  if (day < 1) {
    throw InvalidArgumentException("Day cannot be less than 1.");
  } else if (day > dm) {
    throw InvalidArgumentException(
        "Month cannot have more than that many days");
  }
}
References day, daysOfMonth(), month, and year.
Referenced by Date().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Date & date) [friend]
Definition at line 153 of file Date.cpp.
                                                          {
  char str[11];
  date.getString(str);
  out << str;
  return out;
}
std::istream& operator>> (std::istream & in, Date & date) [friend]
Definition at line 164 of file Date.cpp.
                                                   {
  int year;
  int month;
  int day;
  in >> year;
  if (!isDash(in)) {
    in.setstate(std::ios::failbit);
    return in;
  }
  in >> month;
  if (!isDash(in)) {
    in.setstate(std::ios::failbit);
    return in;
  }
  in >> day;
  date.setYear(year);
  date.setMonth(month);
  date.setDay(day);
  return in;
}
Member Data Documentation
int Travel::Date::day [private]
Definition at line 19 of file Date.hpp.
Referenced by Date(), daysSince1900(), getDay(), setDay(), and validate().
int Travel::Date::month [private]
Definition at line 18 of file Date.hpp.
Referenced by Date(), daysOfMonth(), getMonth(), setMonth(), and validate().
int Travel::Date::year [private]
Definition at line 17 of file Date.hpp.
Referenced by Date(), daysOfMonth(), getYear(), isLeapYear(), setYear(), and validate().
Author
Generated automatically by Doxygen for Traveller's App from the source code.