Travel::HTLInterpreter
NAME
Travel::HTLInterpreter - An interpreter for general commands.
SYNOPSIS
#include <HTLInterpreter.hpp>
Inherits Interpreter< TravelState >.
Public Member Functions
Interpreter (std::shared_ptr< ArrayList< Token >> _tokens)
Inherits the constructors of Interpreter.
bool parse (TravelState &state) override
Parses the provided tokens into the given Travel::TravelState.
Private Member Functions
void cfriend (TravelState &state)
Interprets all commands in the friend prefix.
void destination (TravelState &state)
Interprets all commands in the destination prefix.
void destinationComments (TravelState &state)
Interprets the destination comments command.
void destinationExists (TravelState &state)
Interprets the destination exists command.
void destinationRating (TravelState &state)
Interprets the destination rating command.
void destinationVisited (TravelState &state)
Interprets the destination visited command.
void friendAdd (TravelState &state)
Interprets the friend add command.
void friendList (TravelState &state)
Interprets the friend list command.
void friendRemove (TravelState &state)
Interprets the friend remove command.
void friendVisited (TravelState &state)
Interprets the friend visited command.
bool general (TravelState &state)
Interprets all commands not in a prefix.
void visit (TravelState &state)
Starts visit mode.
Additional Inherited Members
Detailed Description
An interpreter for general commands.
Definition at line 24 of file HTLInterpreter.hpp.
Member Function Documentation
void Travel::HTLInterpreter::cfriend (TravelState & state) [private]
Interprets all commands in the friend prefix.
Definition at line 112 of file HTLInterpreter.cpp.
                                               {
  if (isAtEnd()) {
    throw ReachedEndOfStreamException();
  }
  switch (next().t) {
  case TokenType::ADD:
    friendAdd(state);
    break;
  case TokenType::REMOVE:
    friendRemove(state);
    break;
  case TokenType::LIST:
    friendList(state);
    break;
  case TokenType::VISITED:
    friendVisited(state);
    break;
  case TokenType::EOF_T:
    std::cout << "Friend is a command prefix. It doesn't do anything by "
                 "itself."
              << std::endl;
    break;
  case TokenType::NUMBER:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Number -> " << prev().lexeme << std::endl;
    break;
  case TokenType::DATE:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Date -> " << prev().lexeme << std::endl;
    break;
  case TokenType::ERROR:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Parsing error: " << prev().lexeme << std::endl;
    break;
  default:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected String -> " << prev().lexeme << std::endl;
    break;
  }
}
References ADD, DATE, EOF_T, ERROR, Interpreter< TravelState >::errorflag, friendAdd(), friendList(), friendRemove(), friendVisited(), Interpreter< TravelState >::isAtEnd(), Token::lexeme, Token::line, LIST, Interpreter< TravelState >::next(), NUMBER, Interpreter< TravelState >::prev(), REMOVE, and VISITED.
Referenced by parse().
void Travel::HTLInterpreter::destination (TravelState & state) [private]
Interprets all commands in the destination prefix.
Definition at line 158 of file HTLInterpreter.cpp.
                                                   {
  if (isAtEnd())
    throw ReachedEndOfStreamException();
  switch (next().t) {
  case TokenType::EXISTS:
    destinationExists(state);
    break;
  case TokenType::RATING:
    destinationRating(state);
    break;
  case TokenType::COMMENTS:
    destinationComments(state);
    break;
  case TokenType::VISITED:
    destinationVisited(state);
    break;
  case TokenType::EOF_T:
    std::cout << "Destination is a command prefix. It doesn't do anything"
                 " by itself."
              << std::endl;
    break;
  case TokenType::NUMBER:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Number -> " << prev().lexeme << std::endl;
    break;
  case TokenType::DATE:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Date -> " << prev().lexeme << std::endl;
    break;
  case TokenType::ERROR:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Parsing error: " << prev().lexeme << std::endl;
    break;
  default:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected String -> " << prev().lexeme << std::endl;
    break;
  }
}
References COMMENTS, DATE, destinationComments(), destinationExists(), destinationRating(), destinationVisited(), EOF_T, ERROR, Interpreter< TravelState >::errorflag, EXISTS, Interpreter< TravelState >::isAtEnd(), Token::lexeme, Token::line, Interpreter< TravelState >::next(), NUMBER, Interpreter< TravelState >::prev(), RATING, and VISITED.
Referenced by destinationComments(), destinationExists(), destinationRating(), destinationVisited(), friendVisited(), parse(), and visit().
void Travel::HTLInterpreter::destinationComments (TravelState & state) [private]
Interprets the destination comments command.
Definition at line 96 of file HTLInterpreter.cpp.
                                                           {
  auto destination = consume(TokenType::STRING, "Expected destination name.");
  std::cout << "Showing comments for destination " << destination.lexeme << "."
            << std::endl;
  state.destinationComments(destination.lexeme);
}
References Interpreter< TravelState >::consume(), destination(), Travel::TravelState::destinationComments(), and STRING.
Referenced by destination().
void Travel::HTLInterpreter::destinationExists (TravelState & state) [private]
Interprets the destination exists command.
Definition at line 78 of file HTLInterpreter.cpp.
                                                         {
  auto destination = consume(TokenType::STRING, "Expected destination name.");
  std::cout << "Checking if destination " << destination.lexeme << " exists."
            << std::endl;
  if (state.destinationExists(destination.lexeme)) {
    std::cout << "It does." << std::endl;
  } else {
    std::cout << "It doesn't." << std::endl;
  }
}
References Interpreter< TravelState >::consume(), destination(), Travel::TravelState::destinationExists(), and STRING.
Referenced by destination().
void Travel::HTLInterpreter::destinationRating (TravelState & state) [private]
Interprets the destination rating command.
Definition at line 89 of file HTLInterpreter.cpp.
                                                         {
  auto destination = consume(TokenType::STRING, "Expected destination name.");
  std::cout << "Showing average rating for destination " << destination.lexeme
            << "." << std::endl;
  state.destinationRating(destination.lexeme);
}
References Interpreter< TravelState >::consume(), destination(), Travel::TravelState::destinationRating(), and STRING.
Referenced by destination().
void Travel::HTLInterpreter::destinationVisited (TravelState & state) [private]
Interprets the destination visited command.
Definition at line 103 of file HTLInterpreter.cpp.
                                                          {
  auto destination = consume(TokenType::STRING, "Expected destination name.");
  auto user = consume(TokenType::STRING, "Expected user name.");
  std::cout << "Checking if " << user.lexeme << " has visited "
            << destination.lexeme << std::endl;
  state.userVisited(destination.lexeme, user.lexeme);
}
References Interpreter< TravelState >::consume(), destination(), STRING, and Travel::TravelState::userVisited().
Referenced by destination().
void Travel::HTLInterpreter::friendAdd (TravelState & state) [private]
Interprets the friend add command.
Definition at line 46 of file HTLInterpreter.cpp.
                                                 {
  auto name = consume(TokenType::STRING, "Expected user name.");
  std::cout << "Adding " << name.lexeme << " to friend's list." << std::endl;
  state.friendAdd(name.lexeme);
}
References Interpreter< TravelState >::consume(), Travel::TravelState::friendAdd(), and STRING.
Referenced by cfriend().
void Travel::HTLInterpreter::friendList (TravelState & state) [private]
Interprets the friend list command.
Definition at line 59 of file HTLInterpreter.cpp.
                                                  {
  std::cout << "Listing friends." << std::endl;
  state.friendList();
}
References Travel::TravelState::friendList().
Referenced by cfriend().
void Travel::HTLInterpreter::friendRemove (TravelState & state) [private]
Interprets the friend remove command.
Definition at line 52 of file HTLInterpreter.cpp.
                                                    {
  auto name = consume(TokenType::STRING, "Expected user name.");
  std::cout << "Removing " << name.lexeme << " from friend's list."
            << std::endl;
  state.friendRemove(name.lexeme);
}
References Interpreter< TravelState >::consume(), Travel::TravelState::friendRemove(), and STRING.
Referenced by cfriend().
void Travel::HTLInterpreter::friendVisited (TravelState & state) [private]
Interprets the friend visited command.
Definition at line 64 of file HTLInterpreter.cpp.
                                                     {
  auto destination = consume(TokenType::STRING, "Expected destination name.");
  if (matches(TokenType::STRING)) {
    auto user = next();
    std::cout << "Checking if " << user.lexeme << " has visited "
              << destination.lexeme << std::endl;
    state.friendVisited(destination.lexeme, user.lexeme);
  } else {
    std::cout << "Showing all friends who have visited " << destination.lexeme
              << std::endl;
    state.friendVisited(destination.lexeme);
  }
}
References Interpreter< TravelState >::consume(), destination(), Travel::TravelState::friendVisited(), Interpreter< TravelState >::matches(), Interpreter< TravelState >::next(), and STRING.
Referenced by cfriend().
bool Travel::HTLInterpreter::general (TravelState & state) [private]
Interprets all commands not in a prefix.
Definition at line 11 of file HTLInterpreter.cpp.
                                               {
  switch (next().t) {
  case TokenType::HELP:
    CommandList::getCommandList()->printCommandsWithDescription();
    break;
  case TokenType::EXIT:
    return false;
    break;
  case TokenType::NUMBER:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Number -> " << prev().lexeme << std::endl;
    break;
  case TokenType::DATE:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Date -> " << prev().lexeme << std::endl;
    break;
  case TokenType::ERROR:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Parsing error: " << prev().lexeme << std::endl;
    break;
  case TokenType::EOF_T:
    return true;
    break;
  default:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected String -> " << prev().lexeme << std::endl;
    break;
  }
  return true;
}
References DATE, EOF_T, ERROR, Interpreter< TravelState >::errorflag, EXIT, Travel::CommandList::getCommandList(), HELP, Token::lexeme, Token::line, Interpreter< TravelState >::next(), NUMBER, Interpreter< TravelState >::prev(), and Travel::CommandList::printCommandsWithDescription().
Referenced by parse().
Interpreter< Controller >::Interpreter [inline], [explicit]
Inherits the constructors of Interpreter.
Definition at line 83 of file Interpreter.hpp.
      : tokens(_tokens) {}
bool Travel::HTLInterpreter::parse (TravelState & state) [override]
Parses the provided tokens into the given Travel::TravelState.
Definition at line 220 of file HTLInterpreter.cpp.
                                             {
  errorflag = false;
  while (!isAtEnd()) {
    try {
      if (matches(TokenType::FRIEND)) {
        LOG(INFO, "Friend prefix");
        next();
        cfriend(state);
      } else if (matches(TokenType::DESTINATION)) {
        LOG(INFO, "Destination prefix");
        next();
        destination(state);
      } else if (matches(TokenType::VISIT)) {
        LOG(INFO, "Destination prefix");
        next();
        visit(state);
      } else {
        LOG(INFO, "Generic commandline");
        if (!general(state))
          return false;
      }
    } catch (NoValueException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
    } catch (InvalidArgumentException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
    } catch (ReachedEndOfStreamException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
      return true;
    } catch (WrongTokenTypeException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
      while (peek().t == TokenType::STRING || peek().t == TokenType::NUMBER ||
             peek().t == TokenType::DATE || peek().t == TokenType::ERROR) {
        Token n = next();
        if (n.t == TokenType::ERROR) {
          std::cerr << "Error: " << n.lexeme << std::endl;
        }
      }
    }
  }
  return true;
}
References cfriend(), DATE, destination(), DESTINATION, ERROR, Interpreter< TravelState >::errorflag, FRIEND, general(), Interpreter< TravelState >::isAtEnd(), Token::lexeme, LOG, Interpreter< TravelState >::matches(), Interpreter< TravelState >::next(), NUMBER, Interpreter< TravelState >::peek(), STRING, Token::t, VISIT, visit(), WrongTokenTypeException::what(), NoValueException::what(), ReachedEndOfStreamException::what(), and InvalidArgumentException::what().
Referenced by main().
void Travel::HTLInterpreter::visit (TravelState & state) [private]
Starts visit mode.
Definition at line 203 of file HTLInterpreter.cpp.
                                             {
  Travel::Scanner sc(ScannerContext::VISIT, &std::cin,
                     Travel::CommandList::getCommandList());
  auto destination = consume(TokenType::STRING, "Expected destination name.");
  VisitBuilder vb;
  vb.destination(destination.lexeme);
  bool run = true;
  while (run) {
    std::cout << ">>" << destination.lexeme << "$ ";
    auto tokens = sc.scanNext();
    // tokens->foreach([](Token const& t){ std::cout<<t<<std::endl;});
    Travel::VisitInterpreter interpreter{tokens};
    run = interpreter.parse(vb);
  }
  state.save(vb);
}
References Interpreter< TravelState >::consume(), destination(), Travel::VisitBuilder::destination(), Travel::CommandList::getCommandList(), Travel::TravelState::save(), Travel::Scanner::scanNext(), STRING, Interpreter< TravelState >::tokens, and VISIT.
Referenced by parse().
Author
Generated automatically by Doxygen for Traveller's App from the source code.