Travel::CommandList
NAME
Travel::CommandList - This class represents a list of unique, reserved keywords for the scanner.
SYNOPSIS
#include <CommandList.hpp>
Public Member Functions
CommandList ()
CommandList (CommandList const &other)
std::unique_ptr< Nullable< ScannerContext > > contextFor (TokenType tokenType)
Returns a pointer to a NotNull of the ScannerContext associated with the given TokenType if such exists and Null otherwise.
bool isCommand (SimpleString const &name)
Returns true if there is a registered command with the provided name.
bool isCommand (TokenType tokenType)
Returns true if there is a registered command with the provided TokenType.
CommandList & operator= (CommandList const &other)
void printCommandsWithDescription ()
Prints the registered commands along with their description.
void registerCommand (SimpleString &&name, TokenType tokenType, ScannerContext ctx, const char *&&descr)
Registers the command with the given information.
void registerCommand (SimpleString const &name, TokenType tokenType, ScannerContext ctx, const char *descr)
Registers the command with the given information.
std::unique_ptr< Nullable< TokenType > > tokenFor (SimpleString const &name)
Returns a pointer to a NotNull of the TokenType associated with the given name if such exists and Null otherwise.
Static Public Member Functions
static CommandList * getCommandList ()
Returns the global command list.
static void setCommandList (CommandList *cl)
Sets the global command list.
Private Member Functions
void copy (CommandList const &other)
Convenience method for copying another CommandList to this one.
Private Attributes
HashMap< TokenType, ScannerContext > commandMap
HashMap< SimpleString, const char * > nameToDescr
HashMap< SimpleString, TokenType > nameToToken
Static Private Attributes
static CommandList * globalCommandList = nullptr
A convenience value so CommandList doesn't need to be passed around as much.
Detailed Description
This class represents a list of unique, reserved keywords for the scanner.
It stores their text representation, their corresponding TokenType and ScannerContext, as well as a description for the help command
Definition at line 18 of file CommandList.hpp.
Constructor & Destructor Documentation
Travel::CommandList::CommandList ()
Definition at line 13 of file CommandList.cpp.
{ LOG(INFO, "Create CommandList."); }
References LOG.
Travel::CommandList::CommandList (CommandList const & other)
Definition at line 15 of file CommandList.cpp.
                                                       {
  if (&other != this) {
    copy(other);
  }
}
Member Function Documentation
std::unique_ptr< Nullable< ScannerContext > > Travel::CommandList::contextFor (TokenType tokenType)
Returns a pointer to a NotNull of the ScannerContext associated with the given TokenType if such exists and Null otherwise.
Parameters
tokenType the tokenType to find the context for
Returns
the context
Definition at line 86 of file CommandList.cpp.
                                                 {
  LOG(VERBOSE, "Get context for token type");
  return commandMap.get(tokenType);
}
References LOG.
void Travel::CommandList::copy (CommandList const & other) [private]
Convenience method for copying another CommandList to this one.
Definition at line 6 of file CommandList.cpp.
                                                     {
  LOG(INFO, "Copying CommandList instance.");
  nameToToken = other.nameToToken;
  commandMap = other.commandMap;
  nameToDescr = other.nameToDescr;
}
References commandMap, LOG, nameToDescr, and nameToToken.
static CommandList* Travel::CommandList::getCommandList () [inline], [static]
Returns the global command list.
Returns
the global command list
Definition at line 40 of file CommandList.hpp.
                                       {
    return CommandList::globalCommandList;
  }
References globalCommandList.
Referenced by Travel::HTLInterpreter::general(), Travel::VisitInterpreter::general(), and Travel::HTLInterpreter::visit().
bool Travel::CommandList::isCommand (SimpleString const & name)
Returns true if there is a registered command with the provided name.
Parameters
name the name to check for
Returns
is there a registered command with that name
Definition at line 81 of file CommandList.cpp.
                                                          {
  return nameToToken.contains(name);
}
bool Travel::CommandList::isCommand (TokenType tokenType)
Returns true if there is a registered command with the provided TokenType.
Parameters
tokenType the TokenType to check for
Returns
is there a registered command with that TokenType
Definition at line 77 of file CommandList.cpp.
                                                     {
  return commandMap.contains(tokenType);
}
Travel::CommandList & Travel::CommandList::operator= (Travel::CommandList const & other)
Definition at line 22 of file CommandList.cpp.
                                                           {
  if (&other != this) {
    copy(other);
  }
  return *this;
}
void Travel::CommandList::printCommandsWithDescription ()
Prints the registered commands along with their description. No promises are made in regards to the order they are printed in. Meant to be used as a documentation for the registered commands.
Definition at line 51 of file CommandList.cpp.
                                                     {
  std::cout << "Simple Command-line interface for Travel Management"
            << std::endl;
  // auto keys = nameToDescr.keys();
  // auto values = nameToDescr.values();
  using Pair = Tuple<SimpleString, const char *>;
  auto keysAndValues = nameToDescr.toList();
  // keys->zip(*values)
  // ->sort([](Tuple<SimpleString, const char*> const& t1,
  // Tuple<SimpleString, const char*> const& t2){
  // return t2.head() > t1.head();
  // });
  std::cout
      << "================================================================="
         "==============="
      << std::endl;
  for (unsigned i = 0; i < keysAndValues->length(); i++) {
    std::cout << "[" << keysAndValues->get(i).head() << "] "
              << *keysAndValues->get(i).get<1>() << std::endl;
    std::cout
        << "================================================================="
           "==============="
        << std::endl;
  }
}
References Tuple< Tail >::get().
Referenced by Travel::HTLInterpreter::general(), and Travel::VisitInterpreter::general().
void Travel::CommandList::registerCommand (SimpleString && name, TokenType tokenType, ScannerContext ctx, const char *&& descr)
Registers the command with the given information. A second call to registerCommand with different parameters but the same command name will overwrite the previous one.
Definition at line 40 of file CommandList.cpp.
                                                               {
  LOG(INFO, "Registering command: " << name);
  nameToDescr.put(name, std::move(descr));
  commandMap.put(tokenType, ctx);
  nameToToken.put(std::move(name), tokenType);
  LOG(INFO, nameToDescr.length() << " commands registered.");
}
References LOG.
void Travel::CommandList::registerCommand (SimpleString const & name, TokenType tokenType, ScannerContext ctx, const char * descr)
Registers the command with the given information. A second call to registerCommand with different parameters but the same command name will overwrite the previous one.
Definition at line 29 of file CommandList.cpp.
                                                             {
  LOG(INFO, "Registering command: " << name);
  nameToDescr.put(name, descr);
  commandMap.put(tokenType, ctx);
  nameToToken.put(name, tokenType);
  LOG(INFO, nameToDescr.length() << " commands registered.");
}
References LOG.
Referenced by main().
static void Travel::CommandList::setCommandList (CommandList * cl) [inline], [static]
Sets the global command list.
Parameters
cl the new command list
Definition at line 48 of file CommandList.hpp.
                                              {
    CommandList::globalCommandList = cl;
  }
References globalCommandList.
Referenced by main().
std::unique_ptr< Nullable< TokenType > > Travel::CommandList::tokenFor (SimpleString const & name)
Returns a pointer to a NotNull of the TokenType associated with the given name if such exists and Null otherwise.
Parameters
name the name to find the token type for
Returns
the token type
Definition at line 92 of file CommandList.cpp.
                                                    {
  LOG(VERBOSE, "Get token type for command.");
  return nameToToken.get(name);
}
References LOG.
Member Data Documentation
HashMap<TokenType, ScannerContext> Travel::CommandList::commandMap [private]
Definition at line 20 of file CommandList.hpp.
Referenced by copy().
Travel::CommandList * Travel::CommandList::globalCommandList = nullptr [static], [private]
A convenience value so CommandList doesn't need to be passed around as much.
Definition at line 28 of file CommandList.hpp.
Referenced by getCommandList(), and setCommandList().
HashMap<SimpleString, const char *> Travel::CommandList::nameToDescr [private]
Definition at line 22 of file CommandList.hpp.
Referenced by copy().
HashMap<SimpleString, TokenType> Travel::CommandList::nameToToken [private]
Definition at line 21 of file CommandList.hpp.
Referenced by copy().
Author
Generated automatically by Doxygen for Traveller's App from the source code.