Travel::VisitInterpreter
NAME
Travel::VisitInterpreter - An interpreter for the visit mode started by the visit <destination> command.
SYNOPSIS
#include <VisitInterpreter.hpp>
Inherits Interpreter< VisitBuilder >.
Public Member Functions
Interpreter (std::shared_ptr< ArrayList< Token >> _tokens)
Inherits the constructors of Interpreter.
bool parse (VisitBuilder &state) override
Parses the provided tokens into the given Travel::VisitBuilder.
Private Member Functions
void comment (VisitBuilder &vb)
Interprets the comment command.
void from (VisitBuilder &vb)
Interprets the from command.
bool general (VisitBuilder &vb)
Interprets all commands not part of a prefix. (from, to, rate, comment)
void photo (VisitBuilder &vb)
Interprets all commands that are part of the photo prefix. (delete, show, upload)
void photoDelete (VisitBuilder &vb)
Interprets the photo delete command.
void photoShow (VisitBuilder &vb)
Interprets the photo show command.
void photoUpload (VisitBuilder &vb)
Interprets the photo upload command.
void rate (VisitBuilder &vb)
Interprets the rate command.
void to (VisitBuilder &vb)
Interprets the to command.
Additional Inherited Members
Detailed Description
An interpreter for the visit mode started by the visit <destination> command.
Definition at line 26 of file VisitInterpreter.hpp.
Member Function Documentation
void Travel::VisitInterpreter::comment (VisitBuilder & vb) [private]
Interprets the comment command.
Definition at line 71 of file VisitInterpreter.cpp.
                                               {
  auto comment = consume(TokenType::STRING, "Expected Comment");
  vb.comment(comment.lexeme);
}
References Travel::VisitBuilder::comment(), Interpreter< VisitBuilder >::consume(), and STRING.
Referenced by general().
void Travel::VisitInterpreter::from (VisitBuilder & vb) [private]
Interprets the from command.
Definition at line 56 of file VisitInterpreter.cpp.
                                            {
  auto from = consume(TokenType::DATE, "Expected Date");
  vb.from(from.lexeme);
}
References Interpreter< VisitBuilder >::consume(), DATE, and Travel::VisitBuilder::from().
Referenced by general().
bool Travel::VisitInterpreter::general (VisitBuilder & vb) [private]
Interprets all commands not part of a prefix. (from, to, rate, comment)
Definition at line 5 of file VisitInterpreter.cpp.
                                               {
  switch (next().t) {
  case TokenType::FROM:
    from(vb);
    break;
  case TokenType::TO:
    to(vb);
    break;
  case TokenType::COMMENT:
    comment(vb);
    break;
  case TokenType::RATE:
    rate(vb);
    break;
  case TokenType::HELP:
    // TODO: Maybe filter the commands so only the right ones are
    // shown?
    CommandList::getCommandList()->printCommandsWithDescription();
    break;
  case TokenType::CANCEL:
    vb.clear();
  case TokenType::SAVE:
    return false;
    break;
  case TokenType::NUMBER:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Number -> " << prev().lexeme << std::endl;
    break;
  case TokenType::DATE:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Date -> " << prev().lexeme << std::endl;
    break;
  case TokenType::ERROR:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Parsing error: " << prev().lexeme << std::endl;
    break;
  case TokenType::EOF_T:
    return true;
    break;
  default:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected String -> " << prev().lexeme << std::endl;
    break;
  }
  return true;
}
References CANCEL, Travel::VisitBuilder::clear(), COMMENT, comment(), DATE, EOF_T, ERROR, Interpreter< VisitBuilder >::errorflag, FROM, from(), Travel::CommandList::getCommandList(), HELP, Token::lexeme, Token::line, Interpreter< VisitBuilder >::next(), NUMBER, Interpreter< VisitBuilder >::prev(), Travel::CommandList::printCommandsWithDescription(), RATE, rate(), SAVE, TO, and to().
Referenced by parse().
Interpreter< Controller >::Interpreter [inline], [explicit]
Inherits the constructors of Interpreter.
Definition at line 83 of file Interpreter.hpp.
      : tokens(_tokens) {}
bool Travel::VisitInterpreter::parse (VisitBuilder & state) [override]
Parses the provided tokens into the given Travel::VisitBuilder.
Definition at line 132 of file VisitInterpreter.cpp.
                                             {
  errorflag = false;
  // vb.destination(destination);
  while (!isAtEnd()) {
    try {
      if (matches(TokenType::PHOTO)) {
        LOG(INFO, "Photo prefix");
        next();
        photo(vb);
      } else {
        LOG(INFO, "General");
        if (!general(vb))
          return false;
      }
    } catch (NoValueException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
    } catch (InvalidArgumentException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
    } catch (ReachedEndOfStreamException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
      return true;
    } catch (WrongTokenTypeException &e) {
      errorflag = true;
      std::cerr << e.what() << std::endl;
      while (peek().t == TokenType::STRING || peek().t == TokenType::NUMBER ||
             peek().t == TokenType::DATE || peek().t == TokenType::ERROR) {
        Token n = next();
        if (n.t == TokenType::ERROR) {
          std::cerr << "Error: " << n.lexeme << std::endl;
        }
      }
    }
  }
  return true;
}
References DATE, ERROR, Interpreter< VisitBuilder >::errorflag, general(), Interpreter< VisitBuilder >::isAtEnd(), Token::lexeme, LOG, Interpreter< VisitBuilder >::matches(), Interpreter< VisitBuilder >::next(), NUMBER, Interpreter< VisitBuilder >::peek(), PHOTO, photo(), STRING, Token::t, WrongTokenTypeException::what(), NoValueException::what(), ReachedEndOfStreamException::what(), and InvalidArgumentException::what().
void Travel::VisitInterpreter::photo (VisitBuilder & vb) [private]
Interprets all commands that are part of the photo prefix. (delete, show, upload)
Definition at line 76 of file VisitInterpreter.cpp.
                                             {
  if (isAtEnd())
    throw ReachedEndOfStreamException();
  switch (next().t) {
  case TokenType::UPLOAD:
    photoUpload(vb);
    break;
  case TokenType::DELETE:
    photoDelete(vb);
    break;
  case TokenType::SHOW:
    photoShow(vb);
    break;
  case TokenType::EOF_T:
    std::cout << "Photo is a command prefix. It doesn't do anything"
                 " by itself."
              << std::endl;
    break;
  case TokenType::NUMBER:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Number -> " << prev().lexeme << std::endl;
    break;
  case TokenType::DATE:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected Date -> " << prev().lexeme << std::endl;
    break;
  case TokenType::ERROR:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Parsing error: " << prev().lexeme << std::endl;
    break;
  default:
    errorflag = true;
    std::cerr << "(Line " << prev().line << ") "
              << "Unexpected String -> " << prev().lexeme << std::endl;
    break;
  }
}
References DATE, DELETE, EOF_T, ERROR, Interpreter< VisitBuilder >::errorflag, Interpreter< VisitBuilder >::isAtEnd(), Token::lexeme, Token::line, Interpreter< VisitBuilder >::next(), NUMBER, photoDelete(), photoShow(), photoUpload(), Interpreter< VisitBuilder >::prev(), SHOW, and UPLOAD.
Referenced by parse().
void Travel::VisitInterpreter::photoDelete (VisitBuilder & vb) [private]
Interprets the photo delete command.
Definition at line 118 of file VisitInterpreter.cpp.
                                                   {
  auto uri = consume(TokenType::STRING, "Expected path to photo");
  std::cout << "Deleting " << uri.lexeme << std::endl;
  vb.photoDelete(uri.lexeme);
}
References Interpreter< VisitBuilder >::consume(), Travel::VisitBuilder::photoDelete(), and STRING.
Referenced by photo().
void Travel::VisitInterpreter::photoShow (VisitBuilder & vb) [private]
Interprets the photo show command.
Definition at line 124 of file VisitInterpreter.cpp.
{ vb.photoShow(); }
References Travel::VisitBuilder::photoShow().
Referenced by photo().
void Travel::VisitInterpreter::photoUpload (VisitBuilder & vb) [private]
Interprets the photo upload command.
Definition at line 126 of file VisitInterpreter.cpp.
                                                   {
  auto uri = consume(TokenType::STRING, "Expected path to photo");
  std::cout << "Uploading " << uri.lexeme << std::endl;
  vb.photoAdd(uri.lexeme);
}
References Interpreter< VisitBuilder >::consume(), Travel::VisitBuilder::photoAdd(), and STRING.
Referenced by photo().
void Travel::VisitInterpreter::rate (VisitBuilder & vb) [private]
Interprets the rate command.
Definition at line 66 of file VisitInterpreter.cpp.
                                            {
  auto rating = consume(TokenType::NUMBER, "Expected Number(1 - 5)");
  vb.rating(atoi(rating.lexeme));
}
References Interpreter< VisitBuilder >::consume(), NUMBER, and Travel::VisitBuilder::rating().
Referenced by general().
void Travel::VisitInterpreter::to (VisitBuilder & vb) [private]
Interprets the to command.
Definition at line 61 of file VisitInterpreter.cpp.
                                          {
  auto to = consume(TokenType::DATE, "Expected Date");
  vb.to(to.lexeme);
}
References Interpreter< VisitBuilder >::consume(), DATE, and Travel::VisitBuilder::to().
Referenced by general().
Author
Generated automatically by Doxygen for Traveller's App from the source code.