Travel::Scanner
NAME
Travel::Scanner - A general-purpose scanner that can be adopted to scan most forms of structured text files.
SYNOPSIS
#include <Scanner.hpp>
Public Member Functions
std::shared_ptr< ArrayList< Token > > scan ()
Scans the entire input stream.
Scanner (ScannerContext sc, std::istream *input, CommandList *cl)
Constructs a scanner for the provided input stream using the specified context and command list.
std::shared_ptr< ArrayList< Token > > scanNext ()
Scans the next line in the input stream.
Public Attributes
bool error = false
Set to true only if the scanner encounters an error during scanning i.e a token of type ERROR is generated.
Private Member Functions
std::shared_ptr< ArrayList< Token > > scanLine (const char *line)
Tokenizes the provided line.
Private Attributes
CommandList * cl
std::istream * input
int line = 1
ScannerContext sc
Detailed Description
A general-purpose scanner that can be adopted to scan most forms of structured text files.
It can scan text from any input stream implemented through std::istream regardless if it is a file, standard input or, potentially, a remote source.
This class provides methods for scanning the entire stream at once as well as scanning the stream line-by-line for cases such as accepting from the user rather than a static source (file, remote resource, etc).
The scanner is not reusable. Rather they are meant to read a single input stream once and consequently be disposed of.
You can provide a list of reserved keywords with CommandList. Some keywords may only be provided in a certain context (File, Command-line or all) as such the scanner needs to know it's own context which is provided at instantiation through ScannerContext
Definition at line 42 of file Scanner.hpp.
Constructor & Destructor Documentation
Travel::Scanner::Scanner (ScannerContext sc, std::istream * input, CommandList * cl)
Constructs a scanner for the provided input stream using the specified context and command list.
Parameters
sc the context of the scanner
input the input stream to scan
cl the list of reserved keywords
Definition at line 4 of file Scanner.cpp.
                                          {
  LOG(INFO, "Initialize scanner.");
  this->sc = sc;
  this->input = input;
  this->cl = cl;
}
References cl, input, LOG, and sc.
Member Function Documentation
std::shared_ptr< ArrayList< Token > > Travel::Scanner::scan ()
Scans the entire input stream. This is done by reading from the stream line-by-line until the end of the stream is reached. Due to technical limitations the lines are assumed to be of 512 characters or less.
The last token of the returned list is always of type {EOF} a shared pointer to a list containing the resulting tokens
Definition at line 12 of file Scanner.cpp.
                                                    {
  LOG(INFO, "Scanning..");
  error = false;
  std::shared_ptr<ArrayList<Token>> list = std::make_shared<ArrayList<Token>>();
  while (!input->eof()) {
    LOG(INFO, "Reading line from input.");
    char sline[513];
    input->getline(sline, 512);
    if (input->eof())
      break;
    list->appendAll(*scanLine(sline));
    line++;
  }
  LOG(VERBOSE, "Reached end of input");
  list->append(Token{TokenType::EOF_T, "", line});
  return list;
}
References EOF_T, and LOG.
Referenced by CSV< const char *, const char *, const char * >::load().
std::shared_ptr< ArrayList< Token > > Travel::Scanner::scanLine (const char * line) [private]
Tokenizes the provided line.
Parameters
line the line to tokenize
Returns
a shared pointer to a list containing the resulting tokens
Definition at line 46 of file Scanner.cpp.
                                                                        {
  LOG(VERBOSE, "Read: ");
  LOG(VERBOSE, line);
  LOG(VERBOSE, "Tokenizing line...");
  std::shared_ptr<ArrayList<Token>> list = std::make_shared<ArrayList<Token>>();
  int linelen = strlen(line);
  int index = 0;
  while (index < linelen) {
    LOG(INFO, "======================================================");
    if (line[index] == '"') {
      LOG(INFO, "Found beginning of string literal.");
      index++;
      int start = index;
      while (line[index] != '"') {
        index++;
        if (index >= linelen) {
          LOG(ERROR, "Unterminated string.");
          const char errorMsg[] = "Unterminated string.";
          list->append({TokenType::ERROR, errorMsg, this->line});
          error = true;
          return list;
        }
      }
      LOG(VERBOSE, "Reached end of string");
      if (index + 1 != linelen && line[index + 1] != ' ') {
        LOG(ERROR, "Expected whitespace or EOL after string.");
        const char errorMsg[] = "Expected whitespace or EOL after string.";
        list->append({TokenType::ERROR, errorMsg, this->line});
        error = true;
        return list;
      }
      char *lexeme = new char[index - start + 1];
      LOG(VERBOSE, "Copying string... ");
      strncpy(lexeme, line + start, index - start);
      lexeme[index - start] = '\0';
      LOG(VERBOSE, "Generating token...");
      list->append({TokenType::STRING, lexeme, this->line});
      delete[] lexeme;
      LOG(INFO, "String token generated successfully");
      index++;
    } else if (isdigit(line[index]) ||
               (line[index] == '-' && index + 1 < linelen &&
                isdigit(line[index + 1]))) {
      LOG(INFO, "Found beginning of number");
      int start = index;
      bool maybeDate = false;
      if (line[index] == '-')
        index++;
      TokenType tt = TokenType::NUMBER;
      while (isdigit(line[index])) {
        index++;
        if (line[index] == '-' && tt == TokenType::NUMBER &&
            index + 1 < linelen && isdigit(line[index + 1])) {
          tt = TokenType::DATE;
          index++;
          maybeDate = true;
        } else if (line[index] == '-' && maybeDate && index + 1 < linelen &&
                   isdigit(line[index + 1])) {
          index++;
          maybeDate = false;
        } else if (line[index] == '-') {
          index++;
          tt = TokenType::STRING;
          break;
        }
      }
      LOG(VERBOSE, "Reached end of number");
      while (index < linelen && line[index] != ' ') {
        tt = TokenType::STRING;
        index++;
      }
      char *lexeme = new char[index - start + 1];
      LOG(VERBOSE, "Copying number...");
      strncpy(lexeme, line + start, index - start);
      lexeme[index - start] = '\0';
      LOG(VERBOSE, "Generating token...");
      list->append({tt, lexeme, this->line});
      delete[] lexeme;
      LOG(INFO, "Number token generated successfully");
      index++;
    } else if (line[index] == ' ') {
      LOG(VERBOSE, "Skipping whitespace");
      index++;
    } else {
      LOG(INFO, "Found either a reserved keyword or a single-word string");
      int start = index;
      index++;
      while (index < linelen && line[index] != ' ') {
        index++;
      }
      LOG(VERBOSE, "Found end of identifier");
      if (index != linelen && line[index] != ' ') {
        LOG(ERROR, "Expected whitespace or EOL after identifier.");
        const char errorMsg[] = "Expected whitespace or EOL after identifier.";
        list->append({TokenType::ERROR, errorMsg, this->line});
        error = true;
        return list;
      }
      char *lexeme = new char[index - start + 1];
      LOG(VERBOSE, "Copying identifier...");
      strncpy(lexeme, line + start, index - start);
      lexeme[index - start] = '\0';
      LOG(INFO, "Checking if identifier is a reserved keyword...");
      std::shared_ptr<Nullable<TokenType>> tt = cl->tokenFor(lexeme);
      if (tt->isDefined()) {
        LOG(INFO, "Found reserved keyword.");
        LOG(VERBOSE, "Acquiring Scanner Context for keyword.");
        ScannerContext tctx =
            cl->contextFor(tt->get())->getOrElse(ScannerContext::UNDEFINED);
        if (tctx == ScannerContext::ALL || tctx == sc ||
            sc == ScannerContext::ALL) {
          LOG(VERBOSE, "Keyword used in proper scanner context.");
          LOG(VERBOSE, "Generating token...");
          list->append({tt->get(), lexeme, this->line});
          LOG(INFO, "Keyword token generated successfully");
        } else {
          LOG(ERROR, "Command used in the wrong context.");
          const char errorMsg[] = "Command used in the wrong context.";
          list->append({TokenType::ERROR, errorMsg, this->line});
          error = true;
          delete[] lexeme;
          return list;
        }
      } else {
        LOG(INFO, "Not a reserved keyword.");
        LOG(VERBOSE, "Generating token...");
        list->append({TokenType::STRING, lexeme, this->line});
        LOG(INFO, "String token generated successfully");
      }
      delete[] lexeme;
      index++;
    }
  }
  LOG(INFO, "Line tokenized...");
  return list;
}
References ALL, DATE, ERROR, LOG, NUMBER, STRING, and UNDEFINED.
std::shared_ptr< ArrayList< Token > > Travel::Scanner::scanNext ()
Scans the next line in the input stream. Due to technical limitations the lines are assumed to be of 512 characters or less.
The last token of the returned list is always of type {EOF} a shared pointer to a list containing the resulting tokens
Definition at line 30 of file Scanner.cpp.
                                                        {
  LOG(INFO, "Scanning next line...");
  error = false;
  std::shared_ptr<ArrayList<Token>> list = std::make_shared<ArrayList<Token>>();
  char sline[513];
  input->getline(sline, 512);
  if (input->eof()) {
    list->append(Token{TokenType::EOF_T, "", line});
    return list;
  }
  list->appendAll(*scanLine(sline));
  line++;
  list->append(Token{TokenType::EOF_T, "", line});
  return list;
}
References EOF_T, and LOG.
Referenced by main(), and Travel::HTLInterpreter::visit().
Member Data Documentation
CommandList* Travel::Scanner::cl [private]
Definition at line 45 of file Scanner.hpp.
Referenced by Scanner().
bool Travel::Scanner::error = false
Set to true only if the scanner encounters an error during scanning i.e a token of type ERROR is generated. This is done so more than one error can be detected in a single scan.
Definition at line 63 of file Scanner.hpp.
std::istream* Travel::Scanner::input [private]
Definition at line 46 of file Scanner.hpp.
Referenced by Scanner().
int Travel::Scanner::line = 1 [private]
Definition at line 47 of file Scanner.hpp.
ScannerContext Travel::Scanner::sc [private]
Definition at line 44 of file Scanner.hpp.
Referenced by Scanner().
Author
Generated automatically by Doxygen for Traveller's App from the source code.