Travel
NAME
Travel - Collects all code that is not necessarily easily reusable.
SYNOPSIS
Classes
class CommandList
This class represents a list of unique, reserved keywords for the scanner.
class Date
Stores a date (in ISO 8601) and has some useful methods for working with dates.
class HTLInterpreter
An interpreter for general commands.
class LoginInterpreter
Interprets all commands in the ATOPEN ScannerContext.
class Scanner
A general-purpose scanner that can be adopted to scan most forms of structured text files.
class TravelState
class VisitBuilder
Holds all information necessary to construct a visit.
class VisitInterpreter
An interpreter for the visit mode started by the visit <destination> command.
Functions
static bool isDash (std::istream &in)
std::ostream & operator<< (std::ostream &out, const Date &date)
std::istream & operator>> (std::istream &in, Date &date)
Detailed Description
Collects all code that is not necessarily easily reusable.
(i. e. is too specialized to the project)
Function Documentation
static bool Travel::isDash (std::istream & in) [static]
Definition at line 162 of file Date.cpp.
{ return in.get() == '-'; }
Referenced by operator>>().
std::ostream& Travel::operator<< (std::ostream & out, const Date & date)
Definition at line 153 of file Date.cpp.
                                                          {
  char str[11];
  date.getString(str);
  out << str;
  return out;
}
References Travel::Date::getString().
std::istream& Travel::operator>> (std::istream & in, Date & date)
Definition at line 164 of file Date.cpp.
                                                   {
  int year;
  int month;
  int day;
  in >> year;
  if (!isDash(in)) {
    in.setstate(std::ios::failbit);
    return in;
  }
  in >> month;
  if (!isDash(in)) {
    in.setstate(std::ios::failbit);
    return in;
  }
  in >> day;
  date.setYear(year);
  date.setMonth(month);
  date.setDay(day);
  return in;
}
References isDash(), Travel::Date::setDay(), Travel::Date::setMonth(), and Travel::Date::setYear().
Author
Generated automatically by Doxygen for Traveller's App from the source code.