Travel::TravelState
NAME
Travel::TravelState
SYNOPSIS
#include <TravelState.hpp>
Public Member Functions
void destinationComments (const char *dest)
Print the visit stats for the given destination of all users who have visited it.
bool destinationExists (const char *dest)
Returns true if the given destination is registered in at least one user's visit history.
void destinationRating (const char *dest)
Prints the average rating of the given destination to stdout.
void friendAdd (const char *name)
Add given user to the logged-in user's friends list.
void friendList ()
List the users in the logged-in user's friends list.
void friendRemove (const char *name)
Remove given user from the logged-in user's friends list.
void friendVisited (const char *dest)
Print the visit stats of all users in the logged in user's friend list for the given destination.
void friendVisited (const char *dest, const char *name)
Prints the visit stats of the given user for the given desination if that user is in your friends list.
bool login (const char *username, const char *password)
Attempt to log into the given user with the given password.
void save (VisitBuilder &vb)
Save the visit stored in the provided VisitBuilder to the logged-in user's visit history.
TravelState ()
Initialize the travel state. This loads and initializes all users from the user database.
bool uregister (const char *email, const char *username, const char *password)
Register an account with the provided email, username and password The username must not already be taken.
void userVisited (const char *dest, const char *name)
Prints the visit stats of the given user for the given desination.
~TravelState ()
Private Attributes
CSV< const char *, const char *, const char * > csv {'user', 'pass', 'email'}
User * loggedInUser = nullptr
HashMap< SimpleString, User * > users
Static Private Attributes
static constexpr char * usersDatabase = 'users.db'
Detailed Description
Definition at line 9 of file TravelState.hpp.
Constructor & Destructor Documentation
Travel::TravelState::TravelState () [inline]
Initialize the travel state. This loads and initializes all users from the user database.
Definition at line 23 of file TravelState.hpp.
                {
    csv.load(TravelState::usersDatabase);
    auto keys = csv.getKeys();
    for (int i = 0; i < csv.size(); i++) {
      users.put(keys->get(i), new User(keys->get(i)));
    }
  }
References csv, CSV< Types >::getKeys(), CSV< Types >::load(), HashMap< Key, Value >::put(), CSV< Types >::size(), users, and usersDatabase.
Travel::TravelState::~TravelState () [inline]
Definition at line 31 of file TravelState.hpp.
                 {
    users.values()->foreach ([](User *const(&usr)) { delete usr; });
    csv.save(TravelState::usersDatabase);
  }
References csv, CSV< Types >::save(), users, usersDatabase, and HashMap< Key, Value >::values().
Member Function Documentation
void Travel::TravelState::destinationComments (const char * dest)
Print the visit stats for the given destination of all users who have visited it.
Definition at line 155 of file TravelState.cpp.
                                                            {
  users.values()
      ->filter([&dest](User *const(&u)) { return u->hasVisited(dest); })
      ->foreach (
          [&dest, this](User *const(&u)) { userVisited(dest, u->getName()); });
}
Referenced by Travel::HTLInterpreter::destinationComments().
bool Travel::TravelState::destinationExists (const char * dest)
Returns true if the given destination is registered in at least one user's visit history.
Definition at line 181 of file TravelState.cpp.
                                                          {
  return users.values()->find(
             [&dest](User *const(&u)) { return u->hasVisited(dest); }) >= 0;
}
Referenced by Travel::HTLInterpreter::destinationExists().
void Travel::TravelState::destinationRating (const char * dest)
Prints the average rating of the given destination to stdout.
Definition at line 162 of file TravelState.cpp.
                                                          {
  auto ratings =
      users.values()
          ->filter([&dest](User *const(&u)) { return u->hasVisited(dest); })
          ->map<int>([&dest](User *const(&u)) {
            auto stats = u->destinationStats(dest);
            return atoi(*stats.get<3>());
          })
          ->filter([](int const &i) { return i > 0; });
  int ratingCount = ratings->length();
  if (ratingCount == 0) {
    std::cout << "Nobody has rated this destination yet." << std::endl;
    return;
  }
  int sum = ratings->fold(0, [](int const &a, int const &b) { return a + b; });
  std::cout << "Average rating of " << dest << " is "
            << (((double)sum) / ratingCount) << std::endl;
}
Referenced by Travel::HTLInterpreter::destinationRating().
void Travel::TravelState::friendAdd (const char * name)
Add given user to the logged-in user's friends list.
Definition at line 70 of file TravelState.cpp.
                                                  {
  auto userNameInd = csv.getKeys()->find(
      [name](const char *const(&key)) { return strcmp(key, name) == 0; });
  if (userNameInd < 0) {
    std::cerr << "User with the name " << name << " doesn't exist" << std::endl;
    return;
  }
  loggedInUser->addFriend(name);
}
Referenced by Travel::HTLInterpreter::friendAdd().
void Travel::TravelState::friendList ()
List the users in the logged-in user's friends list.
Definition at line 91 of file TravelState.cpp.
{ loggedInUser->listFriends(); }
Referenced by Travel::HTLInterpreter::friendList().
void Travel::TravelState::friendRemove (const char * name)
Remove given user from the logged-in user's friends list.
Definition at line 80 of file TravelState.cpp.
                                                     {
  auto userNameInd = csv.getKeys()->find(
      [name](const char *const(&key)) { return strcmp(key, name) == 0; });
  if (userNameInd < 0) {
    std::cerr << "User with the name " << name << " doesn't exist" << std::endl;
    return;
  }
  loggedInUser->removeFriend(name);
}
Referenced by Travel::HTLInterpreter::friendRemove().
void Travel::TravelState::friendVisited (const char * dest)
Print the visit stats of all users in the logged in user's friend list for the given destination.
Definition at line 150 of file TravelState.cpp.
                                                      {
  auto fr = loggedInUser->getFriends();
  fr.foreach ([&dest, this](char *const(&f)) { userVisited(dest, f); });
}
void Travel::TravelState::friendVisited (const char * dest, const char * name)
Prints the visit stats of the given user for the given desination if that user is in your friends list.
See also
userVisited
Definition at line 140 of file TravelState.cpp.
                                                                        {
  bool hasfr = loggedInUser->hasFriend(name);
  if (!hasfr) {
    std::cerr << name << " is not your friend." << std::endl;
    return;
  }
  userVisited(dest, name);
}
Referenced by Travel::HTLInterpreter::friendVisited().
bool Travel::TravelState::login (const char * username, const char * password)
Attempt to log into the given user with the given password.
Returns
true upon success and false otherwise
Definition at line 5 of file TravelState.cpp.
                                                                        {
  if (loggedInUser) {
    std::cerr << "Already logged in into " << loggedInUser->getName()
              << std::endl;
    return true;
  }
  auto userNameInd = csv.getKeys()->find([username](const char *const(&key)) {
    return strcmp(key, username) == 0;
  });
  if (userNameInd < 0) {
    std::cerr << "Username or password doesn't match our database."
              << std::endl;
    return false;
  }
  auto userEntry = csv.getRow(userNameInd);
  if (strcmp(*userEntry.get<1>(), password) != 0) {
    std::cerr << "Username or password doesn't match our database."
              << std::endl;
    return false;
  }
  loggedInUser = users.get(username)->get();
  return true;
}
References csv, HashMap< Key, Value >::get(), CSV< Types >::getKeys(), User::getName(), CSV< Types >::getRow(), loggedInUser, and users.
Referenced by Travel::LoginInterpreter::login().
void Travel::TravelState::save (VisitBuilder & vb)
Save the visit stored in the provided VisitBuilder to the logged-in user's visit history.
Definition at line 34 of file TravelState.cpp.
{ loggedInUser->addVisit(vb); }
Referenced by Travel::HTLInterpreter::visit().
bool Travel::TravelState::uregister (const char * email, const char * username, const char * password)
Register an account with the provided email, username and password The username must not already be taken.
Definition at line 36 of file TravelState.cpp.
                                                          {
  if (loggedInUser) {
    std::cerr << "Already logged in into " << loggedInUser->getName()
              << std::endl;
    return true;
  }
  auto userNameInd = csv.getKeys()->find([username](const char *const(&key)) {
    return strcmp(key, username) == 0;
  });
  if (userNameInd >= 0) {
    std::cerr << "Username is taken." << std::endl;
    return false;
  }
  char *_usrcpy = new char[strlen(username) + 1];
  strcpy(_usrcpy, username);
  char *_passcpy = new char[strlen(password) + 1];
  strcpy(_passcpy, password);
  char *_mailcpy = new char[strlen(email) + 1];
  strcpy(_mailcpy, email);
  const char *usrcpy = _usrcpy;
  const char *passcpy = _passcpy;
  const char *mailcpy = _mailcpy;
  std::filesystem::create_directory(username);
  csv.addEntry(usrcpy, passcpy, mailcpy);
  users.put(username, new User(username));
  loggedInUser = users.get(username)->get();
  return true;
}
Referenced by Travel::LoginInterpreter::reg().
void Travel::TravelState::userVisited (const char * dest, const char * name)
Prints the visit stats of the given user for the given desination.
Definition at line 93 of file TravelState.cpp.
                                                                      {
  auto user = users.get(name);
  if (user->isEmpty()) {
    std::cerr << "User with the name " << name << " doesn't exist."
              << std::endl;
    return;
  }
  auto userg = user->get();
  if (!userg->hasVisited(dest)) {
    std::cout << name << " hasn't visited " << dest << std::endl;
    return;
  }
  auto deststats = userg->destinationStats(dest);
  auto from = *deststats.get<1>();
  auto to = *deststats.get<2>();
  auto rating = atoi(*deststats.get<3>());
  auto comment = *deststats.get<4>();
  std::cout << name;
  if (rating > 0) {
    std::cout << " (";
    for (int i = 1; i <= rating; i++) {
      std::cout << "*";
    }
    std::cout << ")";
  }
  std::cout << " [";
  if (strcmp(from, to) == 0) {
    std::cout << from;
  } else {
    std::cout << from << " - " << to;
  }
  std::cout << "]";
  if (strlen(comment) > 0) {
    std::cout << " says: " << std::endl;
    std::cout << comment;
  }
  std::cout << std::endl;
}
Referenced by Travel::HTLInterpreter::destinationVisited().
Member Data Documentation
CSV<const char *, const char *, const char *> Travel::TravelState::csv {'user', 'pass', 'email'} [private]
Definition at line 16 of file TravelState.hpp.
Referenced by login(), TravelState(), and ~TravelState().
User* Travel::TravelState::loggedInUser = nullptr [private]
Definition at line 18 of file TravelState.hpp.
Referenced by login().
HashMap<SimpleString, User *> Travel::TravelState::users [private]
Definition at line 17 of file TravelState.hpp.
Referenced by login(), TravelState(), and ~TravelState().
constexpr char* Travel::TravelState::usersDatabase = 'users.db' [static], [constexpr], [private]
Definition at line 13 of file TravelState.hpp.
Referenced by TravelState(), and ~TravelState().
Author
Generated automatically by Doxygen for Traveller's App from the source code.