Travel::VisitBuilder
NAME
Travel::VisitBuilder - Holds all information necessary to construct a visit.
SYNOPSIS
#include <VisitBuilder.hpp>
Public Member Functions
void clear ()
Reset all values to their default state.
void comment (const char *comment)
Set the comment.
void destination (const char *destination)
Set destination.
void from (char *fdate)
Set the start of visit. TODO: Make sure from is before to.
char * getComment () const
Return the visit comment.
char * getDestination () const
Return visit destination.
Date getFrom () const
Return start of visit.
ArrayList< SimpleString > getPics ()
Return the list of paths to uploaded photos.
int getRating () const
Return the rating.
Date getTo () const
Return end of visit.
void photoAdd (SimpleString &&uri)
Add photo.
void photoDelete (SimpleString &&uri)
Remove photo.
void photoShow ()
Print a list of the uploaded photos to stdout.
void rating (int i)
Set the rating (1 - 5)
void to (char *fdate)
Set the end of visit. TODO: Make sure from is before to.
Private Attributes
char * _comment = nullptr
char * _destination = nullptr
Date _from
ArrayList< SimpleString > _photos
int _rating = -1
Date _to
bool setFrom = false
bool setTo = false
Detailed Description
Holds all information necessary to construct a visit.
Meant as disposable way to package information that will be passed from the UI to TravelState in a single function call.
Definition at line 20 of file VisitBuilder.hpp.
Member Function Documentation
void Travel::VisitBuilder::clear () [inline]
Reset all values to their default state.
Definition at line 126 of file VisitBuilder.hpp.
               {
    setFrom = false;
    setTo = false;
    if (_destination) {
      delete[] _destination;
      _destination = nullptr;
    }
    if (_comment) {
      delete[] _comment;
      _comment = nullptr;
    }
    _rating = -1;
    _photos.clear();
  }
References _comment, _destination, _photos, _rating, ArrayList< A >::clear(), setFrom, and setTo.
Referenced by Travel::VisitInterpreter::general().
void Travel::VisitBuilder::comment (const char * comment) [inline]
Set the comment.
Definition at line 86 of file VisitBuilder.hpp.
                                    {
    if (_comment) {
      std::cerr << "Already commented " << _comment << ". Changing value."
                << std::endl;
      delete[] _comment;
    }
    _comment = new char[strlen(comment) + 1];
    strcpy(_comment, comment);
  }
References _comment.
Referenced by Travel::VisitInterpreter::comment().
void Travel::VisitBuilder::destination (const char * destination) [inline]
Set destination.
Definition at line 115 of file VisitBuilder.hpp.
                                            {
    if (_destination) {
      std::cerr << "Already chose " << _destination
                << " as destination. Changing value." << std::endl;
      delete[] _destination;
    }
    _destination = new char[strlen(destination) + 1];
    strcpy(_destination, destination);
  }
References _destination.
Referenced by Travel::HTLInterpreter::visit().
void Travel::VisitBuilder::from (char * fdate) [inline]
Set the start of visit. TODO: Make sure from is before to.
Definition at line 52 of file VisitBuilder.hpp.
                         {
    if (setFrom) {
      std::cerr << "Already set 'from' to " << _from << ". Changing value."
                << std::endl;
    }
    _from = Travel::Date(fdate);
    setFrom = true;
  }
References _from, and setFrom.
Referenced by Travel::VisitInterpreter::from().
char* Travel::VisitBuilder::getComment () const [inline]
Return the visit comment.
Definition at line 36 of file VisitBuilder.hpp.
{ return _comment; }
References _comment.
Referenced by User::addVisit().
char* Travel::VisitBuilder::getDestination () const [inline]
Return visit destination.
Definition at line 48 of file VisitBuilder.hpp.
{ return _destination; }
References _destination.
Referenced by User::addVisit().
Date Travel::VisitBuilder::getFrom () const [inline]
Return start of visit.
Definition at line 45 of file VisitBuilder.hpp.
{ return _from; }
References _from.
Referenced by User::addVisit().
ArrayList<SimpleString> Travel::VisitBuilder::getPics () [inline]
Return the list of paths to uploaded photos.
Definition at line 33 of file VisitBuilder.hpp.
{ return _photos; }
References _photos.
Referenced by User::addVisit().
int Travel::VisitBuilder::getRating () const [inline]
Return the rating.
Definition at line 39 of file VisitBuilder.hpp.
{ return _rating; }
References _rating.
Referenced by User::addVisit().
Date Travel::VisitBuilder::getTo () const [inline]
Return end of visit.
Definition at line 42 of file VisitBuilder.hpp.
{ return _to; }
References _to.
Referenced by User::addVisit().
void Travel::VisitBuilder::photoAdd (SimpleString && uri) [inline]
Add photo.
Definition at line 97 of file VisitBuilder.hpp.
{ _photos.append(std::move(uri)); }
References _photos, and ArrayList< A >::append().
Referenced by Travel::VisitInterpreter::photoUpload().
void Travel::VisitBuilder::photoDelete (SimpleString && uri) [inline]
Remove photo.
Definition at line 100 of file VisitBuilder.hpp.
                                       {
    auto res = _photos.remove(std::move(uri));
    if (res == -1) {
      std::cerr << "This photo does not exists." << std::endl;
    }
  }
References _photos, and ArrayList< A >::remove().
Referenced by Travel::VisitInterpreter::photoDelete().
void Travel::VisitBuilder::photoShow () [inline]
Print a list of the uploaded photos to stdout.
Definition at line 108 of file VisitBuilder.hpp.
                   {
    std::cout << "Photos uploaded: " << std::endl;
    _photos.foreach (
        [](SimpleString const &ss) { std::cout << ss << std::endl; });
  }
References _photos, and ArrayList< A >::foreach().
Referenced by Travel::VisitInterpreter::photoShow().
void Travel::VisitBuilder::rating (int i) [inline]
Set the rating (1 - 5)
Definition at line 73 of file VisitBuilder.hpp.
                     {
    if (i < 1 || i > 5) {
      std::cerr << "Rating must be between 1 - 5 inclusive" << std::endl;
      return;
    }
    if (_rating != -1) {
      std::cerr << "Already rated " << _rating << ". Changing value."
                << std::endl;
    }
    _rating = i;
  }
References _rating.
Referenced by Travel::VisitInterpreter::rate().
void Travel::VisitBuilder::to (char * fdate) [inline]
Set the end of visit. TODO: Make sure from is before to.
Definition at line 63 of file VisitBuilder.hpp.
                       {
    if (setTo) {
      std::cerr << "Already set 'to' to " << _to << ". Changing value."
                << std::endl;
    }
    _to = Travel::Date(fdate);
    setTo = true;
  }
References _to, and setTo.
Referenced by Travel::VisitInterpreter::to().
Member Data Documentation
char* Travel::VisitBuilder::_comment = nullptr [private]
Definition at line 28 of file VisitBuilder.hpp.
Referenced by clear(), comment(), and getComment().
char* Travel::VisitBuilder::_destination = nullptr [private]
Definition at line 22 of file VisitBuilder.hpp.
Referenced by clear(), destination(), and getDestination().
Date Travel::VisitBuilder::_from [private]
Definition at line 23 of file VisitBuilder.hpp.
Referenced by from(), and getFrom().
ArrayList<SimpleString> Travel::VisitBuilder::_photos [private]
Definition at line 29 of file VisitBuilder.hpp.
Referenced by clear(), getPics(), photoAdd(), photoDelete(), and photoShow().
int Travel::VisitBuilder::_rating = -1 [private]
Definition at line 27 of file VisitBuilder.hpp.
Referenced by clear(), getRating(), and rating().
Date Travel::VisitBuilder::_to [private]
Definition at line 25 of file VisitBuilder.hpp.
Referenced by getTo(), and to().
bool Travel::VisitBuilder::setFrom = false [private]
Definition at line 24 of file VisitBuilder.hpp.
Referenced by clear(), and from().
bool Travel::VisitBuilder::setTo = false [private]
Definition at line 26 of file VisitBuilder.hpp.
Referenced by clear(), and to().
Author
Generated automatically by Doxygen for Traveller's App from the source code.