.TH "TravellersApp/src/ttype.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/ttype.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBforType< Type >\fP"
.br
.RI "A collection of template magic that operates on the provided type There is only a single piece of magic here right now\&. "
.ti -1c
.RI "struct \fBforType< Type >::repeat< times, Tail >\fP"
.br
.RI "A template magic spell that will repeat the given type the provided number of types\&. This can later be applied to any type that accepts a vararg template\&. "
.ti -1c
.RI "struct \fBforType< Type >::repeat< 0, Tail\&.\&.\&. >\fP"
.br
.RI "Root of the recursion for \fBrepeat\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
