TravellersApp/src/collection/Tuple.hpp
NAME
TravellersApp/src/collection/Tuple.hpp
SYNOPSIS
#include '../ttype.hpp'
#include <cstdlib>
#include <functional>
#include <iostream>
#include <type_traits>
Classes
struct Tuple< Head, Tail... >::ofSize< i >
Construct the type of tuple of the given size by repeating the Head type of tuple used to refer to this struct that many times.
class Tuple< Tail >
Tuple implementation partially taken from www.stroustrup.com/C++11FAQ.html::variadic-templates It wasn't working out of the box since it was meant as an example of variadic templates rather than an actually usable tuple class but I patched it up and added a whole ton of additional (badly designed) features.
class Tuple< Head, Tail... >
struct Tuple< Head, Tail... >::typeOf< ind, dummy >
Return the type of the element at the provided index.
struct Tuple< Tail >::typeOf< ind, dummy >
End of recursive template of typeOf.
struct Tuple< Head, Tail... >::typeOf< 0, dummy >
Bottom o recursion.
Functions
template<typename Head , typename... Tail> static std::ostream & operator<< (std::ostream &out, Tuple< Head, Tail... > const &tuple)
static std::ostream & operator<< (std::ostream &out, Tuple<> const &tuple)
Function Documentation
template<typename Head , typename... Tail> static std::ostream& operator<< (std::ostream & out, Tuple< Head, Tail... > const & tuple) [static]
Definition at line 61 of file Tuple.hpp.
                                                                   {
  out << "\"" << tuple.head() << "\"";
  if (tuple.size() > 1)
    out << " ";
  out << tuple.tail();
  return out;
}
References Tuple< Head, Tail... >::head(), Tuple< Head, Tail... >::size(), and Tuple< Head, Tail... >::tail().
static std::ostream& operator<< (std::ostream & out, Tuple<> const & tuple) [static]
Definition at line 56 of file Tuple.hpp.
                                                                     {
  return out;
}
Author
Generated automatically by Doxygen for Traveller's App from the source code.