.TH "Tuple< Tail >::typeOf< ind, dummy >" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tuple< Tail >::typeOf< ind, dummy > \- End of recursive template of \fBtypeOf\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tuple\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = void"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&. Tail>
.br
template<int ind, typename dummy = int>
.br
struct Tuple< Tail >::typeOf< ind, dummy >"
End of recursive template of \fBtypeOf\fP\&. 
.PP
Definition at line 25 of file Tuple\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename\&.\&.\&. Tail> template<int ind, typename dummy  = int> using \fBTuple\fP< Tail >::\fBtypeOf\fP< ind, dummy >::\fBtype\fP =  void"

.PP
Definition at line 25 of file Tuple\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
