Tuple< Head, Tail... >
NAME
Tuple< Head, Tail... >
SYNOPSIS
#include <Tuple.hpp>
Inherits Tuple< Tail... >.
Classes
struct ofSize
Construct the type of tuple of the given size by repeating the Head type of tuple used to refer to this struct that many times.
struct typeOf
Return the type of the element at the provided index.
struct typeOf< 0, dummy >
Bottom o recursion.
Public Member Functions
template<typename T , std::enable_if_t< std::is_same< type, typename Tuple< std::remove_reference_t< T >>::template ofSize< _size >::type >::value > * = nullptr> T const * at (int ind) const
void free ()
template<int ind> typeOf< ind >::type * get ()
template<int ind> std::add_const_t< typename typeOf< ind >::type > * get () const
Head & head ()
The head element.
const Head & head () const
The head element.
template<typename T , std::enable_if_t< std::is_same< Head, T >::value > * = nullptr> constexpr int indexOf (Head const &elem)
template<typename T , std::enable_if_t<!std::is_same< Head, T >::value > * = nullptr> constexpr int indexOf (T const &elem)
bool operator== (type const &other) const
constexpr size_t size () const
inherited & tail ()
All elements except the first one.
const inherited & tail () const
All elements except the first one.
Tuple ()=delete
Issue a compiler error if tuple not constructed with enough elements.
template<typename... VariadicValues> Tuple (Head &&head, VariadicValues &&... tail)
template<typename... VariadicValues> Tuple (Head const &head, VariadicValues... tail)
template<typename T , std::enable_if_t< std::is_same< type, typename Tuple< T >::template ofSize< _size >::type >::value > * = nullptr> Tuple (T **tptr)
Tuple (type const &other)
Protected Attributes
Head _head
Private Types
using inherited = Tuple< Tail... >
The type if the tuple this tuple inherits from.
using type = Tuple< Head, Tail... >
The type of the tuple.
Static Private Attributes
static constexpr size_t _size = 1 + sizeof...(Tail)
The size of the tuple.
Additional Inherited Members
Detailed Description
template<typename Head, typename... Tail>
class Tuple< Head, Tail... >"
Definition at line 71 of file Tuple.hpp.
Member Typedef Documentation
template<typename Head , typename... Tail> using Tuple< Head, Tail... >::inherited = Tuple<Tail...> [private]
The type if the tuple this tuple inherits from.
Definition at line 76 of file Tuple.hpp.
template<typename Head , typename... Tail> using Tuple< Head, Tail... >::type = Tuple<Head, Tail...> [private]
The type of the tuple.
Definition at line 74 of file Tuple.hpp.
Constructor & Destructor Documentation
template<typename Head , typename... Tail> Tuple< Head, Tail... >::Tuple () [delete]
Issue a compiler error if tuple not constructed with enough elements.
template<typename Head , typename... Tail> template<typename... VariadicValues> Tuple< Head, Tail... >::Tuple (Head const & head, VariadicValues... tail) [inline]
Definition at line 133 of file Tuple.hpp.
      : _head(head), inherited(tail...) {}
template<typename Head , typename... Tail> template<typename... VariadicValues> Tuple< Head, Tail... >::Tuple (Head && head, VariadicValues &&... tail) [inline]
Definition at line 137 of file Tuple.hpp.
      : _head(std::move(head)), inherited(tail...) {}
template<typename Head , typename... Tail> template<typename T , std::enable_if_t< std::is_same< type, typename Tuple< T >::template ofSize< _size >::type >::value > * = nullptr> Tuple< Head, Tail... >::Tuple (T ** tptr) [inline]
Definition at line 167 of file Tuple.hpp.
: _head(**tptr), inherited(tptr + 1) {}
template<typename Head , typename... Tail> Tuple< Head, Tail... >::Tuple (type const & other) [inline]
Definition at line 169 of file Tuple.hpp.
: _head(other.head()), inherited(other.tail()) {}
Member Function Documentation
template<typename Head , typename... Tail> template<typename T , std::enable_if_t< std::is_same< type, typename Tuple< std::remove_reference_t< T >>::template ofSize< _size >::type >::value > * = nullptr> T const* Tuple< Head, Tail... >::at (int ind) const [inline]
Definition at line 103 of file Tuple.hpp.
                             {
    if (ind == 0)
      return &head();
    else
      return tail().template at<T>(ind - 1);
  }
template<typename Head , typename... Tail> void Tuple< Head, Tail... >::free () [inline]
Definition at line 201 of file Tuple.hpp.
              {
    delete[] _head;
    tail().free();
  }
template<typename Head , typename... Tail> template<int ind> typeOf<ind>::type* Tuple< Head, Tail... >::get () [inline]
Definition at line 110 of file Tuple.hpp.
                                                     {
    if (ind <= 0)
      return reinterpret_cast<typename typeOf<ind>::type *>(&head());
    return reinterpret_cast<typename typeOf<ind>::type *>(
        tail().template get<ind - 1>());
  }
References Tuple< Tail >::get().
template<typename Head , typename... Tail> template<int ind> std::add_const_t<typename typeOf<ind>::type>* Tuple< Head, Tail... >::get () const [inline]
Definition at line 91 of file Tuple.hpp.
                                                                           {
    if (ind <= 0)
      return reinterpret_cast<std::add_const_t<typename typeOf<ind>::type> *>(
          &head());
    return reinterpret_cast<std::add_const_t<typename typeOf<ind>::type> *>(
        tail().template get<ind - 1>());
  }
References Tuple< Tail >::get().
template<typename Head , typename... Tail> Head& Tuple< Head, Tail... >::head () [inline]
The head element.
Definition at line 172 of file Tuple.hpp.
{ return _head; }
Referenced by operator<<(), and operator==().
template<typename Head , typename... Tail> const Head& Tuple< Head, Tail... >::head () const [inline]
The head element.
Definition at line 189 of file Tuple.hpp.
{ return _head; }
template<typename Head , typename... Tail> template<typename T , std::enable_if_t< std::is_same< Head, T >::value > * = nullptr> constexpr int Tuple< Head, Tail... >::indexOf (Head const & elem) [inline], [constexpr]
Definition at line 183 of file Tuple.hpp.
                                          {
    int ind = elem == head() ? 0 : 1 + tail().template indexOf<T>(elem);
    return ind > size() || ind < 0 ? -2 : ind;
  }
References Tuple< Tail >::size().
template<typename Head , typename... Tail> template<typename T , std::enable_if_t<!std::is_same< Head, T >::value > * = nullptr> constexpr int Tuple< Head, Tail... >::indexOf (T const & elem) [inline], [constexpr]
Definition at line 176 of file Tuple.hpp.
                                       {
    int ind = 1 + tail().template indexOf<T>(elem);
    return ind >= size() || ind < 0 ? -2 : ind;
  }
References Tuple< Tail >::size().
template<typename Head , typename... Tail> bool Tuple< Head, Tail... >::operator== (type const & other) const [inline]
Definition at line 197 of file Tuple.hpp.
                                           {
    return head() == other.head() && tail() == other.tail();
  }
References head(), and tail().
template<typename Head , typename... Tail> constexpr size_t Tuple< Head, Tail... >::size () const [inline], [constexpr]
Definition at line 89 of file Tuple.hpp.
{ return _size; }
References Tuple< Tail >::_size.
Referenced by operator<<().
template<typename Head , typename... Tail> inherited& Tuple< Head, Tail... >::tail () [inline]
All elements except the first one.
Definition at line 192 of file Tuple.hpp.
{ return *this; }
Referenced by operator<<(), and operator==().
template<typename Head , typename... Tail> const inherited& Tuple< Head, Tail... >::tail () const [inline]
All elements except the first one.
Definition at line 195 of file Tuple.hpp.
{ return *this; }
Member Data Documentation
template<typename Head , typename... Tail> Head Tuple< Head, Tail... >::_head [protected]
Definition at line 207 of file Tuple.hpp.
template<typename Head , typename... Tail> constexpr size_t Tuple< Head, Tail... >::_size = 1 + sizeof...(Tail) [static], [constexpr], [private]
The size of the tuple.
Definition at line 78 of file Tuple.hpp.
Author
Generated automatically by Doxygen for Traveller's App from the source code.