Tuple< Tail >
NAME
Tuple< Tail > - Tuple implementation partially taken from www.stroustrup.com/C++11FAQ.html::variadic-templates It wasn't working out of the box since it was meant as an example of variadic templates rather than an actually usable tuple class but I patched it up and added a whole ton of additional (badly designed) features.
SYNOPSIS
#include <Tuple.hpp>
Classes
struct typeOf
End of recursive template of typeOf.
Public Member Functions
template<typename T > T * at (int ind) const
Return the element at the provided index.
void free ()
Free the elements in the tuple.
template<int ind> void * get ()
Return a pointer to the element with the given index.
template<int ind> const void * get () const
Return a const pointer to the element with the given index.
template<typename T > constexpr int indexOf (const T &elem)
Return the index of the given element.
bool operator== (Tuple<> const &other) const
constexpr size_t size () const
Return the amount of elements in the tuple.
Tuple ()
template<typename T > Tuple (T **tptr)
Private Attributes
size_t _size = 0
Detailed Description
template<typename... Tail>
class Tuple< Tail >"
Tuple implementation partially taken from www.stroustrup.com/C++11FAQ.html::variadic-templates It wasn't working out of the box since it was meant as an example of variadic templates rather than an actually usable tuple class but I patched it up and added a whole ton of additional (badly designed) features.
Definition at line 18 of file Tuple.hpp.
Constructor & Destructor Documentation
template<typename... Tail> template<typename T > Tuple< Tail >::Tuple (T ** tptr) [inline]
Definition at line 31 of file Tuple.hpp.
{}
template<typename... Tail> Tuple< Tail >::Tuple () [inline]
Definition at line 49 of file Tuple.hpp.
{}
Member Function Documentation
template<typename... Tail> template<typename T > T* Tuple< Tail >::at (int ind) const [inline]
Return the element at the provided index.
Definition at line 41 of file Tuple.hpp.
{ return nullptr; }
template<typename... Tail> void Tuple< Tail >::free () [inline]
Free the elements in the tuple.
Definition at line 47 of file Tuple.hpp.
{}
template<typename... Tail> template<int ind> void* Tuple< Tail >::get () [inline]
Return a pointer to the element with the given index.
Bug
if the element overloads operator& this breaks. Horribly
Definition at line 29 of file Tuple.hpp.
{ return nullptr; }
Referenced by Tuple< Head, Tail... >::get(), and Travel::CommandList::printCommandsWithDescription().
template<typename... Tail> template<int ind> const void* Tuple< Tail >::get () const [inline]
Return a const pointer to the element with the given index.
Bug
if the element overloads operator& this breaks. Horribly
Definition at line 38 of file Tuple.hpp.
{ return nullptr; }
template<typename... Tail> template<typename T > constexpr int Tuple< Tail >::indexOf (const T & elem) [inline], [constexpr]
Return the index of the given element.
Definition at line 34 of file Tuple.hpp.
{ return 1; }
template<typename... Tail> bool Tuple< Tail >::operator== (Tuple<> const & other) const [inline]
Definition at line 50 of file Tuple.hpp.
{ return true; }
template<typename... Tail> constexpr size_t Tuple< Tail >::size () const [inline], [constexpr]
Return the amount of elements in the tuple.
Definition at line 44 of file Tuple.hpp.
{ return _size; }
Referenced by Tuple< Head, Tail... >::indexOf().
Member Data Documentation
template<typename... Tail> size_t Tuple< Tail >::_size = 0 [private]
Definition at line 20 of file Tuple.hpp.
Referenced by Tuple< Tail... >::size(), and Tuple< Head, Tail... >::size().
Author
Generated automatically by Doxygen for Traveller's App from the source code.