.TH "TravellersApp/src/User.hpp" 3 "Wed Jun 10 2020" "Version 1.0" "Traveller's App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TravellersApp/src/User.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <filesystem>\fP
.br
\fC#include 'VisitBuilder\&.hpp'\fP
.br
\fC#include 'collection/ArrayList\&.hpp'\fP
.br
\fC#include 'parser/CSV\&.hpp'\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUser\fP"
.br
.RI "This class is responsible for storing and loading information regarding the user\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Traveller's App from the source code\&.
