User
NAME
User - This class is responsible for storing and loading information regarding the user.
SYNOPSIS
#include <User.hpp>
Public Member Functions
void addFriend (const char *name)
Add the provided user as a friend.
void addVisit (Travel::VisitBuilder &vb)
Register the visit described by the provided VisitBuilder with the user.
forType< char * >::repeat< 5 >::apply< Tuple > & destinationStats (const char *dest)
Return a reference to the information about a visit to a provided destination stored in a tuple.
ArrayList< char * > & getFriends ()
Return a reference to the list of friend names.
const char * getName () const
Return the name of the user.
bool hasFriend (const char *name)
Check if the provided user is a friend of the current user.
bool hasVisited (const char *dest)
Checks if user has visited the provided destination.
void listFriends ()
Print the user's friends to stdout.
bool operator== (User const &other)
Users are only differentiated via their username.
void removeFriend (const char *name)
Remove the provided user from the user's list of friends.
User ()=delete
User (const char *name)
~User ()
Private Member Functions
void setUserName (const char *_username)
Sets the username.
Private Attributes
forType< char * >::repeat< 5 >::apply< CSV > destinations
char * friendDBPath = nullptr
ArrayList< char * > friends
HashMap< SimpleString, ArrayList< SimpleString > > pics
char * username = nullptr
char * usrDBPath = nullptr
Detailed Description
This class is responsible for storing and loading information regarding the user.
All reading/writing of information is reliant on CSV. All information is stored as a char*, so additional conversion (such as to int or Date) may be necessary.
Definition at line 31 of file User.hpp.
Constructor & Destructor Documentation
User::User () [delete]
User::User (const char * name) [inline]
Definition at line 100 of file User.hpp.
                         {
    setUserName(name);
    CSV<const char *> friendsCSV("name");
    friendsCSV.load(friendDBPath);
    destinations.load(usrDBPath);
    auto names = friendsCSV.getKeys();
    if (names.get()) {
      for (int i = 0; i < names->length(); i++) {
        addFriend(names->get(i));
      }
    }
    for (const auto &entry : std::filesystem::directory_iterator(username)) {
      auto epath = entry.path();
      if (epath.extension().string().compare(".db") != 0)
        continue;
      auto dest = SimpleString(epath.filename().stem().c_str());
      auto path = epath.c_str();
      CSV<char *> s("pics");
      s.load(path);
      ArrayList<SimpleString> l = *s.getKeys()->template map<SimpleString>(
          [](char *const(&s)) { return SimpleString(s); });
      pics.put(dest, l);
    }
  }
References addFriend(), destinations, friendDBPath, CSV< Types >::getKeys(), CSV< Types >::load(), pics, HashMap< Key, Value >::put(), setUserName(), username, and usrDBPath.
User::~User () [inline]
Definition at line 219 of file User.hpp.
          {
    CSV<char *> friendsCSV("name");
    for (int i = 0; i < friends.length(); i++) {
      friendsCSV.addEntry(friends.get(i));
    }
    if (std::filesystem::exists(username) ||
        std::filesystem::create_directory(username)) {
      friendsCSV.save(friendDBPath);
      destinations.save(usrDBPath);
      auto kd = pics.keys();
      auto vd = pics.values();
      auto usrln = strlen(username);
      for (int i = 0; i < kd->length(); i++) {
        auto key = kd->get(i);
        auto value = vd->get(i);
        auto kpath = new char[usrln + 1 + key.length() + 3 + 1];
        strcpy(kpath, username);
        strcpy(kpath + usrln, "/");
        strcpy(kpath + usrln + 1, key.get());
        strcpy(kpath + usrln + 1 + key.length(), ".db");
        std::ofstream file(kpath);
        if (file.is_open()) {
          file << "\"pics\"" << std::endl;
          value.foreach ([&file](SimpleString const(&pic)) {
            file << "\"" << pic << "\"" << std::endl;
          });
        } else {
          std::cerr << "Could not open " << kpath << " for write." << std::endl;
        }
        file.close();
        delete[] kpath;
      }
    } else {
      std::cerr << "Failed to create directory:" << username
                << ". Cannot save userdata";
    }
    if (username)
      delete[] username;
    if (friendDBPath)
      delete[] friendDBPath;
    if (usrDBPath)
      delete[] usrDBPath;
  }
References CSV< Types >::addEntry(), destinations, friendDBPath, friends, ArrayList< A >::get(), HashMap< Key, Value >::keys(), ArrayList< A >::length(), pics, CSV< Types >::save(), username, usrDBPath, and HashMap< Key, Value >::values().
Member Function Documentation
void User::addFriend (const char * name) [inline]
Add the provided user as a friend.
Parameters
name the name of the user to befriend
Definition at line 135 of file User.hpp.
                                   {
    auto userNameInd = friends.find(
        [name](char *const(&key)) { return strcmp(key, name) == 0; });
    if (userNameInd >= 0) {
      std::cerr << name << " is already your friend." << std::endl;
      return;
    }
    auto _name = new char[strlen(name) + 1];
    strcpy(_name, name);
    friends.append(_name);
  }
References ArrayList< A >::append(), ArrayList< A >::find(), and friends.
Referenced by User().
void User::addVisit (Travel::VisitBuilder & vb) [inline]
Register the visit described by the provided VisitBuilder with the user.
Parameters
vb the VisitBuilder.
Definition at line 187 of file User.hpp.
                                        {
    char *dest = vb.getDestination();
    if (!dest)
      return;
    Travel::Date from = vb.getFrom();
    Travel::Date to = vb.getTo();
    int rating = vb.getRating();
    char *comment = vb.getComment() ? vb.getComment() : new char[1];
    if (!vb.getComment())
      comment[0] = '\0';
    char *sfrom = new char[11];
    char *sto = new char[11];
    from.getString(sfrom);
    to.getString(sto);
    char *srating = new char[3];
    if (rating == -1) {
      srating[0] = '-';
      srating[1] = '1';
      srating[2] = '\0';
    } else {
      srating[0] = (char)(48 + rating);
      srating[1] = '\0';
    }
    destinations.addEntry(dest, sfrom, sto, srating, comment);
    pics.put(dest, vb.getPics());
  }
References destinations, Travel::VisitBuilder::getComment(), Travel::VisitBuilder::getDestination(), Travel::VisitBuilder::getFrom(), Travel::VisitBuilder::getPics(), Travel::VisitBuilder::getRating(), Travel::Date::getString(), Travel::VisitBuilder::getTo(), pics, and HashMap< Key, Value >::put().
forType<char *>::repeat<5>::apply<Tuple>& User::destinationStats (const char * dest) [inline]
Return a reference to the information about a visit to a provided destination stored in a tuple. INDEX * 0 * 1 * 2 * 3 * 4 *
STORE * DESTINATION * FROM * TO * RATING * COMMENT *
Parameters
dest the destination whose information to return
Returns
the information for the destination
Definition at line 81 of file User.hpp.
                                                                           {
    auto ind = destinations.getKeys()->find(
        [&dest](char *const(&key)) { return strcmp(dest, key) == 0; });
    return destinations.getRow(ind);
  }
References destinations.
ArrayList<char *>& User::getFriends () [inline]
Return a reference to the list of friend names.
Returns
the list of friends
Definition at line 68 of file User.hpp.
{ return friends; }
References friends.
const char* User::getName () const [inline]
Return the name of the user.
Definition at line 129 of file User.hpp.
{ return username; }
References username.
Referenced by Travel::TravelState::login(), and operator==().
bool User::hasFriend (const char * name) [inline]
Check if the provided user is a friend of the current user.
Parameters
the name of the user to check
Definition at line 169 of file User.hpp.
                                   {
    return friends.find([&name](char *fr) { return strcmp(name, fr) == 0; }) >=
           0;
  }
References ArrayList< A >::find(), and friends.
bool User::hasVisited (const char * dest) [inline]
Checks if user has visited the provided destination.
Parameters
dest the destination to check.
Returns
has the user visited the destination
Definition at line 92 of file User.hpp.
                                    {
    return destinations.getKeys()->find([&dest](char *const(&key)) {
      return strcmp(dest, key) == 0;
    }) >= 0;
  }
References destinations.
void User::listFriends () [inline]
Print the user's friends to stdout.
Definition at line 161 of file User.hpp.
                     {
    friends.foreach ([](char *fr) { std::cout << fr << std::endl; });
  }
References ArrayList< A >::foreach(), and friends.
bool User::operator== (User const & other) [inline]
Users are only differentiated via their username. Hence the name being unique.
Definition at line 178 of file User.hpp.
                                     {
    return strcmp(getName(), other.getName()) == 0;
  }
References getName().
void User::removeFriend (const char * name) [inline]
Remove the provided user from the user's list of friends.
Parameters
name the name of the user to befriend
Definition at line 151 of file User.hpp.
                                      {
    auto rem =
        friends.removeIf([name](char *fr) { return strcmp(name, fr) == 0; });
    if (rem->isDefined()) {
      delete[] rem->get();
    }
  }
References friends, and ArrayList< A >::removeIf().
void User::setUserName (const char * _username) [inline], [private]
Sets the username. Also generates the paths to where information for the user is stored.
Parameters
_username the new username
Definition at line 47 of file User.hpp.
                                          {
    if (username)
      delete[] username;
    if (friendDBPath)
      delete[] friendDBPath;
    username = new char[strlen(_username) + 1];
    // /friend.db - 10 chars
    friendDBPath = new char[strlen(_username) + 10 + 1];
    usrDBPath = new char[strlen(_username) + 3 + 1];
    strcpy(username, _username);
    strcpy(friendDBPath, _username);
    strcpy(friendDBPath + strlen(_username), "/db.friend");
    strcpy(usrDBPath, _username);
    strcpy(usrDBPath + strlen(_username), ".db");
  }
References friendDBPath, username, and usrDBPath.
Referenced by User().
Member Data Documentation
forType<char *>::repeat<5>::apply<CSV> User::destinations [private]
Initial value:
{"dest", "from", "to",
                                                      "rating", "comment"}
Definition at line 38 of file User.hpp.
Referenced by addVisit(), destinationStats(), hasVisited(), User(), and ~User().
char* User::friendDBPath = nullptr [private]
Definition at line 34 of file User.hpp.
Referenced by setUserName(), User(), and ~User().
ArrayList<char *> User::friends [private]
Definition at line 36 of file User.hpp.
Referenced by addFriend(), getFriends(), hasFriend(), listFriends(), removeFriend(), and ~User().
HashMap<SimpleString, ArrayList<SimpleString> > User::pics [private]
Definition at line 40 of file User.hpp.
Referenced by addVisit(), User(), and ~User().
char* User::username = nullptr [private]
Definition at line 33 of file User.hpp.
Referenced by getName(), setUserName(), User(), and ~User().
char* User::usrDBPath = nullptr [private]
Definition at line 35 of file User.hpp.
Referenced by setUserName(), User(), and ~User().
Author
Generated automatically by Doxygen for Traveller's App from the source code.