WrongTokenTypeException
NAME
WrongTokenTypeException - Thrown when Interpreter encounters a different token than the one it was expecting.
SYNOPSIS
#include <WrongTokenTypeException.hpp>
Inherits std::exception.
Public Member Functions
WrongTokenTypeException & operator= (WrongTokenTypeException const &other)
virtual const char * what () const throw ()
WrongTokenTypeException (const char *_msg)
WrongTokenTypeException (WrongTokenTypeException const &other)
~WrongTokenTypeException ()
Private Attributes
char * msg
Detailed Description
Thrown when Interpreter encounters a different token than the one it was expecting.
Definition at line 10 of file WrongTokenTypeException.hpp.
Constructor & Destructor Documentation
WrongTokenTypeException::WrongTokenTypeException (const char * _msg) [inline]
Definition at line 17 of file WrongTokenTypeException.hpp.
                                            {
    msg = new char[strlen(_msg) + 1];
    strcpy(msg, _msg);
  }
References msg.
WrongTokenTypeException::~WrongTokenTypeException () [inline]
Definition at line 22 of file WrongTokenTypeException.hpp.
{ delete[] msg; }
References msg.
WrongTokenTypeException::WrongTokenTypeException (WrongTokenTypeException const & other) [inline]
Definition at line 24 of file WrongTokenTypeException.hpp.
                                                                {
    msg = new char[strlen(other.msg) + 1];
    strcpy(msg, other.msg);
  }
References msg.
Member Function Documentation
WrongTokenTypeException& WrongTokenTypeException::operator= (WrongTokenTypeException const & other) [inline]
Definition at line 29 of file WrongTokenTypeException.hpp.
                                                                           {
    if (this == &other)
      return *this;
    msg = new char[strlen(other.msg) + 1];
    strcpy(msg, other.msg);
    return *this;
  }
References msg.
virtual const char* WrongTokenTypeException::what () const [inline], [virtual]
Definition at line 15 of file WrongTokenTypeException.hpp.
{ return msg; }
References msg.
Referenced by Travel::LoginInterpreter::parse(), Travel::VisitInterpreter::parse(), and Travel::HTLInterpreter::parse().
Member Data Documentation
char* WrongTokenTypeException::msg [private]
Definition at line 12 of file WrongTokenTypeException.hpp.
Referenced by operator=(), what(), WrongTokenTypeException(), and ~WrongTokenTypeException().
Author
Generated automatically by Doxygen for Traveller's App from the source code.